// Code generated by internal/cmd/genmanagement. DO NOT EDIT.
//
// Generated from management-registry.json and openapi.json. Regenerate with
// `go run ./internal/cmd/genmanagement`; CI verifies the committed output
// is current.

// The resources management namespace (CONTRACT §27.1).
//
// The resource hierarchy role assignments cascade down.

package axiam

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/google/uuid"
)

// ResourcesAPI is the resources namespace handle.
//
// The resource hierarchy role assignments cascade down.
//
// Acquiring one performs no I/O and allocates nothing meaningful (§27.2
// rule 1); it holds the client and cannot be constructed without one.
type ResourcesAPI struct {
	c     *Client
	scope namespaceScope
}

// callResourcesList builds the resources.list call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *ResourcesAPI) callResourcesList(page PageRequest) managementCall {
	query := url.Values{}
	query = pageQuery(page, query)
	return managementCall{
		operation:    "resources.list",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/resources",
		path:         "/api/v1/resources",
		query:        query,
	}
}

// List issues GET /api/v1/resources.
func (a *ResourcesAPI) List(ctx context.Context, page PageRequest) (Page[Resource], error) {
	call := a.callResourcesList(page)
	return sendManagement[Page[Resource]](ctx, a.c, call)
}

// ListAll walks resources.list to exhaustion, concatenating every page.
//
// The auto-paging form §27.4 rule 4 requires. It stops on an empty page
// even if Total disagrees, so a misreporting server costs one wasted
// request rather than an unbounded loop.
func (a *ResourcesAPI) ListAll(ctx context.Context, start PageRequest) ([]Resource, error) {
	return collectPages(ctx, start, func(ctx context.Context, p PageRequest) (Page[Resource], error) {
		return a.List(ctx, p)
	})
}

// callResourcesCreate builds the resources.create call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *ResourcesAPI) callResourcesCreate(body CreateResourceRequest) managementCall {
	return managementCall{
		operation:    "resources.create",
		method:       http.MethodPost,
		pathTemplate: "/api/v1/resources",
		path:         "/api/v1/resources",
		body:         body,
	}
}

// Create issues POST /api/v1/resources.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *ResourcesAPI) Create(ctx context.Context, body CreateResourceRequest) (Resource, error) {
	call := a.callResourcesCreate(body)
	return sendManagement[Resource](ctx, a.c, call)
}

// callResourcesGet builds the resources.get call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *ResourcesAPI) callResourcesGet(resourceID uuid.UUID) managementCall {
	return managementCall{
		operation:    "resources.get",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/resources/{resource_id}",
		path:         fmt.Sprintf("/api/v1/resources/%s", resourceID.String()),
	}
}

// Get issues GET /api/v1/resources/{resource_id}.
func (a *ResourcesAPI) Get(ctx context.Context, resourceID uuid.UUID) (Resource, error) {
	call := a.callResourcesGet(resourceID)
	return sendManagement[Resource](ctx, a.c, call)
}

// callResourcesUpdate builds the resources.update call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *ResourcesAPI) callResourcesUpdate(resourceID uuid.UUID, body UpdateResourceRequest) managementCall {
	return managementCall{
		operation:    "resources.update",
		method:       http.MethodPut,
		pathTemplate: "/api/v1/resources/{resource_id}",
		path:         fmt.Sprintf("/api/v1/resources/%s", resourceID.String()),
		body:         body,
	}
}

// Update issues PUT /api/v1/resources/{resource_id}.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *ResourcesAPI) Update(ctx context.Context, resourceID uuid.UUID, body UpdateResourceRequest) (Resource, error) {
	call := a.callResourcesUpdate(resourceID, body)
	return sendManagement[Resource](ctx, a.c, call)
}

// callResourcesDelete builds the resources.delete call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *ResourcesAPI) callResourcesDelete(resourceID uuid.UUID) managementCall {
	return managementCall{
		operation:    "resources.delete",
		method:       http.MethodDelete,
		pathTemplate: "/api/v1/resources/{resource_id}",
		path:         fmt.Sprintf("/api/v1/resources/%s", resourceID.String()),
	}
}

// Delete issues DELETE /api/v1/resources/{resource_id}.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *ResourcesAPI) Delete(ctx context.Context, resourceID uuid.UUID) error {
	call := a.callResourcesDelete(resourceID)
	return sendManagementNoContent(ctx, a.c, call)
}

// callResourcesListChildren builds the resources.list_children call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *ResourcesAPI) callResourcesListChildren(resourceID uuid.UUID) managementCall {
	return managementCall{
		operation:    "resources.list_children",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/resources/{resource_id}/children",
		path:         fmt.Sprintf("/api/v1/resources/%s/children", resourceID.String()),
	}
}

// ListChildren issues GET /api/v1/resources/{resource_id}/children.
func (a *ResourcesAPI) ListChildren(ctx context.Context, resourceID uuid.UUID) ([]Resource, error) {
	call := a.callResourcesListChildren(resourceID)
	return sendManagement[[]Resource](ctx, a.c, call)
}

// callResourcesListAncestors builds the resources.list_ancestors call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *ResourcesAPI) callResourcesListAncestors(resourceID uuid.UUID) managementCall {
	return managementCall{
		operation:    "resources.list_ancestors",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/resources/{resource_id}/ancestors",
		path:         fmt.Sprintf("/api/v1/resources/%s/ancestors", resourceID.String()),
	}
}

// ListAncestors issues GET /api/v1/resources/{resource_id}/ancestors.
func (a *ResourcesAPI) ListAncestors(ctx context.Context, resourceID uuid.UUID) ([]Resource, error) {
	call := a.callResourcesListAncestors(resourceID)
	return sendManagement[[]Resource](ctx, a.c, call)
}
