// Code generated by internal/cmd/genmanagement. DO NOT EDIT.
//
// Generated from management-registry.json and openapi.json. Regenerate with
// `go run ./internal/cmd/genmanagement`; CI verifies the committed output
// is current.

// The ssf management namespace (CONTRACT §27.1).
//
// A tenant's Shared Signals Framework streams (CONTRACT §32): which
// receiver -- an OAuth2 client of the tenant -- receives which CAEP and
// RISC security events, as SETs pushed to its endpoint or polled. The
// receiver's own protocol (transmitter metadata, the SSF stream management
// API, polling) is not in this registry.

package axiam

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/google/uuid"
)

// SsfAPI is the ssf namespace handle.
//
// A tenant's Shared Signals Framework streams (CONTRACT §32): which
// receiver -- an OAuth2 client of the tenant -- receives which CAEP and
// RISC security events, as SETs pushed to its endpoint or polled. The
// receiver's own protocol (transmitter metadata, the SSF stream management
// API, polling) is not in this registry.
//
// Acquiring one performs no I/O and allocates nothing meaningful (§27.2
// rule 1); it holds the client and cannot be constructed without one.
type SsfAPI struct {
	c     *Client
	scope namespaceScope
}

// ForTenant addresses a different tenant than the client's own (§27.4 rule 3).
//
// Returns a new handle; the original is unchanged.
func (a *SsfAPI) ForTenant(tenantID uuid.UUID) *SsfAPI {
	return &SsfAPI{c: a.c, scope: a.scope.withTenant(tenantID)}
}

// callSsfListStreams builds the ssf.list_streams call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *SsfAPI) callSsfListStreams(page PageRequest) (managementCall, error) {
	tenantID, err := a.c.resolveTenant(a.scope, "ssf.list_streams")
	if err != nil {
		return managementCall{}, err
	}
	query := url.Values{}
	query = pageQuery(page, query)
	return managementCall{
		operation:    "ssf.list_streams",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/tenants/{tenant_id}/ssf/streams",
		path:         fmt.Sprintf("/api/v1/tenants/%s/ssf/streams", tenantID.String()),
		query:        query,
	}, nil
}

// ListStreams issues GET /api/v1/tenants/{tenant_id}/ssf/streams.
func (a *SsfAPI) ListStreams(ctx context.Context, page PageRequest) (Page[SsfStream], error) {
	call, err := a.callSsfListStreams(page)
	if err != nil {
		var zero Page[SsfStream]
		return zero, err
	}
	return sendManagement[Page[SsfStream]](ctx, a.c, call)
}

// ListStreamsAll walks ssf.list_streams to exhaustion, concatenating every page.
//
// The auto-paging form §27.4 rule 4 requires. It stops on an empty page
// even if Total disagrees, so a misreporting server costs one wasted
// request rather than an unbounded loop.
func (a *SsfAPI) ListStreamsAll(ctx context.Context, start PageRequest) ([]SsfStream, error) {
	return collectPages(ctx, start, func(ctx context.Context, p PageRequest) (Page[SsfStream], error) {
		return a.ListStreams(ctx, p)
	})
}

// callSsfCreateStream builds the ssf.create_stream call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *SsfAPI) callSsfCreateStream(body SsfStreamInput) (managementCall, error) {
	tenantID, err := a.c.resolveTenant(a.scope, "ssf.create_stream")
	if err != nil {
		return managementCall{}, err
	}
	return managementCall{
		operation:    "ssf.create_stream",
		method:       http.MethodPost,
		pathTemplate: "/api/v1/tenants/{tenant_id}/ssf/streams",
		path:         fmt.Sprintf("/api/v1/tenants/%s/ssf/streams", tenantID.String()),
		body:         body.toWire(),
	}, nil
}

// CreateStream issues POST /api/v1/tenants/{tenant_id}/ssf/streams.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *SsfAPI) CreateStream(ctx context.Context, body SsfStreamInput) (SsfStream, error) {
	call, err := a.callSsfCreateStream(body)
	if err != nil {
		var zero SsfStream
		return zero, err
	}
	return sendManagement[SsfStream](ctx, a.c, call)
}

// callSsfGetStream builds the ssf.get_stream call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *SsfAPI) callSsfGetStream(streamID uuid.UUID) (managementCall, error) {
	tenantID, err := a.c.resolveTenant(a.scope, "ssf.get_stream")
	if err != nil {
		return managementCall{}, err
	}
	return managementCall{
		operation:    "ssf.get_stream",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/tenants/{tenant_id}/ssf/streams/{stream_id}",
		path:         fmt.Sprintf("/api/v1/tenants/%s/ssf/streams/%s", tenantID.String(), streamID.String()),
	}, nil
}

// GetStream issues GET /api/v1/tenants/{tenant_id}/ssf/streams/{stream_id}.
func (a *SsfAPI) GetStream(ctx context.Context, streamID uuid.UUID) (SsfStream, error) {
	call, err := a.callSsfGetStream(streamID)
	if err != nil {
		var zero SsfStream
		return zero, err
	}
	return sendManagement[SsfStream](ctx, a.c, call)
}

// callSsfUpdateStream builds the ssf.update_stream call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *SsfAPI) callSsfUpdateStream(streamID uuid.UUID, body SsfStreamInput) (managementCall, error) {
	tenantID, err := a.c.resolveTenant(a.scope, "ssf.update_stream")
	if err != nil {
		return managementCall{}, err
	}
	return managementCall{
		operation:    "ssf.update_stream",
		method:       http.MethodPut,
		pathTemplate: "/api/v1/tenants/{tenant_id}/ssf/streams/{stream_id}",
		path:         fmt.Sprintf("/api/v1/tenants/%s/ssf/streams/%s", tenantID.String(), streamID.String()),
		body:         body.toWire(),
	}, nil
}

// UpdateStream issues PUT /api/v1/tenants/{tenant_id}/ssf/streams/{stream_id}.
//
// This is a REPLACEMENT, not a patch (§27.4 rule 5). The body's required
// fields are NewSsfStreamInput's arguments; an optional member you leave
// unset is omitted and takes its default, not its stored value. What you
// do not carry over from a prior read is not preserved — it is
// overwritten. Read first, change the field you mean, send the whole thing
// back.
//
// An omitted optional member takes its default (§32.2) — EXCEPT
// AuthorizationHeader, WHICH ABSENT KEEPS THE STORED ONE — unless the
// update moves EndpointURL to another scheme, host or port while a header
// is stored: then it must carry AuthorizationHeader again or
// ClearAuthorizationHeader: true, else 400 (§32.3 rule 5). Start from
// SsfStream.ToInput(). An update overtaken by the receiver's own write is
// 409: read the stream again.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *SsfAPI) UpdateStream(ctx context.Context, streamID uuid.UUID, body SsfStreamInput) (SsfStream, error) {
	call, err := a.callSsfUpdateStream(streamID, body)
	if err != nil {
		var zero SsfStream
		return zero, err
	}
	return sendManagement[SsfStream](ctx, a.c, call)
}

// callSsfDeleteStream builds the ssf.delete_stream call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *SsfAPI) callSsfDeleteStream(streamID uuid.UUID) (managementCall, error) {
	tenantID, err := a.c.resolveTenant(a.scope, "ssf.delete_stream")
	if err != nil {
		return managementCall{}, err
	}
	return managementCall{
		operation:    "ssf.delete_stream",
		method:       http.MethodDelete,
		pathTemplate: "/api/v1/tenants/{tenant_id}/ssf/streams/{stream_id}",
		path:         fmt.Sprintf("/api/v1/tenants/%s/ssf/streams/%s", tenantID.String(), streamID.String()),
	}, nil
}

// DeleteStream issues DELETE /api/v1/tenants/{tenant_id}/ssf/streams/{stream_id}.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *SsfAPI) DeleteStream(ctx context.Context, streamID uuid.UUID) error {
	call, err := a.callSsfDeleteStream(streamID)
	if err != nil {
		return err
	}
	return sendManagementNoContent(ctx, a.c, call)
}
