// Code generated by internal/cmd/genmanagement. DO NOT EDIT.
//
// Generated from management-registry.json and openapi.json. Regenerate with
// `go run ./internal/cmd/genmanagement`; CI verifies the committed output
// is current.

// The directory management namespace (CONTRACT §27.1).
//
// A tenant's LDAP / Active Directory identity source (CONTRACT §30): the
// one configuration, the explicit act that links an existing local account
// to its directory entry, and a read-only view of the sync job. Signing in
// needs nothing new -- a directory account calls the same §1 `login`.

package axiam

import (
	"context"
	"fmt"
	"net/http"

	"github.com/google/uuid"
)

// DirectoryAPI is the directory namespace handle.
//
// A tenant's LDAP / Active Directory identity source (CONTRACT §30): the
// one configuration, the explicit act that links an existing local account
// to its directory entry, and a read-only view of the sync job. Signing in
// needs nothing new -- a directory account calls the same §1 `login`.
//
// Acquiring one performs no I/O and allocates nothing meaningful (§27.2
// rule 1); it holds the client and cannot be constructed without one.
type DirectoryAPI struct {
	c     *Client
	scope namespaceScope
}

// ForTenant addresses a different tenant than the client's own (§27.4 rule 3).
//
// Returns a new handle; the original is unchanged.
func (a *DirectoryAPI) ForTenant(tenantID uuid.UUID) *DirectoryAPI {
	return &DirectoryAPI{c: a.c, scope: a.scope.withTenant(tenantID)}
}

// callDirectoryGet builds the directory.get call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *DirectoryAPI) callDirectoryGet() (managementCall, error) {
	tenantID, err := a.c.resolveTenant(a.scope, "directory.get")
	if err != nil {
		return managementCall{}, err
	}
	return managementCall{
		operation:    "directory.get",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/tenants/{tenant_id}/directory",
		path:         fmt.Sprintf("/api/v1/tenants/%s/directory", tenantID.String()),
	}, nil
}

// Get issues GET /api/v1/tenants/{tenant_id}/directory.
func (a *DirectoryAPI) Get(ctx context.Context) (DirectoryConfig, error) {
	call, err := a.callDirectoryGet()
	if err != nil {
		var zero DirectoryConfig
		return zero, err
	}
	return sendManagement[DirectoryConfig](ctx, a.c, call)
}

// callDirectorySet builds the directory.set call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *DirectoryAPI) callDirectorySet(body SetDirectoryConfig) (managementCall, error) {
	tenantID, err := a.c.resolveTenant(a.scope, "directory.set")
	if err != nil {
		return managementCall{}, err
	}
	return managementCall{
		operation:    "directory.set",
		method:       http.MethodPut,
		pathTemplate: "/api/v1/tenants/{tenant_id}/directory",
		path:         fmt.Sprintf("/api/v1/tenants/%s/directory", tenantID.String()),
		body:         body.toWire(),
	}, nil
}

// Set issues PUT /api/v1/tenants/{tenant_id}/directory.
//
// This is a REPLACEMENT, not a patch (§27.4 rule 5). The body's required
// fields are NewSetDirectoryConfig's arguments; an optional member you
// leave unset is omitted and takes its default, not its stored value. What
// you do not carry over from a prior read is not preserved — it is
// overwritten. Read first, change the field you mean, send the whole thing
// back.
//
// MOVING THE CONNECTION REQUIRES THE SECRET AGAIN (§30.3 rule 2): a Set
// that changes URL, StartTLS, BindDn or TrustAnchorsPEM without BindSecret
// is refused 400 and changes nothing. The SDK holds no copy of the secret
// and cannot re-send one for you. BindSecret is required while the tenant
// has no configuration; otherwise absent keeps the stored secret. Every
// other optional member left out is RESET TO ITS DEFAULT — start from
// DirectoryConfig.ToInput(). An enabled directory and an effective
// opaque_mode = required never coexist (409); without the deployment's
// directory key a write carrying a secret is 503.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *DirectoryAPI) Set(ctx context.Context, body SetDirectoryConfig) (DirectoryConfig, error) {
	call, err := a.callDirectorySet(body)
	if err != nil {
		var zero DirectoryConfig
		return zero, err
	}
	return sendManagement[DirectoryConfig](ctx, a.c, call)
}

// callDirectoryUpdate builds the directory.update call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *DirectoryAPI) callDirectoryUpdate(body UpdateDirectoryConfig) (managementCall, error) {
	tenantID, err := a.c.resolveTenant(a.scope, "directory.update")
	if err != nil {
		return managementCall{}, err
	}
	return managementCall{
		operation:    "directory.update",
		method:       http.MethodPatch,
		pathTemplate: "/api/v1/tenants/{tenant_id}/directory",
		path:         fmt.Sprintf("/api/v1/tenants/%s/directory", tenantID.String()),
		body:         body.toWire(),
	}, nil
}

// Update issues PATCH /api/v1/tenants/{tenant_id}/directory.
//
// MOVING THE CONNECTION REQUIRES THE SECRET AGAIN (§30.3 rule 2): an
// Update that changes URL, StartTLS, BindDn or TrustAnchorsPEM without
// BindSecret is refused 400 and changes nothing; the SDK holds no copy of
// the secret to re-send. A member left nil (or, for GroupBaseDn /
// GroupFilter, left absent) is not sent and stays as stored; GroupBaseDn /
// GroupFilter set to NullOf[string]() are sent as null and clear the
// value. An enabled directory and an effective opaque_mode = required
// never coexist (409).
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *DirectoryAPI) Update(ctx context.Context, body UpdateDirectoryConfig) (DirectoryConfig, error) {
	call, err := a.callDirectoryUpdate(body)
	if err != nil {
		var zero DirectoryConfig
		return zero, err
	}
	return sendManagement[DirectoryConfig](ctx, a.c, call)
}

// callDirectoryDelete builds the directory.delete call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *DirectoryAPI) callDirectoryDelete() (managementCall, error) {
	tenantID, err := a.c.resolveTenant(a.scope, "directory.delete")
	if err != nil {
		return managementCall{}, err
	}
	return managementCall{
		operation:    "directory.delete",
		method:       http.MethodDelete,
		pathTemplate: "/api/v1/tenants/{tenant_id}/directory",
		path:         fmt.Sprintf("/api/v1/tenants/%s/directory", tenantID.String()),
	}, nil
}

// Delete issues DELETE /api/v1/tenants/{tenant_id}/directory.
//
// DELETING STOPS THE DIRECTORY, AND ONLY THAT (§30.3 rule 5): directory
// accounts can no longer sign in with a password — there is no fallback
// to a local hash — and the sync stops. Sessions, refresh tokens and
// passkeys those accounts already hold keep working until they expire or
// the accounts are deactivated. There is no unlink: a linked account stays
// a directory account.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *DirectoryAPI) Delete(ctx context.Context) error {
	call, err := a.callDirectoryDelete()
	if err != nil {
		return err
	}
	return sendManagementNoContent(ctx, a.c, call)
}

// callDirectoryLinkAccount builds the directory.link_account call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *DirectoryAPI) callDirectoryLinkAccount(body LinkDirectoryAccount) (managementCall, error) {
	tenantID, err := a.c.resolveTenant(a.scope, "directory.link_account")
	if err != nil {
		return managementCall{}, err
	}
	return managementCall{
		operation:    "directory.link_account",
		method:       http.MethodPost,
		pathTemplate: "/api/v1/tenants/{tenant_id}/directory/links",
		path:         fmt.Sprintf("/api/v1/tenants/%s/directory/links", tenantID.String()),
		body:         body,
	}, nil
}

// LinkAccount issues POST /api/v1/tenants/{tenant_id}/directory/links.
//
// SIGNS THE ACCOUNT'S OWNER OUT EVERYWHERE (§30.3 rule 6): linking
// deletes the account's WebAuthn credentials and federation links, revokes
// its User certificates, all its sessions and its OAuth2 refresh tokens
// (TOTP is kept). The entry is found by the account's own username; a
// repeat on an already-linked account answers WasAlreadyLinked and repeats
// the revocations.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *DirectoryAPI) LinkAccount(ctx context.Context, body LinkDirectoryAccount) (DirectoryLinkResult, error) {
	call, err := a.callDirectoryLinkAccount(body)
	if err != nil {
		var zero DirectoryLinkResult
		return zero, err
	}
	return sendManagement[DirectoryLinkResult](ctx, a.c, call)
}

// callDirectoryGetSyncStatus builds the directory.get_sync_status call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *DirectoryAPI) callDirectoryGetSyncStatus() (managementCall, error) {
	tenantID, err := a.c.resolveTenant(a.scope, "directory.get_sync_status")
	if err != nil {
		return managementCall{}, err
	}
	return managementCall{
		operation:    "directory.get_sync_status",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/tenants/{tenant_id}/directory/sync-status",
		path:         fmt.Sprintf("/api/v1/tenants/%s/directory/sync-status", tenantID.String()),
	}, nil
}

// GetSyncStatus issues GET /api/v1/tenants/{tenant_id}/directory/sync-status.
func (a *DirectoryAPI) GetSyncStatus(ctx context.Context) (DirectorySyncStatus, error) {
	call, err := a.callDirectoryGetSyncStatus()
	if err != nil {
		var zero DirectorySyncStatus
		return zero, err
	}
	return sendManagement[DirectorySyncStatus](ctx, a.c, call)
}
