// Code generated by internal/cmd/genmanagement. DO NOT EDIT.
//
// Generated from management-registry.json and openapi.json. Regenerate with
// `go run ./internal/cmd/genmanagement`; CI verifies the committed output
// is current.

// The groups management namespace (CONTRACT §27.1).
//
// Named collections of users. Roles assigned to a group are inherited by
// every member.

package axiam

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/google/uuid"
)

// GroupsAPI is the groups namespace handle.
//
// Named collections of users. Roles assigned to a group are inherited by
// every member.
//
// Acquiring one performs no I/O and allocates nothing meaningful (§27.2
// rule 1); it holds the client and cannot be constructed without one.
type GroupsAPI struct {
	c     *Client
	scope namespaceScope
}

// callGroupsList builds the groups.list call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *GroupsAPI) callGroupsList(page PageRequest) managementCall {
	query := url.Values{}
	query = pageQuery(page, query)
	return managementCall{
		operation:    "groups.list",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/groups",
		path:         "/api/v1/groups",
		query:        query,
	}
}

// List issues GET /api/v1/groups.
func (a *GroupsAPI) List(ctx context.Context, page PageRequest) (Page[Group], error) {
	call := a.callGroupsList(page)
	return sendManagement[Page[Group]](ctx, a.c, call)
}

// ListAll walks groups.list to exhaustion, concatenating every page.
//
// The auto-paging form §27.4 rule 4 requires. It stops on an empty page
// even if Total disagrees, so a misreporting server costs one wasted
// request rather than an unbounded loop.
func (a *GroupsAPI) ListAll(ctx context.Context, start PageRequest) ([]Group, error) {
	return collectPages(ctx, start, func(ctx context.Context, p PageRequest) (Page[Group], error) {
		return a.List(ctx, p)
	})
}

// callGroupsCreate builds the groups.create call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *GroupsAPI) callGroupsCreate(body CreateGroupRequest) managementCall {
	return managementCall{
		operation:    "groups.create",
		method:       http.MethodPost,
		pathTemplate: "/api/v1/groups",
		path:         "/api/v1/groups",
		body:         body,
	}
}

// Create issues POST /api/v1/groups.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *GroupsAPI) Create(ctx context.Context, body CreateGroupRequest) (Group, error) {
	call := a.callGroupsCreate(body)
	return sendManagement[Group](ctx, a.c, call)
}

// callGroupsGet builds the groups.get call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *GroupsAPI) callGroupsGet(groupID uuid.UUID) managementCall {
	return managementCall{
		operation:    "groups.get",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/groups/{group_id}",
		path:         fmt.Sprintf("/api/v1/groups/%s", groupID.String()),
	}
}

// Get issues GET /api/v1/groups/{group_id}.
func (a *GroupsAPI) Get(ctx context.Context, groupID uuid.UUID) (Group, error) {
	call := a.callGroupsGet(groupID)
	return sendManagement[Group](ctx, a.c, call)
}

// callGroupsUpdate builds the groups.update call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *GroupsAPI) callGroupsUpdate(groupID uuid.UUID, body UpdateGroup) managementCall {
	return managementCall{
		operation:    "groups.update",
		method:       http.MethodPut,
		pathTemplate: "/api/v1/groups/{group_id}",
		path:         fmt.Sprintf("/api/v1/groups/%s", groupID.String()),
		body:         body,
	}
}

// Update issues PUT /api/v1/groups/{group_id}.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *GroupsAPI) Update(ctx context.Context, groupID uuid.UUID, body UpdateGroup) (Group, error) {
	call := a.callGroupsUpdate(groupID, body)
	return sendManagement[Group](ctx, a.c, call)
}

// callGroupsDelete builds the groups.delete call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *GroupsAPI) callGroupsDelete(groupID uuid.UUID) managementCall {
	return managementCall{
		operation:    "groups.delete",
		method:       http.MethodDelete,
		pathTemplate: "/api/v1/groups/{group_id}",
		path:         fmt.Sprintf("/api/v1/groups/%s", groupID.String()),
	}
}

// Delete issues DELETE /api/v1/groups/{group_id}.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *GroupsAPI) Delete(ctx context.Context, groupID uuid.UUID) error {
	call := a.callGroupsDelete(groupID)
	return sendManagementNoContent(ctx, a.c, call)
}

// callGroupsListMembers builds the groups.list_members call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *GroupsAPI) callGroupsListMembers(groupID uuid.UUID, page PageRequest) managementCall {
	query := url.Values{}
	query = pageQuery(page, query)
	return managementCall{
		operation:    "groups.list_members",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/groups/{group_id}/members",
		path:         fmt.Sprintf("/api/v1/groups/%s/members", groupID.String()),
		query:        query,
	}
}

// ListMembers issues GET /api/v1/groups/{group_id}/members.
func (a *GroupsAPI) ListMembers(ctx context.Context, groupID uuid.UUID, page PageRequest) (Page[UserResponse], error) {
	call := a.callGroupsListMembers(groupID, page)
	return sendManagement[Page[UserResponse]](ctx, a.c, call)
}

// ListMembersAll walks groups.list_members to exhaustion, concatenating every page.
//
// The auto-paging form §27.4 rule 4 requires. It stops on an empty page
// even if Total disagrees, so a misreporting server costs one wasted
// request rather than an unbounded loop.
func (a *GroupsAPI) ListMembersAll(ctx context.Context, groupID uuid.UUID, start PageRequest) ([]UserResponse, error) {
	return collectPages(ctx, start, func(ctx context.Context, p PageRequest) (Page[UserResponse], error) {
		return a.ListMembers(ctx, groupID, p)
	})
}

// callGroupsAddMember builds the groups.add_member call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *GroupsAPI) callGroupsAddMember(groupID uuid.UUID, body AddMemberRequest) managementCall {
	return managementCall{
		operation:    "groups.add_member",
		method:       http.MethodPost,
		pathTemplate: "/api/v1/groups/{group_id}/members",
		path:         fmt.Sprintf("/api/v1/groups/%s/members", groupID.String()),
		body:         body,
	}
}

// AddMember issues POST /api/v1/groups/{group_id}/members.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *GroupsAPI) AddMember(ctx context.Context, groupID uuid.UUID, body AddMemberRequest) error {
	call := a.callGroupsAddMember(groupID, body)
	return sendManagementNoContent(ctx, a.c, call)
}

// callGroupsRemoveMember builds the groups.remove_member call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *GroupsAPI) callGroupsRemoveMember(groupID uuid.UUID, userID uuid.UUID) managementCall {
	return managementCall{
		operation:    "groups.remove_member",
		method:       http.MethodDelete,
		pathTemplate: "/api/v1/groups/{group_id}/members/{user_id}",
		path:         fmt.Sprintf("/api/v1/groups/%s/members/%s", groupID.String(), userID.String()),
	}
}

// RemoveMember issues DELETE /api/v1/groups/{group_id}/members/{user_id}.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *GroupsAPI) RemoveMember(ctx context.Context, groupID uuid.UUID, userID uuid.UUID) error {
	call := a.callGroupsRemoveMember(groupID, userID)
	return sendManagementNoContent(ctx, a.c, call)
}

// callGroupsListRoles builds the groups.list_roles call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *GroupsAPI) callGroupsListRoles(groupID uuid.UUID) managementCall {
	return managementCall{
		operation:    "groups.list_roles",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/groups/{group_id}/roles",
		path:         fmt.Sprintf("/api/v1/groups/%s/roles", groupID.String()),
	}
}

// ListRoles issues GET /api/v1/groups/{group_id}/roles.
func (a *GroupsAPI) ListRoles(ctx context.Context, groupID uuid.UUID) ([]RoleAssignment, error) {
	call := a.callGroupsListRoles(groupID)
	return sendManagement[[]RoleAssignment](ctx, a.c, call)
}
