// Code generated by internal/cmd/genmanagement. DO NOT EDIT.
//
// Generated from management-registry.json and openapi.json. Regenerate with
// `go run ./internal/cmd/genmanagement`; CI verifies the committed output
// is current.

// The settings management namespace (CONTRACT §27.1).
//
// Effective settings, and the organization/tenant layers they resolve
// from.

package axiam

import (
	"context"
	"fmt"
	"net/http"

	"github.com/google/uuid"
)

// SettingsAPI is the settings namespace handle.
//
// Effective settings, and the organization/tenant layers they resolve
// from.
//
// Acquiring one performs no I/O and allocates nothing meaningful (§27.2
// rule 1); it holds the client and cannot be constructed without one.
type SettingsAPI struct {
	c     *Client
	scope namespaceScope
}

// InOrg addresses a different organization than the client's own.
//
// §27.4 rule 3: the client's organization is the default, and a
// platform-admin token legitimately overrides it. Returns a new handle;
// the original is unchanged.
func (a *SettingsAPI) InOrg(orgID uuid.UUID) *SettingsAPI {
	return &SettingsAPI{c: a.c, scope: a.scope.withOrg(orgID)}
}

// ForTenant addresses a different tenant than the client's own (§27.4 rule 3).
//
// Returns a new handle; the original is unchanged.
func (a *SettingsAPI) ForTenant(tenantID uuid.UUID) *SettingsAPI {
	return &SettingsAPI{c: a.c, scope: a.scope.withTenant(tenantID)}
}

// callSettingsGetOrg builds the settings.get_org call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *SettingsAPI) callSettingsGetOrg() (managementCall, error) {
	orgID, err := a.c.resolveOrg(a.scope, "settings.get_org")
	if err != nil {
		return managementCall{}, err
	}
	return managementCall{
		operation:    "settings.get_org",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/organizations/{org_id}/settings",
		path:         fmt.Sprintf("/api/v1/organizations/%s/settings", orgID.String()),
	}, nil
}

// GetOrg issues GET /api/v1/organizations/{org_id}/settings.
func (a *SettingsAPI) GetOrg(ctx context.Context) (SecuritySettings, error) {
	call, err := a.callSettingsGetOrg()
	if err != nil {
		var zero SecuritySettings
		return zero, err
	}
	return sendManagement[SecuritySettings](ctx, a.c, call)
}

// callSettingsSetOrg builds the settings.set_org call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *SettingsAPI) callSettingsSetOrg(body SetOrgSettings) (managementCall, error) {
	orgID, err := a.c.resolveOrg(a.scope, "settings.set_org")
	if err != nil {
		return managementCall{}, err
	}
	return managementCall{
		operation:    "settings.set_org",
		method:       http.MethodPut,
		pathTemplate: "/api/v1/organizations/{org_id}/settings",
		path:         fmt.Sprintf("/api/v1/organizations/%s/settings", orgID.String()),
		body:         body,
	}, nil
}

// SetOrg issues PUT /api/v1/organizations/{org_id}/settings.
//
// This is a REPLACEMENT, not a patch (§27.4 rule 5). Every field of the
// body is required, and what you do not carry over from a prior read is
// not preserved — it is overwritten. Read first, change the field you
// mean, send the whole thing back.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *SettingsAPI) SetOrg(ctx context.Context, body SetOrgSettings) (SecuritySettings, error) {
	call, err := a.callSettingsSetOrg(body)
	if err != nil {
		var zero SecuritySettings
		return zero, err
	}
	return sendManagement[SecuritySettings](ctx, a.c, call)
}

// callSettingsGetEffective builds the settings.get_effective call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *SettingsAPI) callSettingsGetEffective() managementCall {
	return managementCall{
		operation:    "settings.get_effective",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/settings",
		path:         "/api/v1/settings",
	}
}

// GetEffective issues GET /api/v1/settings.
func (a *SettingsAPI) GetEffective(ctx context.Context) (SecuritySettings, error) {
	call := a.callSettingsGetEffective()
	return sendManagement[SecuritySettings](ctx, a.c, call)
}

// callSettingsSetEffective builds the settings.set_effective call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *SettingsAPI) callSettingsSetEffective(body TenantSettingsOverride) managementCall {
	return managementCall{
		operation:    "settings.set_effective",
		method:       http.MethodPut,
		pathTemplate: "/api/v1/settings",
		path:         "/api/v1/settings",
		body:         body,
	}
}

// SetEffective issues PUT /api/v1/settings.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *SettingsAPI) SetEffective(ctx context.Context, body TenantSettingsOverride) (SecuritySettings, error) {
	call := a.callSettingsSetEffective(body)
	return sendManagement[SecuritySettings](ctx, a.c, call)
}

// callSettingsGetTenantOverride builds the settings.get_tenant_override call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *SettingsAPI) callSettingsGetTenantOverride() (managementCall, error) {
	tenantID, err := a.c.resolveTenant(a.scope, "settings.get_tenant_override")
	if err != nil {
		return managementCall{}, err
	}
	return managementCall{
		operation:    "settings.get_tenant_override",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/tenants/{tenant_id}/settings",
		path:         fmt.Sprintf("/api/v1/tenants/%s/settings", tenantID.String()),
	}, nil
}

// GetTenantOverride issues GET /api/v1/tenants/{tenant_id}/settings.
func (a *SettingsAPI) GetTenantOverride(ctx context.Context) (TenantSettingsOverride, error) {
	call, err := a.callSettingsGetTenantOverride()
	if err != nil {
		var zero TenantSettingsOverride
		return zero, err
	}
	return sendManagement[TenantSettingsOverride](ctx, a.c, call)
}

// callSettingsSetTenantOverride builds the settings.set_tenant_override call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *SettingsAPI) callSettingsSetTenantOverride(body TenantSettingsOverride) (managementCall, error) {
	tenantID, err := a.c.resolveTenant(a.scope, "settings.set_tenant_override")
	if err != nil {
		return managementCall{}, err
	}
	return managementCall{
		operation:    "settings.set_tenant_override",
		method:       http.MethodPut,
		pathTemplate: "/api/v1/tenants/{tenant_id}/settings",
		path:         fmt.Sprintf("/api/v1/tenants/%s/settings", tenantID.String()),
		body:         body,
	}, nil
}

// SetTenantOverride issues PUT /api/v1/tenants/{tenant_id}/settings.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *SettingsAPI) SetTenantOverride(ctx context.Context, body TenantSettingsOverride) (TenantSettingsOverride, error) {
	call, err := a.callSettingsSetTenantOverride(body)
	if err != nil {
		var zero TenantSettingsOverride
		return zero, err
	}
	return sendManagement[TenantSettingsOverride](ctx, a.c, call)
}

// callSettingsDeleteTenantOverride builds the settings.delete_tenant_override call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *SettingsAPI) callSettingsDeleteTenantOverride() (managementCall, error) {
	tenantID, err := a.c.resolveTenant(a.scope, "settings.delete_tenant_override")
	if err != nil {
		return managementCall{}, err
	}
	return managementCall{
		operation:    "settings.delete_tenant_override",
		method:       http.MethodDelete,
		pathTemplate: "/api/v1/tenants/{tenant_id}/settings",
		path:         fmt.Sprintf("/api/v1/tenants/%s/settings", tenantID.String()),
	}, nil
}

// DeleteTenantOverride issues DELETE /api/v1/tenants/{tenant_id}/settings.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *SettingsAPI) DeleteTenantOverride(ctx context.Context) error {
	call, err := a.callSettingsDeleteTenantOverride()
	if err != nil {
		return err
	}
	return sendManagementNoContent(ctx, a.c, call)
}
