// Code generated by internal/cmd/genmanagement. DO NOT EDIT.
//
// Generated from management-registry.json and openapi.json. Regenerate with
// `go run ./internal/cmd/genmanagement`; CI verifies the committed output
// is current.

// The webhooks management namespace (CONTRACT §27.1).
//
// Outbound event notifications. Delivery signatures are verified with the
// §13 helper, which this namespace configures.

package axiam

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/google/uuid"
)

// WebhooksAPI is the webhooks namespace handle.
//
// Outbound event notifications. Delivery signatures are verified with the
// §13 helper, which this namespace configures.
//
// Acquiring one performs no I/O and allocates nothing meaningful (§27.2
// rule 1); it holds the client and cannot be constructed without one.
type WebhooksAPI struct {
	c     *Client
	scope namespaceScope
}

// callWebhooksList builds the webhooks.list call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *WebhooksAPI) callWebhooksList(page PageRequest) managementCall {
	query := url.Values{}
	query = pageQuery(page, query)
	return managementCall{
		operation:    "webhooks.list",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/webhooks",
		path:         "/api/v1/webhooks",
		query:        query,
	}
}

// List issues GET /api/v1/webhooks.
func (a *WebhooksAPI) List(ctx context.Context, page PageRequest) (Page[WebhookResponse], error) {
	call := a.callWebhooksList(page)
	return sendManagement[Page[WebhookResponse]](ctx, a.c, call)
}

// ListAll walks webhooks.list to exhaustion, concatenating every page.
//
// The auto-paging form §27.4 rule 4 requires. It stops on an empty page
// even if Total disagrees, so a misreporting server costs one wasted
// request rather than an unbounded loop.
func (a *WebhooksAPI) ListAll(ctx context.Context, start PageRequest) ([]WebhookResponse, error) {
	return collectPages(ctx, start, func(ctx context.Context, p PageRequest) (Page[WebhookResponse], error) {
		return a.List(ctx, p)
	})
}

// callWebhooksCreate builds the webhooks.create call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *WebhooksAPI) callWebhooksCreate(body CreateWebhookRequest) managementCall {
	return managementCall{
		operation:    "webhooks.create",
		method:       http.MethodPost,
		pathTemplate: "/api/v1/webhooks",
		path:         "/api/v1/webhooks",
		body:         body.toWire(),
	}
}

// Create issues POST /api/v1/webhooks.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *WebhooksAPI) Create(ctx context.Context, body CreateWebhookRequest) (WebhookResponse, error) {
	call := a.callWebhooksCreate(body)
	return sendManagement[WebhookResponse](ctx, a.c, call)
}

// callWebhooksGet builds the webhooks.get call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *WebhooksAPI) callWebhooksGet(id uuid.UUID) managementCall {
	return managementCall{
		operation:    "webhooks.get",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/webhooks/{id}",
		path:         fmt.Sprintf("/api/v1/webhooks/%s", id.String()),
	}
}

// Get issues GET /api/v1/webhooks/{id}.
func (a *WebhooksAPI) Get(ctx context.Context, id uuid.UUID) (WebhookResponse, error) {
	call := a.callWebhooksGet(id)
	return sendManagement[WebhookResponse](ctx, a.c, call)
}

// callWebhooksUpdate builds the webhooks.update call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *WebhooksAPI) callWebhooksUpdate(id uuid.UUID, body UpdateWebhookRequest) managementCall {
	return managementCall{
		operation:    "webhooks.update",
		method:       http.MethodPut,
		pathTemplate: "/api/v1/webhooks/{id}",
		path:         fmt.Sprintf("/api/v1/webhooks/%s", id.String()),
		body:         body.toWire(),
	}
}

// Update issues PUT /api/v1/webhooks/{id}.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *WebhooksAPI) Update(ctx context.Context, id uuid.UUID, body UpdateWebhookRequest) (WebhookResponse, error) {
	call := a.callWebhooksUpdate(id, body)
	return sendManagement[WebhookResponse](ctx, a.c, call)
}

// callWebhooksDelete builds the webhooks.delete call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *WebhooksAPI) callWebhooksDelete(id uuid.UUID) managementCall {
	return managementCall{
		operation:    "webhooks.delete",
		method:       http.MethodDelete,
		pathTemplate: "/api/v1/webhooks/{id}",
		path:         fmt.Sprintf("/api/v1/webhooks/%s", id.String()),
	}
}

// Delete issues DELETE /api/v1/webhooks/{id}.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *WebhooksAPI) Delete(ctx context.Context, id uuid.UUID) error {
	call := a.callWebhooksDelete(id)
	return sendManagementNoContent(ctx, a.c, call)
}
