// Code generated by internal/cmd/genmanagement. DO NOT EDIT.
//
// Generated from management-registry.json and openapi.json. Regenerate with
// `go run ./internal/cmd/genmanagement`; CI verifies the committed output
// is current.

// The users management namespace (CONTRACT §27.1).
//
// Users within the client's tenant, and the administrative side of their
// second factor and lockout state.

package axiam

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/google/uuid"
)

// UsersAPI is the users namespace handle.
//
// Users within the client's tenant, and the administrative side of their
// second factor and lockout state.
//
// Acquiring one performs no I/O and allocates nothing meaningful (§27.2
// rule 1); it holds the client and cannot be constructed without one.
type UsersAPI struct {
	c     *Client
	scope namespaceScope
}

// callUsersList builds the users.list call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *UsersAPI) callUsersList(page PageRequest) managementCall {
	query := url.Values{}
	query = pageQuery(page, query)
	return managementCall{
		operation:    "users.list",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/users",
		path:         "/api/v1/users",
		query:        query,
	}
}

// List issues GET /api/v1/users.
func (a *UsersAPI) List(ctx context.Context, page PageRequest) (Page[UserResponse], error) {
	call := a.callUsersList(page)
	return sendManagement[Page[UserResponse]](ctx, a.c, call)
}

// ListAll walks users.list to exhaustion, concatenating every page.
//
// The auto-paging form §27.4 rule 4 requires. It stops on an empty page
// even if Total disagrees, so a misreporting server costs one wasted
// request rather than an unbounded loop.
func (a *UsersAPI) ListAll(ctx context.Context, start PageRequest) ([]UserResponse, error) {
	return collectPages(ctx, start, func(ctx context.Context, p PageRequest) (Page[UserResponse], error) {
		return a.List(ctx, p)
	})
}

// callUsersCreate builds the users.create call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *UsersAPI) callUsersCreate(body CreateUserRequest) managementCall {
	return managementCall{
		operation:    "users.create",
		method:       http.MethodPost,
		pathTemplate: "/api/v1/users",
		path:         "/api/v1/users",
		body:         body.toWire(),
	}
}

// Create issues POST /api/v1/users.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *UsersAPI) Create(ctx context.Context, body CreateUserRequest) (UserResponse, error) {
	call := a.callUsersCreate(body)
	return sendManagement[UserResponse](ctx, a.c, call)
}

// callUsersGet builds the users.get call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *UsersAPI) callUsersGet(userID uuid.UUID) managementCall {
	return managementCall{
		operation:    "users.get",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/users/{user_id}",
		path:         fmt.Sprintf("/api/v1/users/%s", userID.String()),
	}
}

// Get issues GET /api/v1/users/{user_id}.
func (a *UsersAPI) Get(ctx context.Context, userID uuid.UUID) (UserResponse, error) {
	call := a.callUsersGet(userID)
	return sendManagement[UserResponse](ctx, a.c, call)
}

// callUsersUpdate builds the users.update call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *UsersAPI) callUsersUpdate(userID uuid.UUID, body UpdateUserRequest) managementCall {
	return managementCall{
		operation:    "users.update",
		method:       http.MethodPut,
		pathTemplate: "/api/v1/users/{user_id}",
		path:         fmt.Sprintf("/api/v1/users/%s", userID.String()),
		body:         body,
	}
}

// Update issues PUT /api/v1/users/{user_id}.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *UsersAPI) Update(ctx context.Context, userID uuid.UUID, body UpdateUserRequest) (UserResponse, error) {
	call := a.callUsersUpdate(userID, body)
	return sendManagement[UserResponse](ctx, a.c, call)
}

// callUsersDelete builds the users.delete call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *UsersAPI) callUsersDelete(userID uuid.UUID) managementCall {
	return managementCall{
		operation:    "users.delete",
		method:       http.MethodDelete,
		pathTemplate: "/api/v1/users/{user_id}",
		path:         fmt.Sprintf("/api/v1/users/%s", userID.String()),
	}
}

// Delete issues DELETE /api/v1/users/{user_id}.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *UsersAPI) Delete(ctx context.Context, userID uuid.UUID) error {
	call := a.callUsersDelete(userID)
	return sendManagementNoContent(ctx, a.c, call)
}

// callUsersListMFAMethods builds the users.list_mfa_methods call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *UsersAPI) callUsersListMFAMethods(userID uuid.UUID) managementCall {
	return managementCall{
		operation:    "users.list_mfa_methods",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/users/{user_id}/mfa-methods",
		path:         fmt.Sprintf("/api/v1/users/%s/mfa-methods", userID.String()),
	}
}

// ListMFAMethods issues GET /api/v1/users/{user_id}/mfa-methods.
func (a *UsersAPI) ListMFAMethods(ctx context.Context, userID uuid.UUID) ([]MFAMethodResponse, error) {
	call := a.callUsersListMFAMethods(userID)
	return sendManagement[[]MFAMethodResponse](ctx, a.c, call)
}

// callUsersDeleteMFAMethod builds the users.delete_mfa_method call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *UsersAPI) callUsersDeleteMFAMethod(userID uuid.UUID, methodID string) managementCall {
	return managementCall{
		operation:    "users.delete_mfa_method",
		method:       http.MethodDelete,
		pathTemplate: "/api/v1/users/{user_id}/mfa-methods/{method_id}",
		path:         fmt.Sprintf("/api/v1/users/%s/mfa-methods/%s", userID.String(), url.PathEscape(methodID)),
	}
}

// DeleteMFAMethod issues DELETE /api/v1/users/{user_id}/mfa-methods/{method_id}.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *UsersAPI) DeleteMFAMethod(ctx context.Context, userID uuid.UUID, methodID string) error {
	call := a.callUsersDeleteMFAMethod(userID, methodID)
	return sendManagementNoContent(ctx, a.c, call)
}

// callUsersResetMFA builds the users.reset_mfa call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *UsersAPI) callUsersResetMFA(userID uuid.UUID) managementCall {
	return managementCall{
		operation:    "users.reset_mfa",
		method:       http.MethodPost,
		pathTemplate: "/api/v1/users/{user_id}/reset-mfa",
		path:         fmt.Sprintf("/api/v1/users/%s/reset-mfa", userID.String()),
	}
}

// ResetMFA issues POST /api/v1/users/{user_id}/reset-mfa.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *UsersAPI) ResetMFA(ctx context.Context, userID uuid.UUID) error {
	call := a.callUsersResetMFA(userID)
	return sendManagementNoContent(ctx, a.c, call)
}

// callUsersUnlock builds the users.unlock call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *UsersAPI) callUsersUnlock(userID uuid.UUID) managementCall {
	return managementCall{
		operation:    "users.unlock",
		method:       http.MethodPost,
		pathTemplate: "/api/v1/users/{user_id}/unlock",
		path:         fmt.Sprintf("/api/v1/users/%s/unlock", userID.String()),
	}
}

// Unlock issues POST /api/v1/users/{user_id}/unlock.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *UsersAPI) Unlock(ctx context.Context, userID uuid.UUID) (UserResponse, error) {
	call := a.callUsersUnlock(userID)
	return sendManagement[UserResponse](ctx, a.c, call)
}

// callUsersListRoles builds the users.list_roles call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *UsersAPI) callUsersListRoles(userID uuid.UUID) managementCall {
	return managementCall{
		operation:    "users.list_roles",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/users/{user_id}/roles",
		path:         fmt.Sprintf("/api/v1/users/%s/roles", userID.String()),
	}
}

// ListRoles issues GET /api/v1/users/{user_id}/roles.
func (a *UsersAPI) ListRoles(ctx context.Context, userID uuid.UUID) ([]RoleAssignment, error) {
	call := a.callUsersListRoles(userID)
	return sendManagement[[]RoleAssignment](ctx, a.c, call)
}
