// Code generated by internal/cmd/genmanagement. DO NOT EDIT.
//
// Generated from management-registry.json and openapi.json. Regenerate with
// `go run ./internal/cmd/genmanagement`; CI verifies the committed output
// is current.

// The organizations management namespace (CONTRACT §27.1).
//
// Organizations an SDK client may read and configure. Creation and
// deletion are outside the SDK boundary (§27.0).

package axiam

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/google/uuid"
)

// OrganizationsAPI is the organizations namespace handle.
//
// Organizations an SDK client may read and configure. Creation and
// deletion are outside the SDK boundary (§27.0).
//
// Acquiring one performs no I/O and allocates nothing meaningful (§27.2
// rule 1); it holds the client and cannot be constructed without one.
type OrganizationsAPI struct {
	c     *Client
	scope namespaceScope
}

// InOrg addresses a different organization than the client's own.
//
// §27.4 rule 3: the client's organization is the default, and a
// platform-admin token legitimately overrides it. Returns a new handle;
// the original is unchanged.
func (a *OrganizationsAPI) InOrg(orgID uuid.UUID) *OrganizationsAPI {
	return &OrganizationsAPI{c: a.c, scope: a.scope.withOrg(orgID)}
}

// callOrganizationsList builds the organizations.list call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *OrganizationsAPI) callOrganizationsList(page PageRequest) managementCall {
	query := url.Values{}
	query = pageQuery(page, query)
	return managementCall{
		operation:    "organizations.list",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/organizations",
		path:         "/api/v1/organizations",
		query:        query,
	}
}

// List issues GET /api/v1/organizations.
func (a *OrganizationsAPI) List(ctx context.Context, page PageRequest) (Page[Organization], error) {
	call := a.callOrganizationsList(page)
	return sendManagement[Page[Organization]](ctx, a.c, call)
}

// ListAll walks organizations.list to exhaustion, concatenating every page.
//
// The auto-paging form §27.4 rule 4 requires. It stops on an empty page
// even if Total disagrees, so a misreporting server costs one wasted
// request rather than an unbounded loop.
func (a *OrganizationsAPI) ListAll(ctx context.Context, start PageRequest) ([]Organization, error) {
	return collectPages(ctx, start, func(ctx context.Context, p PageRequest) (Page[Organization], error) {
		return a.List(ctx, p)
	})
}

// callOrganizationsGet builds the organizations.get call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *OrganizationsAPI) callOrganizationsGet() (managementCall, error) {
	orgID, err := a.c.resolveOrg(a.scope, "organizations.get")
	if err != nil {
		return managementCall{}, err
	}
	return managementCall{
		operation:    "organizations.get",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/organizations/{org_id}",
		path:         fmt.Sprintf("/api/v1/organizations/%s", orgID.String()),
	}, nil
}

// Get issues GET /api/v1/organizations/{org_id}.
func (a *OrganizationsAPI) Get(ctx context.Context) (Organization, error) {
	call, err := a.callOrganizationsGet()
	if err != nil {
		var zero Organization
		return zero, err
	}
	return sendManagement[Organization](ctx, a.c, call)
}

// callOrganizationsUpdate builds the organizations.update call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *OrganizationsAPI) callOrganizationsUpdate(body UpdateOrganizationRequest) (managementCall, error) {
	orgID, err := a.c.resolveOrg(a.scope, "organizations.update")
	if err != nil {
		return managementCall{}, err
	}
	return managementCall{
		operation:    "organizations.update",
		method:       http.MethodPut,
		pathTemplate: "/api/v1/organizations/{org_id}",
		path:         fmt.Sprintf("/api/v1/organizations/%s", orgID.String()),
		body:         body,
	}, nil
}

// Update issues PUT /api/v1/organizations/{org_id}.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *OrganizationsAPI) Update(ctx context.Context, body UpdateOrganizationRequest) (Organization, error) {
	call, err := a.callOrganizationsUpdate(body)
	if err != nil {
		var zero Organization
		return zero, err
	}
	return sendManagement[Organization](ctx, a.c, call)
}
