// Code generated by internal/cmd/genmanagement. DO NOT EDIT.
//
// Generated from management-registry.json and openapi.json. Regenerate with
// `go run ./internal/cmd/genmanagement`; CI verifies the committed output
// is current.

// The email_config management namespace (CONTRACT §27.1).
//
// Transactional-mail transport, configurable at organization level and
// overridable per tenant.

package axiam

import (
	"context"
	"fmt"
	"net/http"

	"github.com/google/uuid"
)

// EmailConfigAPI is the email_config namespace handle.
//
// Transactional-mail transport, configurable at organization level and
// overridable per tenant.
//
// Acquiring one performs no I/O and allocates nothing meaningful (§27.2
// rule 1); it holds the client and cannot be constructed without one.
type EmailConfigAPI struct {
	c     *Client
	scope namespaceScope
}

// InOrg addresses a different organization than the client's own.
//
// §27.4 rule 3: the client's organization is the default, and a
// platform-admin token legitimately overrides it. Returns a new handle;
// the original is unchanged.
func (a *EmailConfigAPI) InOrg(orgID uuid.UUID) *EmailConfigAPI {
	return &EmailConfigAPI{c: a.c, scope: a.scope.withOrg(orgID)}
}

// ForTenant addresses a different tenant than the client's own (§27.4 rule 3).
//
// Returns a new handle; the original is unchanged.
func (a *EmailConfigAPI) ForTenant(tenantID uuid.UUID) *EmailConfigAPI {
	return &EmailConfigAPI{c: a.c, scope: a.scope.withTenant(tenantID)}
}

// callEmailConfigGetOrg builds the email_config.get_org call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *EmailConfigAPI) callEmailConfigGetOrg() (managementCall, error) {
	orgID, err := a.c.resolveOrg(a.scope, "email_config.get_org")
	if err != nil {
		return managementCall{}, err
	}
	return managementCall{
		operation:    "email_config.get_org",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/organizations/{org_id}/email-config",
		path:         fmt.Sprintf("/api/v1/organizations/%s/email-config", orgID.String()),
	}, nil
}

// GetOrg issues GET /api/v1/organizations/{org_id}/email-config.
func (a *EmailConfigAPI) GetOrg(ctx context.Context) (EmailConfig, error) {
	call, err := a.callEmailConfigGetOrg()
	if err != nil {
		var zero EmailConfig
		return zero, err
	}
	return sendManagement[EmailConfig](ctx, a.c, call)
}

// callEmailConfigSetOrg builds the email_config.set_org call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *EmailConfigAPI) callEmailConfigSetOrg(body SetOrgEmailConfig) (managementCall, error) {
	orgID, err := a.c.resolveOrg(a.scope, "email_config.set_org")
	if err != nil {
		return managementCall{}, err
	}
	return managementCall{
		operation:    "email_config.set_org",
		method:       http.MethodPut,
		pathTemplate: "/api/v1/organizations/{org_id}/email-config",
		path:         fmt.Sprintf("/api/v1/organizations/%s/email-config", orgID.String()),
		body:         body,
	}, nil
}

// SetOrg issues PUT /api/v1/organizations/{org_id}/email-config.
//
// This is a REPLACEMENT, not a patch (§27.4 rule 5). Every field of the
// body is required, and what you do not carry over from a prior read is
// not preserved — it is overwritten. Read first, change the field you
// mean, send the whole thing back.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *EmailConfigAPI) SetOrg(ctx context.Context, body SetOrgEmailConfig) (EmailConfig, error) {
	call, err := a.callEmailConfigSetOrg(body)
	if err != nil {
		var zero EmailConfig
		return zero, err
	}
	return sendManagement[EmailConfig](ctx, a.c, call)
}

// callEmailConfigDeleteOrg builds the email_config.delete_org call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *EmailConfigAPI) callEmailConfigDeleteOrg() (managementCall, error) {
	orgID, err := a.c.resolveOrg(a.scope, "email_config.delete_org")
	if err != nil {
		return managementCall{}, err
	}
	return managementCall{
		operation:    "email_config.delete_org",
		method:       http.MethodDelete,
		pathTemplate: "/api/v1/organizations/{org_id}/email-config",
		path:         fmt.Sprintf("/api/v1/organizations/%s/email-config", orgID.String()),
	}, nil
}

// DeleteOrg issues DELETE /api/v1/organizations/{org_id}/email-config.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *EmailConfigAPI) DeleteOrg(ctx context.Context) error {
	call, err := a.callEmailConfigDeleteOrg()
	if err != nil {
		return err
	}
	return sendManagementNoContent(ctx, a.c, call)
}

// callEmailConfigTestOrg builds the email_config.test_org call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *EmailConfigAPI) callEmailConfigTestOrg() (managementCall, error) {
	orgID, err := a.c.resolveOrg(a.scope, "email_config.test_org")
	if err != nil {
		return managementCall{}, err
	}
	return managementCall{
		operation:    "email_config.test_org",
		method:       http.MethodPost,
		pathTemplate: "/api/v1/organizations/{org_id}/email-config/test",
		path:         fmt.Sprintf("/api/v1/organizations/%s/email-config/test", orgID.String()),
	}, nil
}

// TestOrg issues POST /api/v1/organizations/{org_id}/email-config/test.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *EmailConfigAPI) TestOrg(ctx context.Context) (EmailTestResult, error) {
	call, err := a.callEmailConfigTestOrg()
	if err != nil {
		var zero EmailTestResult
		return zero, err
	}
	return sendManagement[EmailTestResult](ctx, a.c, call)
}

// callEmailConfigGetTenant builds the email_config.get_tenant call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *EmailConfigAPI) callEmailConfigGetTenant() (managementCall, error) {
	tenantID, err := a.c.resolveTenant(a.scope, "email_config.get_tenant")
	if err != nil {
		return managementCall{}, err
	}
	return managementCall{
		operation:    "email_config.get_tenant",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/tenants/{tenant_id}/email-config",
		path:         fmt.Sprintf("/api/v1/tenants/%s/email-config", tenantID.String()),
	}, nil
}

// GetTenant issues GET /api/v1/tenants/{tenant_id}/email-config.
func (a *EmailConfigAPI) GetTenant(ctx context.Context) (EmailConfigOverride, error) {
	call, err := a.callEmailConfigGetTenant()
	if err != nil {
		var zero EmailConfigOverride
		return zero, err
	}
	return sendManagement[EmailConfigOverride](ctx, a.c, call)
}

// callEmailConfigSetTenant builds the email_config.set_tenant call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *EmailConfigAPI) callEmailConfigSetTenant(body EmailConfigOverride) (managementCall, error) {
	tenantID, err := a.c.resolveTenant(a.scope, "email_config.set_tenant")
	if err != nil {
		return managementCall{}, err
	}
	return managementCall{
		operation:    "email_config.set_tenant",
		method:       http.MethodPut,
		pathTemplate: "/api/v1/tenants/{tenant_id}/email-config",
		path:         fmt.Sprintf("/api/v1/tenants/%s/email-config", tenantID.String()),
		body:         body,
	}, nil
}

// SetTenant issues PUT /api/v1/tenants/{tenant_id}/email-config.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *EmailConfigAPI) SetTenant(ctx context.Context, body EmailConfigOverride) (EmailConfigOverride, error) {
	call, err := a.callEmailConfigSetTenant(body)
	if err != nil {
		var zero EmailConfigOverride
		return zero, err
	}
	return sendManagement[EmailConfigOverride](ctx, a.c, call)
}

// callEmailConfigDeleteTenant builds the email_config.delete_tenant call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *EmailConfigAPI) callEmailConfigDeleteTenant() (managementCall, error) {
	tenantID, err := a.c.resolveTenant(a.scope, "email_config.delete_tenant")
	if err != nil {
		return managementCall{}, err
	}
	return managementCall{
		operation:    "email_config.delete_tenant",
		method:       http.MethodDelete,
		pathTemplate: "/api/v1/tenants/{tenant_id}/email-config",
		path:         fmt.Sprintf("/api/v1/tenants/%s/email-config", tenantID.String()),
	}, nil
}

// DeleteTenant issues DELETE /api/v1/tenants/{tenant_id}/email-config.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *EmailConfigAPI) DeleteTenant(ctx context.Context) error {
	call, err := a.callEmailConfigDeleteTenant()
	if err != nil {
		return err
	}
	return sendManagementNoContent(ctx, a.c, call)
}

// callEmailConfigTestTenant builds the email_config.test_tenant call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *EmailConfigAPI) callEmailConfigTestTenant() (managementCall, error) {
	tenantID, err := a.c.resolveTenant(a.scope, "email_config.test_tenant")
	if err != nil {
		return managementCall{}, err
	}
	return managementCall{
		operation:    "email_config.test_tenant",
		method:       http.MethodPost,
		pathTemplate: "/api/v1/tenants/{tenant_id}/email-config/test",
		path:         fmt.Sprintf("/api/v1/tenants/%s/email-config/test", tenantID.String()),
	}, nil
}

// TestTenant issues POST /api/v1/tenants/{tenant_id}/email-config/test.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *EmailConfigAPI) TestTenant(ctx context.Context) (EmailTestResult, error) {
	call, err := a.callEmailConfigTestTenant()
	if err != nil {
		var zero EmailTestResult
		return zero, err
	}
	return sendManagement[EmailTestResult](ctx, a.c, call)
}
