// Code generated by internal/cmd/genmanagement. DO NOT EDIT.
//
// Generated from management-registry.json and openapi.json. Regenerate with
// `go run ./internal/cmd/genmanagement`; CI verifies the committed output
// is current.

// The tenants management namespace (CONTRACT §27.1).
//
// Tenants within an organization -- the isolation boundary every other
// namespace is scoped to.

package axiam

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/google/uuid"
)

// TenantsAPI is the tenants namespace handle.
//
// Tenants within an organization -- the isolation boundary every other
// namespace is scoped to.
//
// Acquiring one performs no I/O and allocates nothing meaningful (§27.2
// rule 1); it holds the client and cannot be constructed without one.
type TenantsAPI struct {
	c     *Client
	scope namespaceScope
}

// InOrg addresses a different organization than the client's own.
//
// §27.4 rule 3: the client's organization is the default, and a
// platform-admin token legitimately overrides it. Returns a new handle;
// the original is unchanged.
func (a *TenantsAPI) InOrg(orgID uuid.UUID) *TenantsAPI {
	return &TenantsAPI{c: a.c, scope: a.scope.withOrg(orgID)}
}

// callTenantsList builds the tenants.list call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *TenantsAPI) callTenantsList(page PageRequest) (managementCall, error) {
	orgID, err := a.c.resolveOrg(a.scope, "tenants.list")
	if err != nil {
		return managementCall{}, err
	}
	query := url.Values{}
	query = pageQuery(page, query)
	return managementCall{
		operation:    "tenants.list",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/organizations/{org_id}/tenants",
		path:         fmt.Sprintf("/api/v1/organizations/%s/tenants", orgID.String()),
		query:        query,
	}, nil
}

// List issues GET /api/v1/organizations/{org_id}/tenants.
func (a *TenantsAPI) List(ctx context.Context, page PageRequest) (Page[Tenant], error) {
	call, err := a.callTenantsList(page)
	if err != nil {
		var zero Page[Tenant]
		return zero, err
	}
	return sendManagement[Page[Tenant]](ctx, a.c, call)
}

// ListAll walks tenants.list to exhaustion, concatenating every page.
//
// The auto-paging form §27.4 rule 4 requires. It stops on an empty page
// even if Total disagrees, so a misreporting server costs one wasted
// request rather than an unbounded loop.
func (a *TenantsAPI) ListAll(ctx context.Context, start PageRequest) ([]Tenant, error) {
	return collectPages(ctx, start, func(ctx context.Context, p PageRequest) (Page[Tenant], error) {
		return a.List(ctx, p)
	})
}

// callTenantsCreate builds the tenants.create call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *TenantsAPI) callTenantsCreate(body CreateTenantRequest) (managementCall, error) {
	orgID, err := a.c.resolveOrg(a.scope, "tenants.create")
	if err != nil {
		return managementCall{}, err
	}
	return managementCall{
		operation:    "tenants.create",
		method:       http.MethodPost,
		pathTemplate: "/api/v1/organizations/{org_id}/tenants",
		path:         fmt.Sprintf("/api/v1/organizations/%s/tenants", orgID.String()),
		body:         body,
	}, nil
}

// Create issues POST /api/v1/organizations/{org_id}/tenants.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *TenantsAPI) Create(ctx context.Context, body CreateTenantRequest) (Tenant, error) {
	call, err := a.callTenantsCreate(body)
	if err != nil {
		var zero Tenant
		return zero, err
	}
	return sendManagement[Tenant](ctx, a.c, call)
}

// callTenantsGet builds the tenants.get call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *TenantsAPI) callTenantsGet(tenantID uuid.UUID) (managementCall, error) {
	orgID, err := a.c.resolveOrg(a.scope, "tenants.get")
	if err != nil {
		return managementCall{}, err
	}
	return managementCall{
		operation:    "tenants.get",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/organizations/{org_id}/tenants/{tenant_id}",
		path:         fmt.Sprintf("/api/v1/organizations/%s/tenants/%s", orgID.String(), tenantID.String()),
	}, nil
}

// Get issues GET /api/v1/organizations/{org_id}/tenants/{tenant_id}.
func (a *TenantsAPI) Get(ctx context.Context, tenantID uuid.UUID) (Tenant, error) {
	call, err := a.callTenantsGet(tenantID)
	if err != nil {
		var zero Tenant
		return zero, err
	}
	return sendManagement[Tenant](ctx, a.c, call)
}

// callTenantsUpdate builds the tenants.update call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *TenantsAPI) callTenantsUpdate(tenantID uuid.UUID, body UpdateTenant) (managementCall, error) {
	orgID, err := a.c.resolveOrg(a.scope, "tenants.update")
	if err != nil {
		return managementCall{}, err
	}
	return managementCall{
		operation:    "tenants.update",
		method:       http.MethodPut,
		pathTemplate: "/api/v1/organizations/{org_id}/tenants/{tenant_id}",
		path:         fmt.Sprintf("/api/v1/organizations/%s/tenants/%s", orgID.String(), tenantID.String()),
		body:         body,
	}, nil
}

// Update issues PUT /api/v1/organizations/{org_id}/tenants/{tenant_id}.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *TenantsAPI) Update(ctx context.Context, tenantID uuid.UUID, body UpdateTenant) (Tenant, error) {
	call, err := a.callTenantsUpdate(tenantID, body)
	if err != nil {
		var zero Tenant
		return zero, err
	}
	return sendManagement[Tenant](ctx, a.c, call)
}

// callTenantsDelete builds the tenants.delete call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *TenantsAPI) callTenantsDelete(tenantID uuid.UUID) (managementCall, error) {
	orgID, err := a.c.resolveOrg(a.scope, "tenants.delete")
	if err != nil {
		return managementCall{}, err
	}
	return managementCall{
		operation:    "tenants.delete",
		method:       http.MethodDelete,
		pathTemplate: "/api/v1/organizations/{org_id}/tenants/{tenant_id}",
		path:         fmt.Sprintf("/api/v1/organizations/%s/tenants/%s", orgID.String(), tenantID.String()),
	}, nil
}

// Delete issues DELETE /api/v1/organizations/{org_id}/tenants/{tenant_id}.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *TenantsAPI) Delete(ctx context.Context, tenantID uuid.UUID) error {
	call, err := a.callTenantsDelete(tenantID)
	if err != nil {
		return err
	}
	return sendManagementNoContent(ctx, a.c, call)
}
