// Code generated by internal/cmd/genmanagement. DO NOT EDIT.
//
// Generated from management-registry.json and openapi.json. Regenerate with
// `go run ./internal/cmd/genmanagement`; CI verifies the committed output
// is current.

// The scim_targets management namespace (CONTRACT §27.1).
//
// A tenant's outbound SCIM targets (CONTRACT §31): the downstream SCIM
// 2.0 service providers AXIAM pushes the tenant's users and groups to,
// each with its delivery state. The credential AXIAM pushes with is
// write-only. Deleting a target does not deprovision anything downstream.

package axiam

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/google/uuid"
)

// SCIMTargetsAPI is the scim_targets namespace handle.
//
// A tenant's outbound SCIM targets (CONTRACT §31): the downstream SCIM
// 2.0 service providers AXIAM pushes the tenant's users and groups to,
// each with its delivery state. The credential AXIAM pushes with is
// write-only. Deleting a target does not deprovision anything downstream.
//
// Acquiring one performs no I/O and allocates nothing meaningful (§27.2
// rule 1); it holds the client and cannot be constructed without one.
type SCIMTargetsAPI struct {
	c     *Client
	scope namespaceScope
}

// callSCIMTargetsList builds the scim_targets.list call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *SCIMTargetsAPI) callSCIMTargetsList(page PageRequest) managementCall {
	query := url.Values{}
	query = pageQuery(page, query)
	return managementCall{
		operation:    "scim_targets.list",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/scim-targets",
		path:         "/api/v1/scim-targets",
		query:        query,
	}
}

// List issues GET /api/v1/scim-targets.
func (a *SCIMTargetsAPI) List(ctx context.Context, page PageRequest) (Page[SCIMTargetResponse], error) {
	call := a.callSCIMTargetsList(page)
	return sendManagement[Page[SCIMTargetResponse]](ctx, a.c, call)
}

// ListAll walks scim_targets.list to exhaustion, concatenating every page.
//
// The auto-paging form §27.4 rule 4 requires. It stops on an empty page
// even if Total disagrees, so a misreporting server costs one wasted
// request rather than an unbounded loop.
func (a *SCIMTargetsAPI) ListAll(ctx context.Context, start PageRequest) ([]SCIMTargetResponse, error) {
	return collectPages(ctx, start, func(ctx context.Context, p PageRequest) (Page[SCIMTargetResponse], error) {
		return a.List(ctx, p)
	})
}

// callSCIMTargetsCreate builds the scim_targets.create call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *SCIMTargetsAPI) callSCIMTargetsCreate(body SCIMTargetInput) managementCall {
	return managementCall{
		operation:    "scim_targets.create",
		method:       http.MethodPost,
		pathTemplate: "/api/v1/scim-targets",
		path:         "/api/v1/scim-targets",
		body:         body.toWire(),
	}
}

// Create issues POST /api/v1/scim-targets.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *SCIMTargetsAPI) Create(ctx context.Context, body SCIMTargetInput) (SCIMTargetResponse, error) {
	call := a.callSCIMTargetsCreate(body)
	return sendManagement[SCIMTargetResponse](ctx, a.c, call)
}

// callSCIMTargetsGet builds the scim_targets.get call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *SCIMTargetsAPI) callSCIMTargetsGet(id uuid.UUID) managementCall {
	return managementCall{
		operation:    "scim_targets.get",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/scim-targets/{id}",
		path:         fmt.Sprintf("/api/v1/scim-targets/%s", id.String()),
	}
}

// Get issues GET /api/v1/scim-targets/{id}.
func (a *SCIMTargetsAPI) Get(ctx context.Context, id uuid.UUID) (SCIMTargetResponse, error) {
	call := a.callSCIMTargetsGet(id)
	return sendManagement[SCIMTargetResponse](ctx, a.c, call)
}

// callSCIMTargetsUpdate builds the scim_targets.update call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *SCIMTargetsAPI) callSCIMTargetsUpdate(id uuid.UUID, body SCIMTargetInput) managementCall {
	return managementCall{
		operation:    "scim_targets.update",
		method:       http.MethodPut,
		pathTemplate: "/api/v1/scim-targets/{id}",
		path:         fmt.Sprintf("/api/v1/scim-targets/%s", id.String()),
		body:         body.toWire(),
	}
}

// Update issues PUT /api/v1/scim-targets/{id}.
//
// This is a REPLACEMENT, not a patch (§27.4 rule 5). Every field of the
// body is required, and what you do not carry over from a prior read is
// not preserved — it is overwritten. Read first, change the field you
// mean, send the whole thing back.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *SCIMTargetsAPI) Update(ctx context.Context, id uuid.UUID, body SCIMTargetInput) (SCIMTargetResponse, error) {
	call := a.callSCIMTargetsUpdate(id, body)
	return sendManagement[SCIMTargetResponse](ctx, a.c, call)
}

// callSCIMTargetsDelete builds the scim_targets.delete call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *SCIMTargetsAPI) callSCIMTargetsDelete(id uuid.UUID) managementCall {
	return managementCall{
		operation:    "scim_targets.delete",
		method:       http.MethodDelete,
		pathTemplate: "/api/v1/scim-targets/{id}",
		path:         fmt.Sprintf("/api/v1/scim-targets/%s", id.String()),
	}
}

// Delete issues DELETE /api/v1/scim-targets/{id}.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *SCIMTargetsAPI) Delete(ctx context.Context, id uuid.UUID) error {
	call := a.callSCIMTargetsDelete(id)
	return sendManagementNoContent(ctx, a.c, call)
}

// callSCIMTargetsReconcile builds the scim_targets.reconcile call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *SCIMTargetsAPI) callSCIMTargetsReconcile(id uuid.UUID) managementCall {
	return managementCall{
		operation:    "scim_targets.reconcile",
		method:       http.MethodPost,
		pathTemplate: "/api/v1/scim-targets/{id}/reconcile",
		path:         fmt.Sprintf("/api/v1/scim-targets/%s/reconcile", id.String()),
	}
}

// Reconcile issues POST /api/v1/scim-targets/{id}/reconcile.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *SCIMTargetsAPI) Reconcile(ctx context.Context, id uuid.UUID) (SCIMReconcileAccepted, error) {
	call := a.callSCIMTargetsReconcile(id)
	return sendManagement[SCIMReconcileAccepted](ctx, a.c, call)
}
