// Code generated by internal/cmd/genmanagement. DO NOT EDIT.
//
// Generated from management-registry.json and openapi.json. Regenerate with
// `go run ./internal/cmd/genmanagement`; CI verifies the committed output
// is current.

// The ca_certificates management namespace (CONTRACT §27.1).
//
// Organization CAs and the per-tenant signing CAs chained beneath them.

package axiam

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/google/uuid"
)

// CACertificatesAPI is the ca_certificates namespace handle.
//
// Organization CAs and the per-tenant signing CAs chained beneath them.
//
// Acquiring one performs no I/O and allocates nothing meaningful (§27.2
// rule 1); it holds the client and cannot be constructed without one.
type CACertificatesAPI struct {
	c     *Client
	scope namespaceScope
}

// InOrg addresses a different organization than the client's own.
//
// §27.4 rule 3: the client's organization is the default, and a
// platform-admin token legitimately overrides it. Returns a new handle;
// the original is unchanged.
func (a *CACertificatesAPI) InOrg(orgID uuid.UUID) *CACertificatesAPI {
	return &CACertificatesAPI{c: a.c, scope: a.scope.withOrg(orgID)}
}

// callCACertificatesList builds the ca_certificates.list call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *CACertificatesAPI) callCACertificatesList(page PageRequest) (managementCall, error) {
	orgID, err := a.c.resolveOrg(a.scope, "ca_certificates.list")
	if err != nil {
		return managementCall{}, err
	}
	query := url.Values{}
	query = pageQuery(page, query)
	return managementCall{
		operation:    "ca_certificates.list",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/organizations/{org_id}/ca-certificates",
		path:         fmt.Sprintf("/api/v1/organizations/%s/ca-certificates", orgID.String()),
		query:        query,
	}, nil
}

// List issues GET /api/v1/organizations/{org_id}/ca-certificates.
func (a *CACertificatesAPI) List(ctx context.Context, page PageRequest) (Page[CACertificate], error) {
	call, err := a.callCACertificatesList(page)
	if err != nil {
		var zero Page[CACertificate]
		return zero, err
	}
	return sendManagement[Page[CACertificate]](ctx, a.c, call)
}

// ListAll walks ca_certificates.list to exhaustion, concatenating every page.
//
// The auto-paging form §27.4 rule 4 requires. It stops on an empty page
// even if Total disagrees, so a misreporting server costs one wasted
// request rather than an unbounded loop.
func (a *CACertificatesAPI) ListAll(ctx context.Context, start PageRequest) ([]CACertificate, error) {
	return collectPages(ctx, start, func(ctx context.Context, p PageRequest) (Page[CACertificate], error) {
		return a.List(ctx, p)
	})
}

// callCACertificatesGenerate builds the ca_certificates.generate call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *CACertificatesAPI) callCACertificatesGenerate(body CreateCACertificateRequest) (managementCall, error) {
	orgID, err := a.c.resolveOrg(a.scope, "ca_certificates.generate")
	if err != nil {
		return managementCall{}, err
	}
	return managementCall{
		operation:    "ca_certificates.generate",
		method:       http.MethodPost,
		pathTemplate: "/api/v1/organizations/{org_id}/ca-certificates",
		path:         fmt.Sprintf("/api/v1/organizations/%s/ca-certificates", orgID.String()),
		body:         body,
	}, nil
}

// Generate issues POST /api/v1/organizations/{org_id}/ca-certificates.
//
// Returns secret material, once. private_key_pem is returned by this call
// and by no other; no later Get will return it again, and the Get
// projection has no field where it was. Discarding the result destroys the
// credential (§27.5 rule 3).
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *CACertificatesAPI) Generate(ctx context.Context, body CreateCACertificateRequest) (GeneratedCACertificate, error) {
	call, err := a.callCACertificatesGenerate(body)
	if err != nil {
		var zero GeneratedCACertificate
		return zero, err
	}
	return sendManagement[GeneratedCACertificate](ctx, a.c, call)
}

// callCACertificatesImportCA builds the ca_certificates.import_ca call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *CACertificatesAPI) callCACertificatesImportCA(body ImportCACertificateRequest) (managementCall, error) {
	orgID, err := a.c.resolveOrg(a.scope, "ca_certificates.import_ca")
	if err != nil {
		return managementCall{}, err
	}
	return managementCall{
		operation:    "ca_certificates.import_ca",
		method:       http.MethodPost,
		pathTemplate: "/api/v1/organizations/{org_id}/ca-certificates/import",
		path:         fmt.Sprintf("/api/v1/organizations/%s/ca-certificates/import", orgID.String()),
		body:         body.toWire(),
	}, nil
}

// ImportCA issues POST /api/v1/organizations/{org_id}/ca-certificates/import.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *CACertificatesAPI) ImportCA(ctx context.Context, body ImportCACertificateRequest) (CACertificate, error) {
	call, err := a.callCACertificatesImportCA(body)
	if err != nil {
		var zero CACertificate
		return zero, err
	}
	return sendManagement[CACertificate](ctx, a.c, call)
}

// callCACertificatesGet builds the ca_certificates.get call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *CACertificatesAPI) callCACertificatesGet(id uuid.UUID) (managementCall, error) {
	orgID, err := a.c.resolveOrg(a.scope, "ca_certificates.get")
	if err != nil {
		return managementCall{}, err
	}
	return managementCall{
		operation:    "ca_certificates.get",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/organizations/{org_id}/ca-certificates/{id}",
		path:         fmt.Sprintf("/api/v1/organizations/%s/ca-certificates/%s", orgID.String(), id.String()),
	}, nil
}

// Get issues GET /api/v1/organizations/{org_id}/ca-certificates/{id}.
func (a *CACertificatesAPI) Get(ctx context.Context, id uuid.UUID) (CACertificate, error) {
	call, err := a.callCACertificatesGet(id)
	if err != nil {
		var zero CACertificate
		return zero, err
	}
	return sendManagement[CACertificate](ctx, a.c, call)
}

// callCACertificatesRevoke builds the ca_certificates.revoke call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *CACertificatesAPI) callCACertificatesRevoke(id uuid.UUID) (managementCall, error) {
	orgID, err := a.c.resolveOrg(a.scope, "ca_certificates.revoke")
	if err != nil {
		return managementCall{}, err
	}
	return managementCall{
		operation:    "ca_certificates.revoke",
		method:       http.MethodPost,
		pathTemplate: "/api/v1/organizations/{org_id}/ca-certificates/{id}/revoke",
		path:         fmt.Sprintf("/api/v1/organizations/%s/ca-certificates/%s/revoke", orgID.String(), id.String()),
	}, nil
}

// Revoke issues POST /api/v1/organizations/{org_id}/ca-certificates/{id}/revoke.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *CACertificatesAPI) Revoke(ctx context.Context, id uuid.UUID) error {
	call, err := a.callCACertificatesRevoke(id)
	if err != nil {
		return err
	}
	return sendManagementNoContent(ctx, a.c, call)
}

// callCACertificatesMigrateCustody builds the ca_certificates.migrate_custody call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *CACertificatesAPI) callCACertificatesMigrateCustody(id uuid.UUID) (managementCall, error) {
	orgID, err := a.c.resolveOrg(a.scope, "ca_certificates.migrate_custody")
	if err != nil {
		return managementCall{}, err
	}
	return managementCall{
		operation:    "ca_certificates.migrate_custody",
		method:       http.MethodPost,
		pathTemplate: "/api/v1/organizations/{org_id}/ca-certificates/{id}/migrate-custody",
		path:         fmt.Sprintf("/api/v1/organizations/%s/ca-certificates/%s/migrate-custody", orgID.String(), id.String()),
	}, nil
}

// MigrateCustody issues POST
// /api/v1/organizations/{org_id}/ca-certificates/{id}/migrate-custody.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *CACertificatesAPI) MigrateCustody(ctx context.Context, id uuid.UUID) (MigrateCustodyResponse, error) {
	call, err := a.callCACertificatesMigrateCustody(id)
	if err != nil {
		var zero MigrateCustodyResponse
		return zero, err
	}
	return sendManagement[MigrateCustodyResponse](ctx, a.c, call)
}

// callCACertificatesSetMTLSTrustAnchor builds the ca_certificates.set_mtls_trust_anchor call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *CACertificatesAPI) callCACertificatesSetMTLSTrustAnchor(id uuid.UUID, body SetMTLSTrustAnchor) (managementCall, error) {
	orgID, err := a.c.resolveOrg(a.scope, "ca_certificates.set_mtls_trust_anchor")
	if err != nil {
		return managementCall{}, err
	}
	return managementCall{
		operation:    "ca_certificates.set_mtls_trust_anchor",
		method:       http.MethodPut,
		pathTemplate: "/api/v1/organizations/{org_id}/ca-certificates/{id}/mtls-trust-anchor",
		path:         fmt.Sprintf("/api/v1/organizations/%s/ca-certificates/%s/mtls-trust-anchor", orgID.String(), id.String()),
		body:         body,
	}, nil
}

// SetMTLSTrustAnchor issues PUT
// /api/v1/organizations/{org_id}/ca-certificates/{id}/mtls-trust-anchor.
//
// This is a REPLACEMENT, not a patch (§27.4 rule 5). Every field of the
// body is required, and what you do not carry over from a prior read is
// not preserved — it is overwritten. Read first, change the field you
// mean, send the whole thing back.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *CACertificatesAPI) SetMTLSTrustAnchor(ctx context.Context, id uuid.UUID, body SetMTLSTrustAnchor) (MTLSTrustAnchorResponse, error) {
	call, err := a.callCACertificatesSetMTLSTrustAnchor(id, body)
	if err != nil {
		var zero MTLSTrustAnchorResponse
		return zero, err
	}
	return sendManagement[MTLSTrustAnchorResponse](ctx, a.c, call)
}

// callCACertificatesListSigningCas builds the ca_certificates.list_signing_cas call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *CACertificatesAPI) callCACertificatesListSigningCas(tenantID uuid.UUID, page PageRequest) (managementCall, error) {
	orgID, err := a.c.resolveOrg(a.scope, "ca_certificates.list_signing_cas")
	if err != nil {
		return managementCall{}, err
	}
	query := url.Values{}
	query = pageQuery(page, query)
	return managementCall{
		operation:    "ca_certificates.list_signing_cas",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/organizations/{org_id}/tenants/{tenant_id}/signing-cas",
		path:         fmt.Sprintf("/api/v1/organizations/%s/tenants/%s/signing-cas", orgID.String(), tenantID.String()),
		query:        query,
	}, nil
}

// ListSigningCas issues GET
// /api/v1/organizations/{org_id}/tenants/{tenant_id}/signing-cas.
func (a *CACertificatesAPI) ListSigningCas(ctx context.Context, tenantID uuid.UUID, page PageRequest) (Page[CACertificate], error) {
	call, err := a.callCACertificatesListSigningCas(tenantID, page)
	if err != nil {
		var zero Page[CACertificate]
		return zero, err
	}
	return sendManagement[Page[CACertificate]](ctx, a.c, call)
}

// ListSigningCasAll walks ca_certificates.list_signing_cas to exhaustion, concatenating
// every page.
//
// The auto-paging form §27.4 rule 4 requires. It stops on an empty page
// even if Total disagrees, so a misreporting server costs one wasted
// request rather than an unbounded loop.
func (a *CACertificatesAPI) ListSigningCasAll(ctx context.Context, tenantID uuid.UUID, start PageRequest) ([]CACertificate, error) {
	return collectPages(ctx, start, func(ctx context.Context, p PageRequest) (Page[CACertificate], error) {
		return a.ListSigningCas(ctx, tenantID, p)
	})
}

// callCACertificatesGenerateSigningCA builds the ca_certificates.generate_signing_ca call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *CACertificatesAPI) callCACertificatesGenerateSigningCA(tenantID uuid.UUID, body CreateIntermediateCARequest) (managementCall, error) {
	orgID, err := a.c.resolveOrg(a.scope, "ca_certificates.generate_signing_ca")
	if err != nil {
		return managementCall{}, err
	}
	return managementCall{
		operation:    "ca_certificates.generate_signing_ca",
		method:       http.MethodPost,
		pathTemplate: "/api/v1/organizations/{org_id}/tenants/{tenant_id}/signing-cas",
		path:         fmt.Sprintf("/api/v1/organizations/%s/tenants/%s/signing-cas", orgID.String(), tenantID.String()),
		body:         body,
	}, nil
}

// GenerateSigningCA issues POST
// /api/v1/organizations/{org_id}/tenants/{tenant_id}/signing-cas.
//
// Returns secret material, once. private_key_pem is returned by this call
// and by no other; no later Get will return it again, and the Get
// projection has no field where it was. Discarding the result destroys the
// credential (§27.5 rule 3).
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *CACertificatesAPI) GenerateSigningCA(ctx context.Context, tenantID uuid.UUID, body CreateIntermediateCARequest) (GeneratedCACertificate, error) {
	call, err := a.callCACertificatesGenerateSigningCA(tenantID, body)
	if err != nil {
		var zero GeneratedCACertificate
		return zero, err
	}
	return sendManagement[GeneratedCACertificate](ctx, a.c, call)
}

// callCACertificatesSignSigningCACSR builds the ca_certificates.sign_signing_ca_csr call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *CACertificatesAPI) callCACertificatesSignSigningCACSR(tenantID uuid.UUID, body SignIntermediateCSRRequest) (managementCall, error) {
	orgID, err := a.c.resolveOrg(a.scope, "ca_certificates.sign_signing_ca_csr")
	if err != nil {
		return managementCall{}, err
	}
	return managementCall{
		operation:    "ca_certificates.sign_signing_ca_csr",
		method:       http.MethodPost,
		pathTemplate: "/api/v1/organizations/{org_id}/tenants/{tenant_id}/signing-cas/sign-csr",
		path:         fmt.Sprintf("/api/v1/organizations/%s/tenants/%s/signing-cas/sign-csr", orgID.String(), tenantID.String()),
		body:         body,
	}, nil
}

// SignSigningCACSR issues POST
// /api/v1/organizations/{org_id}/tenants/{tenant_id}/signing-cas/sign-csr.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *CACertificatesAPI) SignSigningCACSR(ctx context.Context, tenantID uuid.UUID, body SignIntermediateCSRRequest) (CACertificate, error) {
	call, err := a.callCACertificatesSignSigningCACSR(tenantID, body)
	if err != nil {
		var zero CACertificate
		return zero, err
	}
	return sendManagement[CACertificate](ctx, a.c, call)
}
