// Code generated by internal/cmd/genmanagement. DO NOT EDIT.
//
// Generated from management-registry.json and openapi.json. Regenerate with
// `go run ./internal/cmd/genmanagement`; CI verifies the committed output
// is current.

// The federation management namespace (CONTRACT §27.1).
//
// Upstream IdP configuration and the per-user links it produces.

package axiam

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/google/uuid"
)

// FederationAPI is the federation namespace handle.
//
// Upstream IdP configuration and the per-user links it produces.
//
// Acquiring one performs no I/O and allocates nothing meaningful (§27.2
// rule 1); it holds the client and cannot be constructed without one.
type FederationAPI struct {
	c     *Client
	scope namespaceScope
}

// callFederationListConfigs builds the federation.list_configs call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *FederationAPI) callFederationListConfigs(page PageRequest) managementCall {
	query := url.Values{}
	query = pageQuery(page, query)
	return managementCall{
		operation:    "federation.list_configs",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/federation-configs",
		path:         "/api/v1/federation-configs",
		query:        query,
	}
}

// ListConfigs issues GET /api/v1/federation-configs.
func (a *FederationAPI) ListConfigs(ctx context.Context, page PageRequest) (Page[FederationConfigResponse], error) {
	call := a.callFederationListConfigs(page)
	return sendManagement[Page[FederationConfigResponse]](ctx, a.c, call)
}

// ListConfigsAll walks federation.list_configs to exhaustion, concatenating every page.
//
// The auto-paging form §27.4 rule 4 requires. It stops on an empty page
// even if Total disagrees, so a misreporting server costs one wasted
// request rather than an unbounded loop.
func (a *FederationAPI) ListConfigsAll(ctx context.Context, start PageRequest) ([]FederationConfigResponse, error) {
	return collectPages(ctx, start, func(ctx context.Context, p PageRequest) (Page[FederationConfigResponse], error) {
		return a.ListConfigs(ctx, p)
	})
}

// callFederationCreateConfig builds the federation.create_config call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *FederationAPI) callFederationCreateConfig(body CreateFederationConfigRequest) managementCall {
	return managementCall{
		operation:    "federation.create_config",
		method:       http.MethodPost,
		pathTemplate: "/api/v1/federation-configs",
		path:         "/api/v1/federation-configs",
		body:         body.toWire(),
	}
}

// CreateConfig issues POST /api/v1/federation-configs.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *FederationAPI) CreateConfig(ctx context.Context, body CreateFederationConfigRequest) (FederationConfigResponse, error) {
	call := a.callFederationCreateConfig(body)
	return sendManagement[FederationConfigResponse](ctx, a.c, call)
}

// callFederationGetConfig builds the federation.get_config call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *FederationAPI) callFederationGetConfig(id uuid.UUID) managementCall {
	return managementCall{
		operation:    "federation.get_config",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/federation-configs/{id}",
		path:         fmt.Sprintf("/api/v1/federation-configs/%s", id.String()),
	}
}

// GetConfig issues GET /api/v1/federation-configs/{id}.
func (a *FederationAPI) GetConfig(ctx context.Context, id uuid.UUID) (FederationConfigResponse, error) {
	call := a.callFederationGetConfig(id)
	return sendManagement[FederationConfigResponse](ctx, a.c, call)
}

// callFederationUpdateConfig builds the federation.update_config call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *FederationAPI) callFederationUpdateConfig(id uuid.UUID, body UpdateFederationConfigRequest) managementCall {
	return managementCall{
		operation:    "federation.update_config",
		method:       http.MethodPut,
		pathTemplate: "/api/v1/federation-configs/{id}",
		path:         fmt.Sprintf("/api/v1/federation-configs/%s", id.String()),
		body:         body.toWire(),
	}
}

// UpdateConfig issues PUT /api/v1/federation-configs/{id}.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *FederationAPI) UpdateConfig(ctx context.Context, id uuid.UUID, body UpdateFederationConfigRequest) (FederationConfigResponse, error) {
	call := a.callFederationUpdateConfig(id, body)
	return sendManagement[FederationConfigResponse](ctx, a.c, call)
}

// callFederationDeleteConfig builds the federation.delete_config call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *FederationAPI) callFederationDeleteConfig(id uuid.UUID) managementCall {
	return managementCall{
		operation:    "federation.delete_config",
		method:       http.MethodDelete,
		pathTemplate: "/api/v1/federation-configs/{id}",
		path:         fmt.Sprintf("/api/v1/federation-configs/%s", id.String()),
	}
}

// DeleteConfig issues DELETE /api/v1/federation-configs/{id}.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *FederationAPI) DeleteConfig(ctx context.Context, id uuid.UUID) error {
	call := a.callFederationDeleteConfig(id)
	return sendManagementNoContent(ctx, a.c, call)
}

// callFederationListUserLinks builds the federation.list_user_links call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *FederationAPI) callFederationListUserLinks(userID uuid.UUID) managementCall {
	return managementCall{
		operation:    "federation.list_user_links",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/federation-links/user/{user_id}",
		path:         fmt.Sprintf("/api/v1/federation-links/user/%s", userID.String()),
	}
}

// ListUserLinks issues GET /api/v1/federation-links/user/{user_id}.
func (a *FederationAPI) ListUserLinks(ctx context.Context, userID uuid.UUID) ([]FederationLinkResponse, error) {
	call := a.callFederationListUserLinks(userID)
	return sendManagement[[]FederationLinkResponse](ctx, a.c, call)
}

// callFederationDeleteLink builds the federation.delete_link call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *FederationAPI) callFederationDeleteLink(id uuid.UUID) managementCall {
	return managementCall{
		operation:    "federation.delete_link",
		method:       http.MethodDelete,
		pathTemplate: "/api/v1/federation-links/{id}",
		path:         fmt.Sprintf("/api/v1/federation-links/%s", id.String()),
	}
}

// DeleteLink issues DELETE /api/v1/federation-links/{id}.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *FederationAPI) DeleteLink(ctx context.Context, id uuid.UUID) error {
	call := a.callFederationDeleteLink(id)
	return sendManagementNoContent(ctx, a.c, call)
}

// callFederationOIDCAuthorize builds the federation.oidc_authorize call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *FederationAPI) callFederationOIDCAuthorize(body OIDCAuthorizeRequest) managementCall {
	return managementCall{
		operation:    "federation.oidc_authorize",
		method:       http.MethodPost,
		pathTemplate: "/api/v1/federation/oidc/authorize",
		path:         "/api/v1/federation/oidc/authorize",
		body:         body,
	}
}

// OIDCAuthorize issues POST /api/v1/federation/oidc/authorize.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *FederationAPI) OIDCAuthorize(ctx context.Context, body OIDCAuthorizeRequest) (OIDCAuthorizeResponse, error) {
	call := a.callFederationOIDCAuthorize(body)
	return sendManagement[OIDCAuthorizeResponse](ctx, a.c, call)
}

// callFederationOIDCCallback builds the federation.oidc_callback call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *FederationAPI) callFederationOIDCCallback(body OIDCCallbackRequest) managementCall {
	return managementCall{
		operation:    "federation.oidc_callback",
		method:       http.MethodPost,
		pathTemplate: "/api/v1/federation/oidc/callback",
		path:         "/api/v1/federation/oidc/callback",
		body:         body,
	}
}

// OIDCCallback issues POST /api/v1/federation/oidc/callback.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *FederationAPI) OIDCCallback(ctx context.Context, body OIDCCallbackRequest) (OIDCCallbackResponse, error) {
	call := a.callFederationOIDCCallback(body)
	return sendManagement[OIDCCallbackResponse](ctx, a.c, call)
}
