// Code generated by internal/cmd/genmanagement. DO NOT EDIT.
//
// Generated from management-registry.json and openapi.json. Regenerate with
// `go run ./internal/cmd/genmanagement`; CI verifies the committed output
// is current.

// The webauthn_policy management namespace (CONTRACT §27.1).
//
// Per-tenant attestation policy governing the §24 ceremonies, and the
// compliance report over it.

package axiam

import (
	"context"
	"fmt"
	"net/http"

	"github.com/google/uuid"
)

// WebauthnPolicyAPI is the webauthn_policy namespace handle.
//
// Per-tenant attestation policy governing the §24 ceremonies, and the
// compliance report over it.
//
// Acquiring one performs no I/O and allocates nothing meaningful (§27.2
// rule 1); it holds the client and cannot be constructed without one.
type WebauthnPolicyAPI struct {
	c     *Client
	scope namespaceScope
}

// ForTenant addresses a different tenant than the client's own (§27.4 rule 3).
//
// Returns a new handle; the original is unchanged.
func (a *WebauthnPolicyAPI) ForTenant(tenantID uuid.UUID) *WebauthnPolicyAPI {
	return &WebauthnPolicyAPI{c: a.c, scope: a.scope.withTenant(tenantID)}
}

// callWebauthnPolicyGet builds the webauthn_policy.get call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *WebauthnPolicyAPI) callWebauthnPolicyGet() (managementCall, error) {
	tenantID, err := a.c.resolveTenant(a.scope, "webauthn_policy.get")
	if err != nil {
		return managementCall{}, err
	}
	return managementCall{
		operation:    "webauthn_policy.get",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/tenants/{tenant_id}/webauthn/attestation-policy",
		path:         fmt.Sprintf("/api/v1/tenants/%s/webauthn/attestation-policy", tenantID.String()),
	}, nil
}

// Get issues GET /api/v1/tenants/{tenant_id}/webauthn/attestation-policy.
func (a *WebauthnPolicyAPI) Get(ctx context.Context) (PolicyResponse, error) {
	call, err := a.callWebauthnPolicyGet()
	if err != nil {
		var zero PolicyResponse
		return zero, err
	}
	return sendManagement[PolicyResponse](ctx, a.c, call)
}

// callWebauthnPolicySet builds the webauthn_policy.set call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *WebauthnPolicyAPI) callWebauthnPolicySet(body WebauthnAttestationPolicy) (managementCall, error) {
	tenantID, err := a.c.resolveTenant(a.scope, "webauthn_policy.set")
	if err != nil {
		return managementCall{}, err
	}
	return managementCall{
		operation:    "webauthn_policy.set",
		method:       http.MethodPut,
		pathTemplate: "/api/v1/tenants/{tenant_id}/webauthn/attestation-policy",
		path:         fmt.Sprintf("/api/v1/tenants/%s/webauthn/attestation-policy", tenantID.String()),
		body:         body,
	}, nil
}

// Set issues PUT /api/v1/tenants/{tenant_id}/webauthn/attestation-policy.
//
// This is a REPLACEMENT, not a patch (§27.4 rule 5). Every field of the
// body is required, and what you do not carry over from a prior read is
// not preserved — it is overwritten. Read first, change the field you
// mean, send the whole thing back.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *WebauthnPolicyAPI) Set(ctx context.Context, body WebauthnAttestationPolicy) (WebauthnAttestationPolicy, error) {
	call, err := a.callWebauthnPolicySet(body)
	if err != nil {
		var zero WebauthnAttestationPolicy
		return zero, err
	}
	return sendManagement[WebauthnAttestationPolicy](ctx, a.c, call)
}

// callWebauthnPolicyComplianceReport builds the webauthn_policy.compliance_report call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *WebauthnPolicyAPI) callWebauthnPolicyComplianceReport() (managementCall, error) {
	tenantID, err := a.c.resolveTenant(a.scope, "webauthn_policy.compliance_report")
	if err != nil {
		return managementCall{}, err
	}
	return managementCall{
		operation:    "webauthn_policy.compliance_report",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/tenants/{tenant_id}/webauthn/compliance-report",
		path:         fmt.Sprintf("/api/v1/tenants/%s/webauthn/compliance-report", tenantID.String()),
	}, nil
}

// ComplianceReport issues GET /api/v1/tenants/{tenant_id}/webauthn/compliance-report.
func (a *WebauthnPolicyAPI) ComplianceReport(ctx context.Context) ([]ComplianceReportEntry, error) {
	call, err := a.callWebauthnPolicyComplianceReport()
	if err != nil {
		var zero []ComplianceReportEntry
		return zero, err
	}
	return sendManagement[[]ComplianceReportEntry](ctx, a.c, call)
}
