// Code generated by internal/cmd/genmanagement. DO NOT EDIT.
//
// Generated from management-registry.json and openapi.json. Regenerate with
// `go run ./internal/cmd/genmanagement`; CI verifies the committed output
// is current.

// The oauth2_clients management namespace (CONTRACT §27.1).
//
// Registered OAuth2/OIDC clients -- the registration half of what §12,
// §21 and §26 then speak to.

package axiam

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/google/uuid"
)

// OAuth2ClientsAPI is the oauth2_clients namespace handle.
//
// Registered OAuth2/OIDC clients -- the registration half of what §12,
// §21 and §26 then speak to.
//
// Acquiring one performs no I/O and allocates nothing meaningful (§27.2
// rule 1); it holds the client and cannot be constructed without one.
type OAuth2ClientsAPI struct {
	c     *Client
	scope namespaceScope
}

// callOAuth2ClientsList builds the oauth2_clients.list call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *OAuth2ClientsAPI) callOAuth2ClientsList(page PageRequest) managementCall {
	query := url.Values{}
	query = pageQuery(page, query)
	return managementCall{
		operation:    "oauth2_clients.list",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/oauth2-clients",
		path:         "/api/v1/oauth2-clients",
		query:        query,
	}
}

// List issues GET /api/v1/oauth2-clients.
func (a *OAuth2ClientsAPI) List(ctx context.Context, page PageRequest) (Page[OAuth2ClientResponse], error) {
	call := a.callOAuth2ClientsList(page)
	return sendManagement[Page[OAuth2ClientResponse]](ctx, a.c, call)
}

// ListAll walks oauth2_clients.list to exhaustion, concatenating every page.
//
// The auto-paging form §27.4 rule 4 requires. It stops on an empty page
// even if Total disagrees, so a misreporting server costs one wasted
// request rather than an unbounded loop.
func (a *OAuth2ClientsAPI) ListAll(ctx context.Context, start PageRequest) ([]OAuth2ClientResponse, error) {
	return collectPages(ctx, start, func(ctx context.Context, p PageRequest) (Page[OAuth2ClientResponse], error) {
		return a.List(ctx, p)
	})
}

// callOAuth2ClientsCreate builds the oauth2_clients.create call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *OAuth2ClientsAPI) callOAuth2ClientsCreate(body CreateOAuth2ClientRequest) managementCall {
	return managementCall{
		operation:    "oauth2_clients.create",
		method:       http.MethodPost,
		pathTemplate: "/api/v1/oauth2-clients",
		path:         "/api/v1/oauth2-clients",
		body:         body,
	}
}

// Create issues POST /api/v1/oauth2-clients.
//
// Returns secret material, once. client_secret is returned by this call
// and by no other; no later Get will return it again, and the Get
// projection has no field where it was. Discarding the result destroys the
// credential (§27.5 rule 3).
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *OAuth2ClientsAPI) Create(ctx context.Context, body CreateOAuth2ClientRequest) (OAuth2ClientCreatedResponse, error) {
	call := a.callOAuth2ClientsCreate(body)
	return sendManagement[OAuth2ClientCreatedResponse](ctx, a.c, call)
}

// callOAuth2ClientsGet builds the oauth2_clients.get call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *OAuth2ClientsAPI) callOAuth2ClientsGet(id uuid.UUID) managementCall {
	return managementCall{
		operation:    "oauth2_clients.get",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/oauth2-clients/{id}",
		path:         fmt.Sprintf("/api/v1/oauth2-clients/%s", id.String()),
	}
}

// Get issues GET /api/v1/oauth2-clients/{id}.
func (a *OAuth2ClientsAPI) Get(ctx context.Context, id uuid.UUID) (OAuth2ClientResponse, error) {
	call := a.callOAuth2ClientsGet(id)
	return sendManagement[OAuth2ClientResponse](ctx, a.c, call)
}

// callOAuth2ClientsUpdate builds the oauth2_clients.update call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *OAuth2ClientsAPI) callOAuth2ClientsUpdate(id uuid.UUID, body UpdateOAuth2ClientRequest) managementCall {
	return managementCall{
		operation:    "oauth2_clients.update",
		method:       http.MethodPut,
		pathTemplate: "/api/v1/oauth2-clients/{id}",
		path:         fmt.Sprintf("/api/v1/oauth2-clients/%s", id.String()),
		body:         body,
	}
}

// Update issues PUT /api/v1/oauth2-clients/{id}.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *OAuth2ClientsAPI) Update(ctx context.Context, id uuid.UUID, body UpdateOAuth2ClientRequest) (OAuth2ClientResponse, error) {
	call := a.callOAuth2ClientsUpdate(id, body)
	return sendManagement[OAuth2ClientResponse](ctx, a.c, call)
}

// callOAuth2ClientsDelete builds the oauth2_clients.delete call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *OAuth2ClientsAPI) callOAuth2ClientsDelete(id uuid.UUID) managementCall {
	return managementCall{
		operation:    "oauth2_clients.delete",
		method:       http.MethodDelete,
		pathTemplate: "/api/v1/oauth2-clients/{id}",
		path:         fmt.Sprintf("/api/v1/oauth2-clients/%s", id.String()),
	}
}

// Delete issues DELETE /api/v1/oauth2-clients/{id}.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *OAuth2ClientsAPI) Delete(ctx context.Context, id uuid.UUID) error {
	call := a.callOAuth2ClientsDelete(id)
	return sendManagementNoContent(ctx, a.c, call)
}
