// Code generated by internal/cmd/genmanagement. DO NOT EDIT.
//
// Generated from management-registry.json and openapi.json. Regenerate with
// `go run ./internal/cmd/genmanagement`; CI verifies the committed output
// is current.

// The service_accounts management namespace (CONTRACT §27.1).
//
// Machine identities, their secrets, and the certificate a device-bound
// one authenticates with.

package axiam

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/google/uuid"
)

// ServiceAccountsAPI is the service_accounts namespace handle.
//
// Machine identities, their secrets, and the certificate a device-bound
// one authenticates with.
//
// Acquiring one performs no I/O and allocates nothing meaningful (§27.2
// rule 1); it holds the client and cannot be constructed without one.
type ServiceAccountsAPI struct {
	c     *Client
	scope namespaceScope
}

// callServiceAccountsList builds the service_accounts.list call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *ServiceAccountsAPI) callServiceAccountsList(page PageRequest) managementCall {
	query := url.Values{}
	query = pageQuery(page, query)
	return managementCall{
		operation:    "service_accounts.list",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/service-accounts",
		path:         "/api/v1/service-accounts",
		query:        query,
	}
}

// List issues GET /api/v1/service-accounts.
func (a *ServiceAccountsAPI) List(ctx context.Context, page PageRequest) (Page[ServiceAccountResponse], error) {
	call := a.callServiceAccountsList(page)
	return sendManagement[Page[ServiceAccountResponse]](ctx, a.c, call)
}

// ListAll walks service_accounts.list to exhaustion, concatenating every page.
//
// The auto-paging form §27.4 rule 4 requires. It stops on an empty page
// even if Total disagrees, so a misreporting server costs one wasted
// request rather than an unbounded loop.
func (a *ServiceAccountsAPI) ListAll(ctx context.Context, start PageRequest) ([]ServiceAccountResponse, error) {
	return collectPages(ctx, start, func(ctx context.Context, p PageRequest) (Page[ServiceAccountResponse], error) {
		return a.List(ctx, p)
	})
}

// callServiceAccountsCreate builds the service_accounts.create call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *ServiceAccountsAPI) callServiceAccountsCreate(body CreateServiceAccountRequest) managementCall {
	return managementCall{
		operation:    "service_accounts.create",
		method:       http.MethodPost,
		pathTemplate: "/api/v1/service-accounts",
		path:         "/api/v1/service-accounts",
		body:         body,
	}
}

// Create issues POST /api/v1/service-accounts.
//
// Returns secret material, once. client_secret is returned by this call
// and by no other; no later Get will return it again, and the Get
// projection has no field where it was. Discarding the result destroys the
// credential (§27.5 rule 3).
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *ServiceAccountsAPI) Create(ctx context.Context, body CreateServiceAccountRequest) (ServiceAccountCreatedResponse, error) {
	call := a.callServiceAccountsCreate(body)
	return sendManagement[ServiceAccountCreatedResponse](ctx, a.c, call)
}

// callServiceAccountsGet builds the service_accounts.get call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *ServiceAccountsAPI) callServiceAccountsGet(saID uuid.UUID) managementCall {
	return managementCall{
		operation:    "service_accounts.get",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/service-accounts/{sa_id}",
		path:         fmt.Sprintf("/api/v1/service-accounts/%s", saID.String()),
	}
}

// Get issues GET /api/v1/service-accounts/{sa_id}.
func (a *ServiceAccountsAPI) Get(ctx context.Context, saID uuid.UUID) (ServiceAccountResponse, error) {
	call := a.callServiceAccountsGet(saID)
	return sendManagement[ServiceAccountResponse](ctx, a.c, call)
}

// callServiceAccountsUpdate builds the service_accounts.update call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *ServiceAccountsAPI) callServiceAccountsUpdate(saID uuid.UUID, body UpdateServiceAccount) managementCall {
	return managementCall{
		operation:    "service_accounts.update",
		method:       http.MethodPut,
		pathTemplate: "/api/v1/service-accounts/{sa_id}",
		path:         fmt.Sprintf("/api/v1/service-accounts/%s", saID.String()),
		body:         body,
	}
}

// Update issues PUT /api/v1/service-accounts/{sa_id}.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *ServiceAccountsAPI) Update(ctx context.Context, saID uuid.UUID, body UpdateServiceAccount) (ServiceAccountResponse, error) {
	call := a.callServiceAccountsUpdate(saID, body)
	return sendManagement[ServiceAccountResponse](ctx, a.c, call)
}

// callServiceAccountsDelete builds the service_accounts.delete call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *ServiceAccountsAPI) callServiceAccountsDelete(saID uuid.UUID) managementCall {
	return managementCall{
		operation:    "service_accounts.delete",
		method:       http.MethodDelete,
		pathTemplate: "/api/v1/service-accounts/{sa_id}",
		path:         fmt.Sprintf("/api/v1/service-accounts/%s", saID.String()),
	}
}

// Delete issues DELETE /api/v1/service-accounts/{sa_id}.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *ServiceAccountsAPI) Delete(ctx context.Context, saID uuid.UUID) error {
	call := a.callServiceAccountsDelete(saID)
	return sendManagementNoContent(ctx, a.c, call)
}

// callServiceAccountsRotateSecret builds the service_accounts.rotate_secret call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *ServiceAccountsAPI) callServiceAccountsRotateSecret(saID uuid.UUID) managementCall {
	return managementCall{
		operation:    "service_accounts.rotate_secret",
		method:       http.MethodPost,
		pathTemplate: "/api/v1/service-accounts/{sa_id}/rotate-secret",
		path:         fmt.Sprintf("/api/v1/service-accounts/%s/rotate-secret", saID.String()),
	}
}

// RotateSecret issues POST /api/v1/service-accounts/{sa_id}/rotate-secret.
//
// Returns secret material, once. client_secret is returned by this call
// and by no other; no later Get will return it again, and the Get
// projection has no field where it was. Discarding the result destroys the
// credential (§27.5 rule 3).
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *ServiceAccountsAPI) RotateSecret(ctx context.Context, saID uuid.UUID) (RotateSecretResponse, error) {
	call := a.callServiceAccountsRotateSecret(saID)
	return sendManagement[RotateSecretResponse](ctx, a.c, call)
}

// callServiceAccountsBindCertificate builds the service_accounts.bind_certificate call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *ServiceAccountsAPI) callServiceAccountsBindCertificate(saID uuid.UUID, body BindCertificate) managementCall {
	return managementCall{
		operation:    "service_accounts.bind_certificate",
		method:       http.MethodPost,
		pathTemplate: "/api/v1/service-accounts/{sa_id}/bind-certificate",
		path:         fmt.Sprintf("/api/v1/service-accounts/%s/bind-certificate", saID.String()),
		body:         body,
	}
}

// BindCertificate issues POST /api/v1/service-accounts/{sa_id}/bind-certificate.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *ServiceAccountsAPI) BindCertificate(ctx context.Context, saID uuid.UUID, body BindCertificate) error {
	call := a.callServiceAccountsBindCertificate(saID, body)
	return sendManagementNoContent(ctx, a.c, call)
}

// callServiceAccountsListRoles builds the service_accounts.list_roles call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *ServiceAccountsAPI) callServiceAccountsListRoles(serviceAccountID uuid.UUID) managementCall {
	return managementCall{
		operation:    "service_accounts.list_roles",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/service-accounts/{service_account_id}/roles",
		path:         fmt.Sprintf("/api/v1/service-accounts/%s/roles", serviceAccountID.String()),
	}
}

// ListRoles issues GET /api/v1/service-accounts/{service_account_id}/roles.
func (a *ServiceAccountsAPI) ListRoles(ctx context.Context, serviceAccountID uuid.UUID) ([]RoleAssignment, error) {
	call := a.callServiceAccountsListRoles(serviceAccountID)
	return sendManagement[[]RoleAssignment](ctx, a.c, call)
}

// callServiceAccountsListGroups builds the service_accounts.list_groups call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *ServiceAccountsAPI) callServiceAccountsListGroups(serviceAccountID uuid.UUID) managementCall {
	return managementCall{
		operation:    "service_accounts.list_groups",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/service-accounts/{service_account_id}/groups",
		path:         fmt.Sprintf("/api/v1/service-accounts/%s/groups", serviceAccountID.String()),
	}
}

// ListGroups issues GET /api/v1/service-accounts/{service_account_id}/groups.
func (a *ServiceAccountsAPI) ListGroups(ctx context.Context, serviceAccountID uuid.UUID) ([]Group, error) {
	call := a.callServiceAccountsListGroups(serviceAccountID)
	return sendManagement[[]Group](ctx, a.c, call)
}
