// Code generated by internal/cmd/genmanagement. DO NOT EDIT.
//
// Generated from management-registry.json and openapi.json. Regenerate with
// `go run ./internal/cmd/genmanagement`; CI verifies the committed output
// is current.

// The roles management namespace (CONTRACT §27.1).
//
// Roles, their permission sets, and their assignment to users and groups.

package axiam

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/google/uuid"
)

// RolesAPI is the roles namespace handle.
//
// Roles, their permission sets, and their assignment to users and groups.
//
// Acquiring one performs no I/O and allocates nothing meaningful (§27.2
// rule 1); it holds the client and cannot be constructed without one.
type RolesAPI struct {
	c     *Client
	scope namespaceScope
}

// callRolesList builds the roles.list call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *RolesAPI) callRolesList(page PageRequest) managementCall {
	query := url.Values{}
	query = pageQuery(page, query)
	return managementCall{
		operation:    "roles.list",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/roles",
		path:         "/api/v1/roles",
		query:        query,
	}
}

// List issues GET /api/v1/roles.
func (a *RolesAPI) List(ctx context.Context, page PageRequest) (Page[Role], error) {
	call := a.callRolesList(page)
	return sendManagement[Page[Role]](ctx, a.c, call)
}

// ListAll walks roles.list to exhaustion, concatenating every page.
//
// The auto-paging form §27.4 rule 4 requires. It stops on an empty page
// even if Total disagrees, so a misreporting server costs one wasted
// request rather than an unbounded loop.
func (a *RolesAPI) ListAll(ctx context.Context, start PageRequest) ([]Role, error) {
	return collectPages(ctx, start, func(ctx context.Context, p PageRequest) (Page[Role], error) {
		return a.List(ctx, p)
	})
}

// callRolesCreate builds the roles.create call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *RolesAPI) callRolesCreate(body CreateRoleRequest) managementCall {
	return managementCall{
		operation:    "roles.create",
		method:       http.MethodPost,
		pathTemplate: "/api/v1/roles",
		path:         "/api/v1/roles",
		body:         body,
	}
}

// Create issues POST /api/v1/roles.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *RolesAPI) Create(ctx context.Context, body CreateRoleRequest) (Role, error) {
	call := a.callRolesCreate(body)
	return sendManagement[Role](ctx, a.c, call)
}

// callRolesGet builds the roles.get call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *RolesAPI) callRolesGet(roleID uuid.UUID) managementCall {
	return managementCall{
		operation:    "roles.get",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/roles/{role_id}",
		path:         fmt.Sprintf("/api/v1/roles/%s", roleID.String()),
	}
}

// Get issues GET /api/v1/roles/{role_id}.
func (a *RolesAPI) Get(ctx context.Context, roleID uuid.UUID) (Role, error) {
	call := a.callRolesGet(roleID)
	return sendManagement[Role](ctx, a.c, call)
}

// callRolesUpdate builds the roles.update call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *RolesAPI) callRolesUpdate(roleID uuid.UUID, body UpdateRole) managementCall {
	return managementCall{
		operation:    "roles.update",
		method:       http.MethodPut,
		pathTemplate: "/api/v1/roles/{role_id}",
		path:         fmt.Sprintf("/api/v1/roles/%s", roleID.String()),
		body:         body,
	}
}

// Update issues PUT /api/v1/roles/{role_id}.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *RolesAPI) Update(ctx context.Context, roleID uuid.UUID, body UpdateRole) (Role, error) {
	call := a.callRolesUpdate(roleID, body)
	return sendManagement[Role](ctx, a.c, call)
}

// callRolesDelete builds the roles.delete call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *RolesAPI) callRolesDelete(roleID uuid.UUID) managementCall {
	return managementCall{
		operation:    "roles.delete",
		method:       http.MethodDelete,
		pathTemplate: "/api/v1/roles/{role_id}",
		path:         fmt.Sprintf("/api/v1/roles/%s", roleID.String()),
	}
}

// Delete issues DELETE /api/v1/roles/{role_id}.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *RolesAPI) Delete(ctx context.Context, roleID uuid.UUID) error {
	call := a.callRolesDelete(roleID)
	return sendManagementNoContent(ctx, a.c, call)
}

// callRolesListUsers builds the roles.list_users call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *RolesAPI) callRolesListUsers(roleID uuid.UUID) managementCall {
	return managementCall{
		operation:    "roles.list_users",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/roles/{role_id}/users",
		path:         fmt.Sprintf("/api/v1/roles/%s/users", roleID.String()),
	}
}

// ListUsers issues GET /api/v1/roles/{role_id}/users.
func (a *RolesAPI) ListUsers(ctx context.Context, roleID uuid.UUID) ([]RoleUserAssignment, error) {
	call := a.callRolesListUsers(roleID)
	return sendManagement[[]RoleUserAssignment](ctx, a.c, call)
}

// callRolesAssignToUser builds the roles.assign_to_user call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *RolesAPI) callRolesAssignToUser(roleID uuid.UUID, body AssignRoleToUserRequest) managementCall {
	return managementCall{
		operation:    "roles.assign_to_user",
		method:       http.MethodPost,
		pathTemplate: "/api/v1/roles/{role_id}/users",
		path:         fmt.Sprintf("/api/v1/roles/%s/users", roleID.String()),
		body:         body,
	}
}

// AssignToUser issues POST /api/v1/roles/{role_id}/users.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *RolesAPI) AssignToUser(ctx context.Context, roleID uuid.UUID, body AssignRoleToUserRequest) error {
	call := a.callRolesAssignToUser(roleID, body)
	return sendManagementNoContent(ctx, a.c, call)
}

// callRolesUnassignFromUser builds the roles.unassign_from_user call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *RolesAPI) callRolesUnassignFromUser(roleID uuid.UUID, userID uuid.UUID, resourceID string) managementCall {
	query := url.Values{}
	if resourceID != "" {
		query.Set("resource_id", resourceID)
	}
	return managementCall{
		operation:    "roles.unassign_from_user",
		method:       http.MethodDelete,
		pathTemplate: "/api/v1/roles/{role_id}/users/{user_id}",
		path:         fmt.Sprintf("/api/v1/roles/%s/users/%s", roleID.String(), userID.String()),
		query:        query,
	}
}

// UnassignFromUser issues DELETE /api/v1/roles/{role_id}/users/{user_id}.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *RolesAPI) UnassignFromUser(ctx context.Context, roleID uuid.UUID, userID uuid.UUID, resourceID string) error {
	call := a.callRolesUnassignFromUser(roleID, userID, resourceID)
	return sendManagementNoContent(ctx, a.c, call)
}

// callRolesListGroups builds the roles.list_groups call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *RolesAPI) callRolesListGroups(roleID uuid.UUID) managementCall {
	return managementCall{
		operation:    "roles.list_groups",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/roles/{role_id}/groups",
		path:         fmt.Sprintf("/api/v1/roles/%s/groups", roleID.String()),
	}
}

// ListGroups issues GET /api/v1/roles/{role_id}/groups.
func (a *RolesAPI) ListGroups(ctx context.Context, roleID uuid.UUID) ([]RoleGroupAssignment, error) {
	call := a.callRolesListGroups(roleID)
	return sendManagement[[]RoleGroupAssignment](ctx, a.c, call)
}

// callRolesAssignToGroup builds the roles.assign_to_group call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *RolesAPI) callRolesAssignToGroup(roleID uuid.UUID, body AssignRoleToGroupRequest) managementCall {
	return managementCall{
		operation:    "roles.assign_to_group",
		method:       http.MethodPost,
		pathTemplate: "/api/v1/roles/{role_id}/groups",
		path:         fmt.Sprintf("/api/v1/roles/%s/groups", roleID.String()),
		body:         body,
	}
}

// AssignToGroup issues POST /api/v1/roles/{role_id}/groups.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *RolesAPI) AssignToGroup(ctx context.Context, roleID uuid.UUID, body AssignRoleToGroupRequest) error {
	call := a.callRolesAssignToGroup(roleID, body)
	return sendManagementNoContent(ctx, a.c, call)
}

// callRolesUnassignFromGroup builds the roles.unassign_from_group call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *RolesAPI) callRolesUnassignFromGroup(roleID uuid.UUID, groupID uuid.UUID, resourceID string) managementCall {
	query := url.Values{}
	if resourceID != "" {
		query.Set("resource_id", resourceID)
	}
	return managementCall{
		operation:    "roles.unassign_from_group",
		method:       http.MethodDelete,
		pathTemplate: "/api/v1/roles/{role_id}/groups/{group_id}",
		path:         fmt.Sprintf("/api/v1/roles/%s/groups/%s", roleID.String(), groupID.String()),
		query:        query,
	}
}

// UnassignFromGroup issues DELETE /api/v1/roles/{role_id}/groups/{group_id}.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *RolesAPI) UnassignFromGroup(ctx context.Context, roleID uuid.UUID, groupID uuid.UUID, resourceID string) error {
	call := a.callRolesUnassignFromGroup(roleID, groupID, resourceID)
	return sendManagementNoContent(ctx, a.c, call)
}

// callRolesListPermissions builds the roles.list_permissions call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *RolesAPI) callRolesListPermissions(roleID uuid.UUID) managementCall {
	return managementCall{
		operation:    "roles.list_permissions",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/roles/{role_id}/permissions",
		path:         fmt.Sprintf("/api/v1/roles/%s/permissions", roleID.String()),
	}
}

// ListPermissions issues GET /api/v1/roles/{role_id}/permissions.
func (a *RolesAPI) ListPermissions(ctx context.Context, roleID uuid.UUID) ([]ResolvedPermissionGrant, error) {
	call := a.callRolesListPermissions(roleID)
	return sendManagement[[]ResolvedPermissionGrant](ctx, a.c, call)
}

// callRolesGrantPermission builds the roles.grant_permission call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *RolesAPI) callRolesGrantPermission(roleID uuid.UUID, body GrantPermissionRequest) managementCall {
	return managementCall{
		operation:    "roles.grant_permission",
		method:       http.MethodPost,
		pathTemplate: "/api/v1/roles/{role_id}/permissions",
		path:         fmt.Sprintf("/api/v1/roles/%s/permissions", roleID.String()),
		body:         body,
	}
}

// GrantPermission issues POST /api/v1/roles/{role_id}/permissions.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *RolesAPI) GrantPermission(ctx context.Context, roleID uuid.UUID, body GrantPermissionRequest) error {
	call := a.callRolesGrantPermission(roleID, body)
	return sendManagementNoContent(ctx, a.c, call)
}

// callRolesRevokePermission builds the roles.revoke_permission call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *RolesAPI) callRolesRevokePermission(roleID uuid.UUID, permissionID uuid.UUID) managementCall {
	return managementCall{
		operation:    "roles.revoke_permission",
		method:       http.MethodDelete,
		pathTemplate: "/api/v1/roles/{role_id}/permissions/{permission_id}",
		path:         fmt.Sprintf("/api/v1/roles/%s/permissions/%s", roleID.String(), permissionID.String()),
	}
}

// RevokePermission issues DELETE /api/v1/roles/{role_id}/permissions/{permission_id}.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *RolesAPI) RevokePermission(ctx context.Context, roleID uuid.UUID, permissionID uuid.UUID) error {
	call := a.callRolesRevokePermission(roleID, permissionID)
	return sendManagementNoContent(ctx, a.c, call)
}
