// Code generated by internal/cmd/genmanagement. DO NOT EDIT.
//
// Generated from management-registry.json and openapi.json. Regenerate with
// `go run ./internal/cmd/genmanagement`; CI verifies the committed output
// is current.

// The audit management namespace (CONTRACT §27.1).
//
// Append-only audit log, read-only by construction.

package axiam

import (
	"context"
	"net/http"
	"net/url"
)

// AuditListFilter holds the optional filters for audit.list.
//
// Six loose optional string arguments is a call site a reader cannot check
// and a refactor silently reorders, so they travel as one struct. A zero
// field is not sent.
type AuditListFilter struct {
	// ActorID filters on actor_id. Empty means unset.
	ActorID string
	// Action filters on action. Empty means unset.
	Action string
	// Outcome filters on outcome. Empty means unset.
	Outcome string
	// ResourceID filters on resource_id. Empty means unset.
	ResourceID string
	// From filters on from. Empty means unset.
	From string
	// To filters on to. Empty means unset.
	To string
}

// AuditListSystemFilter holds the optional filters for audit.list_system.
//
// Six loose optional string arguments is a call site a reader cannot check
// and a refactor silently reorders, so they travel as one struct. A zero
// field is not sent.
type AuditListSystemFilter struct {
	// ActorID filters on actor_id. Empty means unset.
	ActorID string
	// Action filters on action. Empty means unset.
	Action string
	// Outcome filters on outcome. Empty means unset.
	Outcome string
	// ResourceID filters on resource_id. Empty means unset.
	ResourceID string
	// From filters on from. Empty means unset.
	From string
	// To filters on to. Empty means unset.
	To string
}

// AuditAPI is the audit namespace handle.
//
// Append-only audit log, read-only by construction.
//
// Acquiring one performs no I/O and allocates nothing meaningful (§27.2
// rule 1); it holds the client and cannot be constructed without one.
type AuditAPI struct {
	c     *Client
	scope namespaceScope
}

// callAuditList builds the audit.list call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *AuditAPI) callAuditList(filter AuditListFilter, page PageRequest) managementCall {
	query := url.Values{}
	if filter.ActorID != "" {
		query.Set("actor_id", filter.ActorID)
	}
	if filter.Action != "" {
		query.Set("action", filter.Action)
	}
	if filter.Outcome != "" {
		query.Set("outcome", filter.Outcome)
	}
	if filter.ResourceID != "" {
		query.Set("resource_id", filter.ResourceID)
	}
	if filter.From != "" {
		query.Set("from", filter.From)
	}
	if filter.To != "" {
		query.Set("to", filter.To)
	}
	query = pageQuery(page, query)
	return managementCall{
		operation:    "audit.list",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/audit-logs",
		path:         "/api/v1/audit-logs",
		query:        query,
	}
}

// List issues GET /api/v1/audit-logs.
func (a *AuditAPI) List(ctx context.Context, filter AuditListFilter, page PageRequest) (Page[AuditLogEntry], error) {
	call := a.callAuditList(filter, page)
	return sendManagement[Page[AuditLogEntry]](ctx, a.c, call)
}

// ListAll walks audit.list to exhaustion, concatenating every page.
//
// The auto-paging form §27.4 rule 4 requires. It stops on an empty page
// even if Total disagrees, so a misreporting server costs one wasted
// request rather than an unbounded loop.
func (a *AuditAPI) ListAll(ctx context.Context, filter AuditListFilter, start PageRequest) ([]AuditLogEntry, error) {
	return collectPages(ctx, start, func(ctx context.Context, p PageRequest) (Page[AuditLogEntry], error) {
		return a.List(ctx, filter, p)
	})
}

// callAuditListSystem builds the audit.list_system call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *AuditAPI) callAuditListSystem(filter AuditListSystemFilter, page PageRequest) managementCall {
	query := url.Values{}
	if filter.ActorID != "" {
		query.Set("actor_id", filter.ActorID)
	}
	if filter.Action != "" {
		query.Set("action", filter.Action)
	}
	if filter.Outcome != "" {
		query.Set("outcome", filter.Outcome)
	}
	if filter.ResourceID != "" {
		query.Set("resource_id", filter.ResourceID)
	}
	if filter.From != "" {
		query.Set("from", filter.From)
	}
	if filter.To != "" {
		query.Set("to", filter.To)
	}
	query = pageQuery(page, query)
	return managementCall{
		operation:    "audit.list_system",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/audit-logs/system",
		path:         "/api/v1/audit-logs/system",
		query:        query,
	}
}

// ListSystem issues GET /api/v1/audit-logs/system.
func (a *AuditAPI) ListSystem(ctx context.Context, filter AuditListSystemFilter, page PageRequest) (Page[AuditLogEntry], error) {
	call := a.callAuditListSystem(filter, page)
	return sendManagement[Page[AuditLogEntry]](ctx, a.c, call)
}

// ListSystemAll walks audit.list_system to exhaustion, concatenating every page.
//
// The auto-paging form §27.4 rule 4 requires. It stops on an empty page
// even if Total disagrees, so a misreporting server costs one wasted
// request rather than an unbounded loop.
func (a *AuditAPI) ListSystemAll(ctx context.Context, filter AuditListSystemFilter, start PageRequest) ([]AuditLogEntry, error) {
	return collectPages(ctx, start, func(ctx context.Context, p PageRequest) (Page[AuditLogEntry], error) {
		return a.ListSystem(ctx, filter, p)
	})
}
