// Code generated by internal/cmd/genmanagement. DO NOT EDIT.
//
// Generated from management-registry.json and openapi.json. Regenerate with
// `go run ./internal/cmd/genmanagement`; CI verifies the committed output
// is current.

// The notification_rules management namespace (CONTRACT §27.1).
//
// Which events raise a notification, and to whom.

package axiam

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/google/uuid"
)

// NotificationRulesAPI is the notification_rules namespace handle.
//
// Which events raise a notification, and to whom.
//
// Acquiring one performs no I/O and allocates nothing meaningful (§27.2
// rule 1); it holds the client and cannot be constructed without one.
type NotificationRulesAPI struct {
	c     *Client
	scope namespaceScope
}

// callNotificationRulesList builds the notification_rules.list call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *NotificationRulesAPI) callNotificationRulesList(page PageRequest) managementCall {
	query := url.Values{}
	query = pageQuery(page, query)
	return managementCall{
		operation:    "notification_rules.list",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/notification-rules",
		path:         "/api/v1/notification-rules",
		query:        query,
	}
}

// List issues GET /api/v1/notification-rules.
func (a *NotificationRulesAPI) List(ctx context.Context, page PageRequest) (Page[NotificationRuleResponse], error) {
	call := a.callNotificationRulesList(page)
	return sendManagement[Page[NotificationRuleResponse]](ctx, a.c, call)
}

// ListAll walks notification_rules.list to exhaustion, concatenating every page.
//
// The auto-paging form §27.4 rule 4 requires. It stops on an empty page
// even if Total disagrees, so a misreporting server costs one wasted
// request rather than an unbounded loop.
func (a *NotificationRulesAPI) ListAll(ctx context.Context, start PageRequest) ([]NotificationRuleResponse, error) {
	return collectPages(ctx, start, func(ctx context.Context, p PageRequest) (Page[NotificationRuleResponse], error) {
		return a.List(ctx, p)
	})
}

// callNotificationRulesCreate builds the notification_rules.create call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *NotificationRulesAPI) callNotificationRulesCreate(body CreateNotificationRuleRequest) managementCall {
	return managementCall{
		operation:    "notification_rules.create",
		method:       http.MethodPost,
		pathTemplate: "/api/v1/notification-rules",
		path:         "/api/v1/notification-rules",
		body:         body,
	}
}

// Create issues POST /api/v1/notification-rules.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *NotificationRulesAPI) Create(ctx context.Context, body CreateNotificationRuleRequest) (NotificationRuleResponse, error) {
	call := a.callNotificationRulesCreate(body)
	return sendManagement[NotificationRuleResponse](ctx, a.c, call)
}

// callNotificationRulesGet builds the notification_rules.get call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *NotificationRulesAPI) callNotificationRulesGet(id uuid.UUID) managementCall {
	return managementCall{
		operation:    "notification_rules.get",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/notification-rules/{id}",
		path:         fmt.Sprintf("/api/v1/notification-rules/%s", id.String()),
	}
}

// Get issues GET /api/v1/notification-rules/{id}.
func (a *NotificationRulesAPI) Get(ctx context.Context, id uuid.UUID) (NotificationRuleResponse, error) {
	call := a.callNotificationRulesGet(id)
	return sendManagement[NotificationRuleResponse](ctx, a.c, call)
}

// callNotificationRulesUpdate builds the notification_rules.update call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *NotificationRulesAPI) callNotificationRulesUpdate(id uuid.UUID, body UpdateNotificationRuleRequest) managementCall {
	return managementCall{
		operation:    "notification_rules.update",
		method:       http.MethodPut,
		pathTemplate: "/api/v1/notification-rules/{id}",
		path:         fmt.Sprintf("/api/v1/notification-rules/%s", id.String()),
		body:         body,
	}
}

// Update issues PUT /api/v1/notification-rules/{id}.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *NotificationRulesAPI) Update(ctx context.Context, id uuid.UUID, body UpdateNotificationRuleRequest) (NotificationRuleResponse, error) {
	call := a.callNotificationRulesUpdate(id, body)
	return sendManagement[NotificationRuleResponse](ctx, a.c, call)
}

// callNotificationRulesDelete builds the notification_rules.delete call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *NotificationRulesAPI) callNotificationRulesDelete(id uuid.UUID) managementCall {
	return managementCall{
		operation:    "notification_rules.delete",
		method:       http.MethodDelete,
		pathTemplate: "/api/v1/notification-rules/{id}",
		path:         fmt.Sprintf("/api/v1/notification-rules/%s", id.String()),
	}
}

// Delete issues DELETE /api/v1/notification-rules/{id}.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *NotificationRulesAPI) Delete(ctx context.Context, id uuid.UUID) error {
	call := a.callNotificationRulesDelete(id)
	return sendManagementNoContent(ctx, a.c, call)
}
