// Code generated by internal/cmd/genmanagement. DO NOT EDIT.
//
// Generated from management-registry.json and openapi.json. Regenerate with
// `go run ./internal/cmd/genmanagement`; CI verifies the committed output
// is current.

// The platform management namespace (CONTRACT §27.1).
//
// Deployment-level probes and FIDO metadata state. Unauthenticated where
// the server leaves them so.

package axiam

import (
	"context"
	"net/http"
)

// PlatformAPI is the platform namespace handle.
//
// Deployment-level probes and FIDO metadata state. Unauthenticated where
// the server leaves them so.
//
// Acquiring one performs no I/O and allocates nothing meaningful (§27.2
// rule 1); it holds the client and cannot be constructed without one.
type PlatformAPI struct {
	c     *Client
	scope namespaceScope
}

// callPlatformHealth builds the platform.health call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *PlatformAPI) callPlatformHealth() managementCall {
	return managementCall{
		operation:    "platform.health",
		method:       http.MethodGet,
		pathTemplate: "/health",
		path:         "/health",
	}
}

// Health issues GET /health.
func (a *PlatformAPI) Health(ctx context.Context) (HealthResponse, error) {
	call := a.callPlatformHealth()
	return sendManagement[HealthResponse](ctx, a.c, call)
}

// callPlatformReady builds the platform.ready call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *PlatformAPI) callPlatformReady() managementCall {
	return managementCall{
		operation:    "platform.ready",
		method:       http.MethodGet,
		pathTemplate: "/ready",
		path:         "/ready",
	}
}

// Ready issues GET /ready.
func (a *PlatformAPI) Ready(ctx context.Context) (ReadyResponse, error) {
	call := a.callPlatformReady()
	return sendManagement[ReadyResponse](ctx, a.c, call)
}

// callPlatformMDSStatus builds the platform.mds_status call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *PlatformAPI) callPlatformMDSStatus() managementCall {
	return managementCall{
		operation:    "platform.mds_status",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/mds/status",
		path:         "/api/v1/mds/status",
	}
}

// MDSStatus issues GET /api/v1/mds/status.
func (a *PlatformAPI) MDSStatus(ctx context.Context) (MDSStatusResponse, error) {
	call := a.callPlatformMDSStatus()
	return sendManagement[MDSStatusResponse](ctx, a.c, call)
}

// callPlatformMDSRefresh builds the platform.mds_refresh call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *PlatformAPI) callPlatformMDSRefresh() managementCall {
	return managementCall{
		operation:    "platform.mds_refresh",
		method:       http.MethodPost,
		pathTemplate: "/api/v1/mds/refresh",
		path:         "/api/v1/mds/refresh",
	}
}

// MDSRefresh issues POST /api/v1/mds/refresh.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *PlatformAPI) MDSRefresh(ctx context.Context) (MDSRefreshOutcome, error) {
	call := a.callPlatformMDSRefresh()
	return sendManagement[MDSRefreshOutcome](ctx, a.c, call)
}
