// Code generated by internal/cmd/genmanagement. DO NOT EDIT.
//
// Generated from management-registry.json and openapi.json. Regenerate with
// `go run ./internal/cmd/genmanagement`; CI verifies the committed output
// is current.

// The permissions management namespace (CONTRACT §27.1).
//
// Permissions -- an action on a resource, optionally narrowed by a scope.

package axiam

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/google/uuid"
)

// PermissionsAPI is the permissions namespace handle.
//
// Permissions -- an action on a resource, optionally narrowed by a scope.
//
// Acquiring one performs no I/O and allocates nothing meaningful (§27.2
// rule 1); it holds the client and cannot be constructed without one.
type PermissionsAPI struct {
	c     *Client
	scope namespaceScope
}

// callPermissionsList builds the permissions.list call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *PermissionsAPI) callPermissionsList(page PageRequest) managementCall {
	query := url.Values{}
	query = pageQuery(page, query)
	return managementCall{
		operation:    "permissions.list",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/permissions",
		path:         "/api/v1/permissions",
		query:        query,
	}
}

// List issues GET /api/v1/permissions.
func (a *PermissionsAPI) List(ctx context.Context, page PageRequest) (Page[Permission], error) {
	call := a.callPermissionsList(page)
	return sendManagement[Page[Permission]](ctx, a.c, call)
}

// ListAll walks permissions.list to exhaustion, concatenating every page.
//
// The auto-paging form §27.4 rule 4 requires. It stops on an empty page
// even if Total disagrees, so a misreporting server costs one wasted
// request rather than an unbounded loop.
func (a *PermissionsAPI) ListAll(ctx context.Context, start PageRequest) ([]Permission, error) {
	return collectPages(ctx, start, func(ctx context.Context, p PageRequest) (Page[Permission], error) {
		return a.List(ctx, p)
	})
}

// callPermissionsCreate builds the permissions.create call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *PermissionsAPI) callPermissionsCreate(body CreatePermissionRequest) managementCall {
	return managementCall{
		operation:    "permissions.create",
		method:       http.MethodPost,
		pathTemplate: "/api/v1/permissions",
		path:         "/api/v1/permissions",
		body:         body,
	}
}

// Create issues POST /api/v1/permissions.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *PermissionsAPI) Create(ctx context.Context, body CreatePermissionRequest) (Permission, error) {
	call := a.callPermissionsCreate(body)
	return sendManagement[Permission](ctx, a.c, call)
}

// callPermissionsGet builds the permissions.get call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *PermissionsAPI) callPermissionsGet(permissionID uuid.UUID) managementCall {
	return managementCall{
		operation:    "permissions.get",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/permissions/{permission_id}",
		path:         fmt.Sprintf("/api/v1/permissions/%s", permissionID.String()),
	}
}

// Get issues GET /api/v1/permissions/{permission_id}.
func (a *PermissionsAPI) Get(ctx context.Context, permissionID uuid.UUID) (Permission, error) {
	call := a.callPermissionsGet(permissionID)
	return sendManagement[Permission](ctx, a.c, call)
}

// callPermissionsUpdate builds the permissions.update call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *PermissionsAPI) callPermissionsUpdate(permissionID uuid.UUID, body UpdatePermissionRequest) managementCall {
	return managementCall{
		operation:    "permissions.update",
		method:       http.MethodPut,
		pathTemplate: "/api/v1/permissions/{permission_id}",
		path:         fmt.Sprintf("/api/v1/permissions/%s", permissionID.String()),
		body:         body,
	}
}

// Update issues PUT /api/v1/permissions/{permission_id}.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *PermissionsAPI) Update(ctx context.Context, permissionID uuid.UUID, body UpdatePermissionRequest) (Permission, error) {
	call := a.callPermissionsUpdate(permissionID, body)
	return sendManagement[Permission](ctx, a.c, call)
}

// callPermissionsDelete builds the permissions.delete call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *PermissionsAPI) callPermissionsDelete(permissionID uuid.UUID) managementCall {
	return managementCall{
		operation:    "permissions.delete",
		method:       http.MethodDelete,
		pathTemplate: "/api/v1/permissions/{permission_id}",
		path:         fmt.Sprintf("/api/v1/permissions/%s", permissionID.String()),
	}
}

// Delete issues DELETE /api/v1/permissions/{permission_id}.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *PermissionsAPI) Delete(ctx context.Context, permissionID uuid.UUID) error {
	call := a.callPermissionsDelete(permissionID)
	return sendManagementNoContent(ctx, a.c, call)
}
