// Code generated by internal/cmd/genmanagement. DO NOT EDIT.
//
// Generated from management-registry.json and openapi.json. Regenerate with
// `go run ./internal/cmd/genmanagement`; CI verifies the committed output
// is current.

// The scim_tokens management namespace (CONTRACT §27.1).
//
// Bearer tokens for the SCIM 2.0 provisioning endpoint.

package axiam

import (
	"context"
	"fmt"
	"net/http"

	"github.com/google/uuid"
)

// SCIMTokensAPI is the scim_tokens namespace handle.
//
// Bearer tokens for the SCIM 2.0 provisioning endpoint.
//
// Acquiring one performs no I/O and allocates nothing meaningful (§27.2
// rule 1); it holds the client and cannot be constructed without one.
type SCIMTokensAPI struct {
	c     *Client
	scope namespaceScope
}

// callSCIMTokensList builds the scim_tokens.list call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *SCIMTokensAPI) callSCIMTokensList() managementCall {
	return managementCall{
		operation:    "scim_tokens.list",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/scim-tokens",
		path:         "/api/v1/scim-tokens",
	}
}

// List issues GET /api/v1/scim-tokens.
func (a *SCIMTokensAPI) List(ctx context.Context) ([]SCIMTokenResponse, error) {
	call := a.callSCIMTokensList()
	return sendManagement[[]SCIMTokenResponse](ctx, a.c, call)
}

// callSCIMTokensCreate builds the scim_tokens.create call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *SCIMTokensAPI) callSCIMTokensCreate(body CreateSCIMTokenRequest) managementCall {
	return managementCall{
		operation:    "scim_tokens.create",
		method:       http.MethodPost,
		pathTemplate: "/api/v1/scim-tokens",
		path:         "/api/v1/scim-tokens",
		body:         body,
	}
}

// Create issues POST /api/v1/scim-tokens.
//
// Returns secret material, once. provisioning_token is returned by this
// call and by no other; no later Get will return it again, and the Get
// projection has no field where it was. Discarding the result destroys the
// credential (§27.5 rule 3).
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *SCIMTokensAPI) Create(ctx context.Context, body CreateSCIMTokenRequest) (CreateSCIMTokenResponse, error) {
	call := a.callSCIMTokensCreate(body)
	return sendManagement[CreateSCIMTokenResponse](ctx, a.c, call)
}

// callSCIMTokensRevoke builds the scim_tokens.revoke call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *SCIMTokensAPI) callSCIMTokensRevoke(id uuid.UUID) managementCall {
	return managementCall{
		operation:    "scim_tokens.revoke",
		method:       http.MethodDelete,
		pathTemplate: "/api/v1/scim-tokens/{id}",
		path:         fmt.Sprintf("/api/v1/scim-tokens/%s", id.String()),
	}
}

// Revoke issues DELETE /api/v1/scim-tokens/{id}.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *SCIMTokensAPI) Revoke(ctx context.Context, id uuid.UUID) error {
	call := a.callSCIMTokensRevoke(id)
	return sendManagementNoContent(ctx, a.c, call)
}
