// Code generated by internal/cmd/genmanagement. DO NOT EDIT.
//
// Generated from management-registry.json and openapi.json. Regenerate with
// `go run ./internal/cmd/genmanagement`; CI verifies the committed output
// is current.

// The reactors management namespace (CONTRACT §27.1).
//
// Registration of §22 AMQP extension actors -- the admin surface §22.9
// describes, which no SDK could previously reach.

package axiam

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/google/uuid"
)

// ReactorsAPI is the reactors namespace handle.
//
// Registration of §22 AMQP extension actors -- the admin surface §22.9
// describes, which no SDK could previously reach.
//
// Acquiring one performs no I/O and allocates nothing meaningful (§27.2
// rule 1); it holds the client and cannot be constructed without one.
type ReactorsAPI struct {
	c     *Client
	scope namespaceScope
}

// callReactorsList builds the reactors.list call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *ReactorsAPI) callReactorsList(page PageRequest) managementCall {
	query := url.Values{}
	query = pageQuery(page, query)
	return managementCall{
		operation:    "reactors.list",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/reactors",
		path:         "/api/v1/reactors",
		query:        query,
	}
}

// List issues GET /api/v1/reactors.
func (a *ReactorsAPI) List(ctx context.Context, page PageRequest) (Page[ReactorResponse], error) {
	call := a.callReactorsList(page)
	return sendManagement[Page[ReactorResponse]](ctx, a.c, call)
}

// ListAll walks reactors.list to exhaustion, concatenating every page.
//
// The auto-paging form §27.4 rule 4 requires. It stops on an empty page
// even if Total disagrees, so a misreporting server costs one wasted
// request rather than an unbounded loop.
func (a *ReactorsAPI) ListAll(ctx context.Context, start PageRequest) ([]ReactorResponse, error) {
	return collectPages(ctx, start, func(ctx context.Context, p PageRequest) (Page[ReactorResponse], error) {
		return a.List(ctx, p)
	})
}

// callReactorsCreate builds the reactors.create call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *ReactorsAPI) callReactorsCreate(body CreateReactorRequest) managementCall {
	return managementCall{
		operation:    "reactors.create",
		method:       http.MethodPost,
		pathTemplate: "/api/v1/reactors",
		path:         "/api/v1/reactors",
		body:         body,
	}
}

// Create issues POST /api/v1/reactors.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *ReactorsAPI) Create(ctx context.Context, body CreateReactorRequest) (ReactorResponse, error) {
	call := a.callReactorsCreate(body)
	return sendManagement[ReactorResponse](ctx, a.c, call)
}

// callReactorsGet builds the reactors.get call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *ReactorsAPI) callReactorsGet(id uuid.UUID) managementCall {
	return managementCall{
		operation:    "reactors.get",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/reactors/{id}",
		path:         fmt.Sprintf("/api/v1/reactors/%s", id.String()),
	}
}

// Get issues GET /api/v1/reactors/{id}.
func (a *ReactorsAPI) Get(ctx context.Context, id uuid.UUID) (ReactorResponse, error) {
	call := a.callReactorsGet(id)
	return sendManagement[ReactorResponse](ctx, a.c, call)
}

// callReactorsUpdate builds the reactors.update call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *ReactorsAPI) callReactorsUpdate(id uuid.UUID, body UpdateReactorRequest) managementCall {
	return managementCall{
		operation:    "reactors.update",
		method:       http.MethodPut,
		pathTemplate: "/api/v1/reactors/{id}",
		path:         fmt.Sprintf("/api/v1/reactors/%s", id.String()),
		body:         body,
	}
}

// Update issues PUT /api/v1/reactors/{id}.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *ReactorsAPI) Update(ctx context.Context, id uuid.UUID, body UpdateReactorRequest) (ReactorResponse, error) {
	call := a.callReactorsUpdate(id, body)
	return sendManagement[ReactorResponse](ctx, a.c, call)
}

// callReactorsDelete builds the reactors.delete call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *ReactorsAPI) callReactorsDelete(id uuid.UUID) managementCall {
	return managementCall{
		operation:    "reactors.delete",
		method:       http.MethodDelete,
		pathTemplate: "/api/v1/reactors/{id}",
		path:         fmt.Sprintf("/api/v1/reactors/%s", id.String()),
	}
}

// Delete issues DELETE /api/v1/reactors/{id}.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *ReactorsAPI) Delete(ctx context.Context, id uuid.UUID) error {
	call := a.callReactorsDelete(id)
	return sendManagementNoContent(ctx, a.c, call)
}

// callReactorsListEvents builds the reactors.list_events call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *ReactorsAPI) callReactorsListEvents() managementCall {
	return managementCall{
		operation:    "reactors.list_events",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/reactors/events",
		path:         "/api/v1/reactors/events",
	}
}

// ListEvents issues GET /api/v1/reactors/events.
func (a *ReactorsAPI) ListEvents(ctx context.Context) ([]ReactorEventDescriptor, error) {
	call := a.callReactorsListEvents()
	return sendManagement[[]ReactorEventDescriptor](ctx, a.c, call)
}
