// Code generated by internal/cmd/genmanagement. DO NOT EDIT.
//
// Generated from management-registry.json and openapi.json. Regenerate with
// `go run ./internal/cmd/genmanagement`; CI verifies the committed output
// is current.

// The pgp_keys management namespace (CONTRACT §27.1).
//
// OpenPGP keys used for audit signing and encrypted data export.

package axiam

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/google/uuid"
)

// PGPKeysAPI is the pgp_keys namespace handle.
//
// OpenPGP keys used for audit signing and encrypted data export.
//
// Acquiring one performs no I/O and allocates nothing meaningful (§27.2
// rule 1); it holds the client and cannot be constructed without one.
type PGPKeysAPI struct {
	c     *Client
	scope namespaceScope
}

// callPGPKeysList builds the pgp_keys.list call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *PGPKeysAPI) callPGPKeysList(page PageRequest) managementCall {
	query := url.Values{}
	query = pageQuery(page, query)
	return managementCall{
		operation:    "pgp_keys.list",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/pgp-keys",
		path:         "/api/v1/pgp-keys",
		query:        query,
	}
}

// List issues GET /api/v1/pgp-keys.
func (a *PGPKeysAPI) List(ctx context.Context, page PageRequest) (Page[PGPKey], error) {
	call := a.callPGPKeysList(page)
	return sendManagement[Page[PGPKey]](ctx, a.c, call)
}

// ListAll walks pgp_keys.list to exhaustion, concatenating every page.
//
// The auto-paging form §27.4 rule 4 requires. It stops on an empty page
// even if Total disagrees, so a misreporting server costs one wasted
// request rather than an unbounded loop.
func (a *PGPKeysAPI) ListAll(ctx context.Context, start PageRequest) ([]PGPKey, error) {
	return collectPages(ctx, start, func(ctx context.Context, p PageRequest) (Page[PGPKey], error) {
		return a.List(ctx, p)
	})
}

// callPGPKeysGenerate builds the pgp_keys.generate call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *PGPKeysAPI) callPGPKeysGenerate(body CreatePGPKeyRequest) managementCall {
	return managementCall{
		operation:    "pgp_keys.generate",
		method:       http.MethodPost,
		pathTemplate: "/api/v1/pgp-keys",
		path:         "/api/v1/pgp-keys",
		body:         body,
	}
}

// Generate issues POST /api/v1/pgp-keys.
//
// Returns secret material, once. private_key_armored is returned by this
// call and by no other; no later Get will return it again, and the Get
// projection has no field where it was. Discarding the result destroys the
// credential (§27.5 rule 3).
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *PGPKeysAPI) Generate(ctx context.Context, body CreatePGPKeyRequest) (GeneratedPGPKey, error) {
	call := a.callPGPKeysGenerate(body)
	return sendManagement[GeneratedPGPKey](ctx, a.c, call)
}

// callPGPKeysGet builds the pgp_keys.get call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *PGPKeysAPI) callPGPKeysGet(id uuid.UUID) managementCall {
	return managementCall{
		operation:    "pgp_keys.get",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/pgp-keys/{id}",
		path:         fmt.Sprintf("/api/v1/pgp-keys/%s", id.String()),
	}
}

// Get issues GET /api/v1/pgp-keys/{id}.
func (a *PGPKeysAPI) Get(ctx context.Context, id uuid.UUID) (PGPKey, error) {
	call := a.callPGPKeysGet(id)
	return sendManagement[PGPKey](ctx, a.c, call)
}

// callPGPKeysRevoke builds the pgp_keys.revoke call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *PGPKeysAPI) callPGPKeysRevoke(id uuid.UUID) managementCall {
	return managementCall{
		operation:    "pgp_keys.revoke",
		method:       http.MethodPost,
		pathTemplate: "/api/v1/pgp-keys/{id}/revoke",
		path:         fmt.Sprintf("/api/v1/pgp-keys/%s/revoke", id.String()),
	}
}

// Revoke issues POST /api/v1/pgp-keys/{id}/revoke.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *PGPKeysAPI) Revoke(ctx context.Context, id uuid.UUID) error {
	call := a.callPGPKeysRevoke(id)
	return sendManagementNoContent(ctx, a.c, call)
}

// callPGPKeysEncrypt builds the pgp_keys.encrypt call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *PGPKeysAPI) callPGPKeysEncrypt(id uuid.UUID, body EncryptRequest) managementCall {
	return managementCall{
		operation:    "pgp_keys.encrypt",
		method:       http.MethodPost,
		pathTemplate: "/api/v1/pgp-keys/{id}/encrypt",
		path:         fmt.Sprintf("/api/v1/pgp-keys/%s/encrypt", id.String()),
		body:         body,
	}
}

// Encrypt issues POST /api/v1/pgp-keys/{id}/encrypt.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *PGPKeysAPI) Encrypt(ctx context.Context, id uuid.UUID, body EncryptRequest) (EncryptedExport, error) {
	call := a.callPGPKeysEncrypt(id, body)
	return sendManagement[EncryptedExport](ctx, a.c, call)
}

// callPGPKeysSignAuditBatch builds the pgp_keys.sign_audit_batch call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *PGPKeysAPI) callPGPKeysSignAuditBatch(body SignAuditBatchRequest) managementCall {
	return managementCall{
		operation:    "pgp_keys.sign_audit_batch",
		method:       http.MethodPost,
		pathTemplate: "/api/v1/pgp-keys/sign-audit-batch",
		path:         "/api/v1/pgp-keys/sign-audit-batch",
		body:         body,
	}
}

// SignAuditBatch issues POST /api/v1/pgp-keys/sign-audit-batch.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *PGPKeysAPI) SignAuditBatch(ctx context.Context, body SignAuditBatchRequest) (SignedAuditBatch, error) {
	call := a.callPGPKeysSignAuditBatch(body)
	return sendManagement[SignedAuditBatch](ctx, a.c, call)
}
