// Code generated by internal/cmd/genmanagement. DO NOT EDIT.
//
// Generated from management-registry.json and openapi.json. Regenerate with
// `go run ./internal/cmd/genmanagement`; CI verifies the committed output
// is current.

// The privacy management namespace (CONTRACT §27.1).
//
// GDPR self-service: the authenticated account's own export and erasure.
// Scoped to the caller, never to another user.

package axiam

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// PrivacyAPI is the privacy namespace handle.
//
// GDPR self-service: the authenticated account's own export and erasure.
// Scoped to the caller, never to another user.
//
// Acquiring one performs no I/O and allocates nothing meaningful (§27.2
// rule 1); it holds the client and cannot be constructed without one.
type PrivacyAPI struct {
	c     *Client
	scope namespaceScope
}

// callPrivacyRequestExport builds the privacy.request_export call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *PrivacyAPI) callPrivacyRequestExport(body any) managementCall {
	return managementCall{
		operation:    "privacy.request_export",
		method:       http.MethodPost,
		pathTemplate: "/api/v1/account/export",
		path:         "/api/v1/account/export",
		body:         body,
	}
}

// RequestExport issues POST /api/v1/account/export.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *PrivacyAPI) RequestExport(ctx context.Context, body any) error {
	call := a.callPrivacyRequestExport(body)
	return sendManagementNoContent(ctx, a.c, call)
}

// callPrivacyDownloadExport builds the privacy.download_export call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *PrivacyAPI) callPrivacyDownloadExport(token string) managementCall {
	return managementCall{
		operation:    "privacy.download_export",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/account/export/{token}",
		path:         fmt.Sprintf("/api/v1/account/export/%s", url.PathEscape(token)),
	}
}

// DownloadExport issues GET /api/v1/account/export/{token}.
func (a *PrivacyAPI) DownloadExport(ctx context.Context, token string) error {
	call := a.callPrivacyDownloadExport(token)
	return sendManagementNoContent(ctx, a.c, call)
}

// callPrivacyRequestDelete builds the privacy.request_delete call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *PrivacyAPI) callPrivacyRequestDelete(body any) managementCall {
	return managementCall{
		operation:    "privacy.request_delete",
		method:       http.MethodPost,
		pathTemplate: "/api/v1/account/delete",
		path:         "/api/v1/account/delete",
		body:         body,
	}
}

// RequestDelete issues POST /api/v1/account/delete.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *PrivacyAPI) RequestDelete(ctx context.Context, body any) error {
	call := a.callPrivacyRequestDelete(body)
	return sendManagementNoContent(ctx, a.c, call)
}

// callPrivacyCancelDelete builds the privacy.cancel_delete call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *PrivacyAPI) callPrivacyCancelDelete(token string) managementCall {
	query := url.Values{}
	query.Set("token", token)
	return managementCall{
		operation:    "privacy.cancel_delete",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/auth/account/delete/cancel",
		path:         "/api/v1/auth/account/delete/cancel",
		query:        query,
	}
}

// CancelDelete issues GET /api/v1/auth/account/delete/cancel.
func (a *PrivacyAPI) CancelDelete(ctx context.Context, token string) error {
	call := a.callPrivacyCancelDelete(token)
	return sendManagementNoContent(ctx, a.c, call)
}
