// Code generated by internal/cmd/genmanagement. DO NOT EDIT.
//
// Generated from management-registry.json and openapi.json. Regenerate with
// `go run ./internal/cmd/genmanagement`; CI verifies the committed output
// is current.

// One accessor per §27 namespace.
//
// §27.2 makes this namespacing normative rather than stylistic: twenty
// namespaces have a List and fourteen a Get, so flattening 146 operations
// onto the Client would need a disambiguating prefix invented once per
// operation — and would bury the eight §1 methods most callers actually
// want under five times as many they do not.
//
// Each accessor builds its handle on access and performs no I/O (§27.2
// rule 1), so holding one costs nothing and none of them runs at
// construction.

package axiam

// Organizations returns the organizations management namespace handle.
//
// Organizations an SDK client may read and configure. Creation and
// deletion are outside the SDK boundary (§27.0).
func (c *Client) Organizations() *OrganizationsAPI {
	return &OrganizationsAPI{c: c}
}

// Tenants returns the tenants management namespace handle.
//
// Tenants within an organization -- the isolation boundary every other
// namespace is scoped to.
func (c *Client) Tenants() *TenantsAPI {
	return &TenantsAPI{c: c}
}

// Users returns the users management namespace handle.
//
// Users within the client's tenant, and the administrative side of their
// second factor and lockout state.
func (c *Client) Users() *UsersAPI {
	return &UsersAPI{c: c}
}

// Groups returns the groups management namespace handle.
//
// Named collections of users. Roles assigned to a group are inherited by
// every member.
func (c *Client) Groups() *GroupsAPI {
	return &GroupsAPI{c: c}
}

// Roles returns the roles management namespace handle.
//
// Roles, their permission sets, and their assignment to users and groups.
func (c *Client) Roles() *RolesAPI {
	return &RolesAPI{c: c}
}

// Permissions returns the permissions management namespace handle.
//
// Permissions -- an action on a resource, optionally narrowed by a scope.
func (c *Client) Permissions() *PermissionsAPI {
	return &PermissionsAPI{c: c}
}

// Resources returns the resources management namespace handle.
//
// The resource hierarchy role assignments cascade down.
func (c *Client) Resources() *ResourcesAPI {
	return &ResourcesAPI{c: c}
}

// Scopes returns the scopes management namespace handle.
//
// Sub-resource granularity, always addressed under their resource.
func (c *Client) Scopes() *ScopesAPI {
	return &ScopesAPI{c: c}
}

// ServiceAccounts returns the service_accounts management namespace handle.
//
// Machine identities, their secrets, and the certificate a device-bound
// one authenticates with.
func (c *Client) ServiceAccounts() *ServiceAccountsAPI {
	return &ServiceAccountsAPI{c: c}
}

// Certificates returns the certificates management namespace handle.
//
// End-entity X.509 certificates -- the ones issued to users, services and
// IoT devices.
func (c *Client) Certificates() *CertificatesAPI {
	return &CertificatesAPI{c: c}
}

// CACertificates returns the ca_certificates management namespace handle.
//
// Organization CAs and the per-tenant signing CAs chained beneath them.
func (c *Client) CACertificates() *CACertificatesAPI {
	return &CACertificatesAPI{c: c}
}

// PGPKeys returns the pgp_keys management namespace handle.
//
// OpenPGP keys used for audit signing and encrypted data export.
func (c *Client) PGPKeys() *PGPKeysAPI {
	return &PGPKeysAPI{c: c}
}

// Webhooks returns the webhooks management namespace handle.
//
// Outbound event notifications. Delivery signatures are verified with the
// §13 helper, which this namespace configures.
func (c *Client) Webhooks() *WebhooksAPI {
	return &WebhooksAPI{c: c}
}

// OAuth2Clients returns the oauth2_clients management namespace handle.
//
// Registered OAuth2/OIDC clients -- the registration half of what §12,
// §21 and §26 then speak to.
func (c *Client) OAuth2Clients() *OAuth2ClientsAPI {
	return &OAuth2ClientsAPI{c: c}
}

// Federation returns the federation management namespace handle.
//
// Upstream IdP configuration and the per-user links it produces.
func (c *Client) Federation() *FederationAPI {
	return &FederationAPI{c: c}
}

// NotificationRules returns the notification_rules management namespace handle.
//
// Which events raise a notification, and to whom.
func (c *Client) NotificationRules() *NotificationRulesAPI {
	return &NotificationRulesAPI{c: c}
}

// EmailConfig returns the email_config management namespace handle.
//
// Transactional-mail transport, configurable at organization level and
// overridable per tenant.
func (c *Client) EmailConfig() *EmailConfigAPI {
	return &EmailConfigAPI{c: c}
}

// Settings returns the settings management namespace handle.
//
// Effective settings, and the organization/tenant layers they resolve
// from.
func (c *Client) Settings() *SettingsAPI {
	return &SettingsAPI{c: c}
}

// SCIMTokens returns the scim_tokens management namespace handle.
//
// Bearer tokens for the SCIM 2.0 provisioning endpoint.
func (c *Client) SCIMTokens() *SCIMTokensAPI {
	return &SCIMTokensAPI{c: c}
}

// Reactors returns the reactors management namespace handle.
//
// Registration of §22 AMQP extension actors -- the admin surface §22.9
// describes, which no SDK could previously reach.
func (c *Client) Reactors() *ReactorsAPI {
	return &ReactorsAPI{c: c}
}

// WebauthnPolicy returns the webauthn_policy management namespace handle.
//
// Per-tenant attestation policy governing the §24 ceremonies, and the
// compliance report over it.
func (c *Client) WebauthnPolicy() *WebauthnPolicyAPI {
	return &WebauthnPolicyAPI{c: c}
}

// Audit returns the audit management namespace handle.
//
// Append-only audit log, read-only by construction.
func (c *Client) Audit() *AuditAPI {
	return &AuditAPI{c: c}
}

// Privacy returns the privacy management namespace handle.
//
// GDPR self-service: the authenticated account's own export and erasure.
// Scoped to the caller, never to another user.
func (c *Client) Privacy() *PrivacyAPI {
	return &PrivacyAPI{c: c}
}

// Platform returns the platform management namespace handle.
//
// Deployment-level probes and FIDO metadata state. Unauthenticated where
// the server leaves them so.
func (c *Client) Platform() *PlatformAPI {
	return &PlatformAPI{c: c}
}
