// Code generated by internal/cmd/genmanagement. DO NOT EDIT.
//
// Generated from management-registry.json and openapi.json. Regenerate with
// `go run ./internal/cmd/genmanagement`; CI verifies the committed output
// is current.

// The saml management namespace (CONTRACT §27.1).
//
// A tenant's SAML 2.0 identity provider (CONTRACT §29): the registry of
// service providers, the import of an SP's metadata into a *draft*
// registration (never a write), and the lifecycle of the IdP signing
// credential. The protocol itself -- single sign-on, single logout, the
// IdP metadata document -- is browser and SP-to-IdP surface under
// /saml/v2/{tenant_id}, an SP's own SAML library speaks to it, and it is
// not in this registry.

package axiam

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/google/uuid"
)

// SAMLAPI is the saml namespace handle.
//
// A tenant's SAML 2.0 identity provider (CONTRACT §29): the registry of
// service providers, the import of an SP's metadata into a *draft*
// registration (never a write), and the lifecycle of the IdP signing
// credential. The protocol itself -- single sign-on, single logout, the
// IdP metadata document -- is browser and SP-to-IdP surface under
// /saml/v2/{tenant_id}, an SP's own SAML library speaks to it, and it is
// not in this registry.
//
// Acquiring one performs no I/O and allocates nothing meaningful (§27.2
// rule 1); it holds the client and cannot be constructed without one.
type SAMLAPI struct {
	c     *Client
	scope namespaceScope
}

// ForTenant addresses a different tenant than the client's own (§27.4 rule 3).
//
// Returns a new handle; the original is unchanged.
func (a *SAMLAPI) ForTenant(tenantID uuid.UUID) *SAMLAPI {
	return &SAMLAPI{c: a.c, scope: a.scope.withTenant(tenantID)}
}

// callSAMLGetIdp builds the saml.get_idp call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *SAMLAPI) callSAMLGetIdp() (managementCall, error) {
	tenantID, err := a.c.resolveTenant(a.scope, "saml.get_idp")
	if err != nil {
		return managementCall{}, err
	}
	return managementCall{
		operation:    "saml.get_idp",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/tenants/{tenant_id}/saml/idp",
		path:         fmt.Sprintf("/api/v1/tenants/%s/saml/idp", tenantID.String()),
	}, nil
}

// GetIdp issues GET /api/v1/tenants/{tenant_id}/saml/idp.
func (a *SAMLAPI) GetIdp(ctx context.Context) (SAMLIdpInfo, error) {
	call, err := a.callSAMLGetIdp()
	if err != nil {
		var zero SAMLIdpInfo
		return zero, err
	}
	return sendManagement[SAMLIdpInfo](ctx, a.c, call)
}

// callSAMLListServiceProviders builds the saml.list_service_providers call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *SAMLAPI) callSAMLListServiceProviders(page PageRequest) (managementCall, error) {
	tenantID, err := a.c.resolveTenant(a.scope, "saml.list_service_providers")
	if err != nil {
		return managementCall{}, err
	}
	query := url.Values{}
	query = pageQuery(page, query)
	return managementCall{
		operation:    "saml.list_service_providers",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/tenants/{tenant_id}/saml/service-providers",
		path:         fmt.Sprintf("/api/v1/tenants/%s/saml/service-providers", tenantID.String()),
		query:        query,
	}, nil
}

// ListServiceProviders issues GET /api/v1/tenants/{tenant_id}/saml/service-providers.
func (a *SAMLAPI) ListServiceProviders(ctx context.Context, page PageRequest) (Page[SAMLServiceProvider], error) {
	call, err := a.callSAMLListServiceProviders(page)
	if err != nil {
		var zero Page[SAMLServiceProvider]
		return zero, err
	}
	return sendManagement[Page[SAMLServiceProvider]](ctx, a.c, call)
}

// ListServiceProvidersAll walks saml.list_service_providers to exhaustion, concatenating every
// page.
//
// The auto-paging form §27.4 rule 4 requires. It stops on an empty page
// even if Total disagrees, so a misreporting server costs one wasted
// request rather than an unbounded loop.
func (a *SAMLAPI) ListServiceProvidersAll(ctx context.Context, start PageRequest) ([]SAMLServiceProvider, error) {
	return collectPages(ctx, start, func(ctx context.Context, p PageRequest) (Page[SAMLServiceProvider], error) {
		return a.ListServiceProviders(ctx, p)
	})
}

// callSAMLCreateServiceProvider builds the saml.create_service_provider call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *SAMLAPI) callSAMLCreateServiceProvider(body SAMLServiceProviderInput) (managementCall, error) {
	tenantID, err := a.c.resolveTenant(a.scope, "saml.create_service_provider")
	if err != nil {
		return managementCall{}, err
	}
	return managementCall{
		operation:    "saml.create_service_provider",
		method:       http.MethodPost,
		pathTemplate: "/api/v1/tenants/{tenant_id}/saml/service-providers",
		path:         fmt.Sprintf("/api/v1/tenants/%s/saml/service-providers", tenantID.String()),
		body:         body,
	}, nil
}

// CreateServiceProvider issues POST /api/v1/tenants/{tenant_id}/saml/service-providers.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *SAMLAPI) CreateServiceProvider(ctx context.Context, body SAMLServiceProviderInput) (SAMLServiceProvider, error) {
	call, err := a.callSAMLCreateServiceProvider(body)
	if err != nil {
		var zero SAMLServiceProvider
		return zero, err
	}
	return sendManagement[SAMLServiceProvider](ctx, a.c, call)
}

// callSAMLGetServiceProvider builds the saml.get_service_provider call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *SAMLAPI) callSAMLGetServiceProvider(spID uuid.UUID) (managementCall, error) {
	tenantID, err := a.c.resolveTenant(a.scope, "saml.get_service_provider")
	if err != nil {
		return managementCall{}, err
	}
	return managementCall{
		operation:    "saml.get_service_provider",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/tenants/{tenant_id}/saml/service-providers/{sp_id}",
		path:         fmt.Sprintf("/api/v1/tenants/%s/saml/service-providers/%s", tenantID.String(), spID.String()),
	}, nil
}

// GetServiceProvider issues GET /api/v1/tenants/{tenant_id}/saml/service-providers/{sp_id}.
func (a *SAMLAPI) GetServiceProvider(ctx context.Context, spID uuid.UUID) (SAMLServiceProvider, error) {
	call, err := a.callSAMLGetServiceProvider(spID)
	if err != nil {
		var zero SAMLServiceProvider
		return zero, err
	}
	return sendManagement[SAMLServiceProvider](ctx, a.c, call)
}

// callSAMLUpdateServiceProvider builds the saml.update_service_provider call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *SAMLAPI) callSAMLUpdateServiceProvider(spID uuid.UUID, body SAMLServiceProviderInput) (managementCall, error) {
	tenantID, err := a.c.resolveTenant(a.scope, "saml.update_service_provider")
	if err != nil {
		return managementCall{}, err
	}
	return managementCall{
		operation:    "saml.update_service_provider",
		method:       http.MethodPut,
		pathTemplate: "/api/v1/tenants/{tenant_id}/saml/service-providers/{sp_id}",
		path:         fmt.Sprintf("/api/v1/tenants/%s/saml/service-providers/%s", tenantID.String(), spID.String()),
		body:         body,
	}, nil
}

// UpdateServiceProvider issues PUT /api/v1/tenants/{tenant_id}/saml/service-providers/{sp_id}.
//
// This is a REPLACEMENT, not a patch (§27.4 rule 5). Every field of the
// body is required, and what you do not carry over from a prior read is
// not preserved — it is overwritten. Read first, change the field you
// mean, send the whole thing back.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *SAMLAPI) UpdateServiceProvider(ctx context.Context, spID uuid.UUID, body SAMLServiceProviderInput) (SAMLServiceProvider, error) {
	call, err := a.callSAMLUpdateServiceProvider(spID, body)
	if err != nil {
		var zero SAMLServiceProvider
		return zero, err
	}
	return sendManagement[SAMLServiceProvider](ctx, a.c, call)
}

// callSAMLDeleteServiceProvider builds the saml.delete_service_provider call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *SAMLAPI) callSAMLDeleteServiceProvider(spID uuid.UUID) (managementCall, error) {
	tenantID, err := a.c.resolveTenant(a.scope, "saml.delete_service_provider")
	if err != nil {
		return managementCall{}, err
	}
	return managementCall{
		operation:    "saml.delete_service_provider",
		method:       http.MethodDelete,
		pathTemplate: "/api/v1/tenants/{tenant_id}/saml/service-providers/{sp_id}",
		path:         fmt.Sprintf("/api/v1/tenants/%s/saml/service-providers/%s", tenantID.String(), spID.String()),
	}, nil
}

// DeleteServiceProvider issues DELETE
// /api/v1/tenants/{tenant_id}/saml/service-providers/{sp_id}.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *SAMLAPI) DeleteServiceProvider(ctx context.Context, spID uuid.UUID) error {
	call, err := a.callSAMLDeleteServiceProvider(spID)
	if err != nil {
		return err
	}
	return sendManagementNoContent(ctx, a.c, call)
}

// callSAMLParseSpMetadata builds the saml.parse_sp_metadata call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *SAMLAPI) callSAMLParseSpMetadata(body ParseSAMLSpMetadata) (managementCall, error) {
	tenantID, err := a.c.resolveTenant(a.scope, "saml.parse_sp_metadata")
	if err != nil {
		return managementCall{}, err
	}
	return managementCall{
		operation:    "saml.parse_sp_metadata",
		method:       http.MethodPost,
		pathTemplate: "/api/v1/tenants/{tenant_id}/saml/parse-sp-metadata",
		path:         fmt.Sprintf("/api/v1/tenants/%s/saml/parse-sp-metadata", tenantID.String()),
		body:         body,
	}, nil
}

// ParseSpMetadata issues POST /api/v1/tenants/{tenant_id}/saml/parse-sp-metadata.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *SAMLAPI) ParseSpMetadata(ctx context.Context, body ParseSAMLSpMetadata) (SAMLSpMetadataDraft, error) {
	call, err := a.callSAMLParseSpMetadata(body)
	if err != nil {
		var zero SAMLSpMetadataDraft
		return zero, err
	}
	return sendManagement[SAMLSpMetadataDraft](ctx, a.c, call)
}

// callSAMLListIdpCredentials builds the saml.list_idp_credentials call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *SAMLAPI) callSAMLListIdpCredentials() (managementCall, error) {
	tenantID, err := a.c.resolveTenant(a.scope, "saml.list_idp_credentials")
	if err != nil {
		return managementCall{}, err
	}
	return managementCall{
		operation:    "saml.list_idp_credentials",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/tenants/{tenant_id}/saml/idp-credentials",
		path:         fmt.Sprintf("/api/v1/tenants/%s/saml/idp-credentials", tenantID.String()),
	}, nil
}

// ListIdpCredentials issues GET /api/v1/tenants/{tenant_id}/saml/idp-credentials.
func (a *SAMLAPI) ListIdpCredentials(ctx context.Context) ([]SAMLIdpCredential, error) {
	call, err := a.callSAMLListIdpCredentials()
	if err != nil {
		var zero []SAMLIdpCredential
		return zero, err
	}
	return sendManagement[[]SAMLIdpCredential](ctx, a.c, call)
}

// callSAMLIssueIdpCredential builds the saml.issue_idp_credential call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *SAMLAPI) callSAMLIssueIdpCredential(body IssueSAMLIdpCredential) (managementCall, error) {
	tenantID, err := a.c.resolveTenant(a.scope, "saml.issue_idp_credential")
	if err != nil {
		return managementCall{}, err
	}
	return managementCall{
		operation:    "saml.issue_idp_credential",
		method:       http.MethodPost,
		pathTemplate: "/api/v1/tenants/{tenant_id}/saml/idp-credentials",
		path:         fmt.Sprintf("/api/v1/tenants/%s/saml/idp-credentials", tenantID.String()),
		body:         body,
	}, nil
}

// IssueIdpCredential issues POST /api/v1/tenants/{tenant_id}/saml/idp-credentials.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *SAMLAPI) IssueIdpCredential(ctx context.Context, body IssueSAMLIdpCredential) (SAMLIdpCredential, error) {
	call, err := a.callSAMLIssueIdpCredential(body)
	if err != nil {
		var zero SAMLIdpCredential
		return zero, err
	}
	return sendManagement[SAMLIdpCredential](ctx, a.c, call)
}

// callSAMLPromoteIdpCredential builds the saml.promote_idp_credential call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *SAMLAPI) callSAMLPromoteIdpCredential(credentialID uuid.UUID) (managementCall, error) {
	tenantID, err := a.c.resolveTenant(a.scope, "saml.promote_idp_credential")
	if err != nil {
		return managementCall{}, err
	}
	return managementCall{
		operation:    "saml.promote_idp_credential",
		method:       http.MethodPost,
		pathTemplate: "/api/v1/tenants/{tenant_id}/saml/idp-credentials/{credential_id}/promote",
		path:         fmt.Sprintf("/api/v1/tenants/%s/saml/idp-credentials/%s/promote", tenantID.String(), credentialID.String()),
	}, nil
}

// PromoteIdpCredential issues POST
// /api/v1/tenants/{tenant_id}/saml/idp-credentials/{credential_id}/promote.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *SAMLAPI) PromoteIdpCredential(ctx context.Context, credentialID uuid.UUID) (SAMLIdpCredentialPromotion, error) {
	call, err := a.callSAMLPromoteIdpCredential(credentialID)
	if err != nil {
		var zero SAMLIdpCredentialPromotion
		return zero, err
	}
	return sendManagement[SAMLIdpCredentialPromotion](ctx, a.c, call)
}

// callSAMLRetireIdpCredential builds the saml.retire_idp_credential call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *SAMLAPI) callSAMLRetireIdpCredential(credentialID uuid.UUID) (managementCall, error) {
	tenantID, err := a.c.resolveTenant(a.scope, "saml.retire_idp_credential")
	if err != nil {
		return managementCall{}, err
	}
	return managementCall{
		operation:    "saml.retire_idp_credential",
		method:       http.MethodPost,
		pathTemplate: "/api/v1/tenants/{tenant_id}/saml/idp-credentials/{credential_id}/retire",
		path:         fmt.Sprintf("/api/v1/tenants/%s/saml/idp-credentials/%s/retire", tenantID.String(), credentialID.String()),
	}, nil
}

// RetireIdpCredential issues POST
// /api/v1/tenants/{tenant_id}/saml/idp-credentials/{credential_id}/retire.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *SAMLAPI) RetireIdpCredential(ctx context.Context, credentialID uuid.UUID) (SAMLIdpCredential, error) {
	call, err := a.callSAMLRetireIdpCredential(credentialID)
	if err != nil {
		var zero SAMLIdpCredential
		return zero, err
	}
	return sendManagement[SAMLIdpCredential](ctx, a.c, call)
}
