// Code generated by internal/cmd/genmanagement. DO NOT EDIT.
//
// Generated from management-registry.json and openapi.json. Regenerate with
// `go run ./internal/cmd/genmanagement`; CI verifies the committed output
// is current.

// The certificates management namespace (CONTRACT §27.1).
//
// End-entity X.509 certificates -- the ones issued to users, services and
// IoT devices.

package axiam

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/google/uuid"
)

// CertificatesAPI is the certificates namespace handle.
//
// End-entity X.509 certificates -- the ones issued to users, services and
// IoT devices.
//
// Acquiring one performs no I/O and allocates nothing meaningful (§27.2
// rule 1); it holds the client and cannot be constructed without one.
type CertificatesAPI struct {
	c     *Client
	scope namespaceScope
}

// callCertificatesList builds the certificates.list call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *CertificatesAPI) callCertificatesList(page PageRequest) managementCall {
	query := url.Values{}
	query = pageQuery(page, query)
	return managementCall{
		operation:    "certificates.list",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/certificates",
		path:         "/api/v1/certificates",
		query:        query,
	}
}

// List issues GET /api/v1/certificates.
func (a *CertificatesAPI) List(ctx context.Context, page PageRequest) (Page[Certificate], error) {
	call := a.callCertificatesList(page)
	return sendManagement[Page[Certificate]](ctx, a.c, call)
}

// ListAll walks certificates.list to exhaustion, concatenating every page.
//
// The auto-paging form §27.4 rule 4 requires. It stops on an empty page
// even if Total disagrees, so a misreporting server costs one wasted
// request rather than an unbounded loop.
func (a *CertificatesAPI) ListAll(ctx context.Context, start PageRequest) ([]Certificate, error) {
	return collectPages(ctx, start, func(ctx context.Context, p PageRequest) (Page[Certificate], error) {
		return a.List(ctx, p)
	})
}

// callCertificatesGenerate builds the certificates.generate call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *CertificatesAPI) callCertificatesGenerate(body CreateCertificateRequest) managementCall {
	return managementCall{
		operation:    "certificates.generate",
		method:       http.MethodPost,
		pathTemplate: "/api/v1/certificates",
		path:         "/api/v1/certificates",
		body:         body,
	}
}

// Generate issues POST /api/v1/certificates.
//
// Returns secret material, once. private_key_pem is returned by this call
// and by no other; no later Get will return it again, and the Get
// projection has no field where it was. Discarding the result destroys the
// credential (§27.5 rule 3).
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *CertificatesAPI) Generate(ctx context.Context, body CreateCertificateRequest) (GeneratedCertificate, error) {
	call := a.callCertificatesGenerate(body)
	return sendManagement[GeneratedCertificate](ctx, a.c, call)
}

// callCertificatesGet builds the certificates.get call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *CertificatesAPI) callCertificatesGet(id uuid.UUID) managementCall {
	return managementCall{
		operation:    "certificates.get",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/certificates/{id}",
		path:         fmt.Sprintf("/api/v1/certificates/%s", id.String()),
	}
}

// Get issues GET /api/v1/certificates/{id}.
func (a *CertificatesAPI) Get(ctx context.Context, id uuid.UUID) (Certificate, error) {
	call := a.callCertificatesGet(id)
	return sendManagement[Certificate](ctx, a.c, call)
}

// callCertificatesRevoke builds the certificates.revoke call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *CertificatesAPI) callCertificatesRevoke(id uuid.UUID) managementCall {
	return managementCall{
		operation:    "certificates.revoke",
		method:       http.MethodPost,
		pathTemplate: "/api/v1/certificates/{id}/revoke",
		path:         fmt.Sprintf("/api/v1/certificates/%s/revoke", id.String()),
	}
}

// Revoke issues POST /api/v1/certificates/{id}/revoke.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *CertificatesAPI) Revoke(ctx context.Context, id uuid.UUID) error {
	call := a.callCertificatesRevoke(id)
	return sendManagementNoContent(ctx, a.c, call)
}
