// Code generated by internal/cmd/genmanagement. DO NOT EDIT.
//
// Generated from management-registry.json and openapi.json. Regenerate with
// `go run ./internal/cmd/genmanagement`; CI verifies the committed output
// is current.

// The scopes management namespace (CONTRACT §27.1).
//
// Sub-resource granularity, always addressed under their resource.

package axiam

import (
	"context"
	"fmt"
	"net/http"

	"github.com/google/uuid"
)

// ScopesAPI is the scopes namespace handle.
//
// Sub-resource granularity, always addressed under their resource.
//
// Acquiring one performs no I/O and allocates nothing meaningful (§27.2
// rule 1); it holds the client and cannot be constructed without one.
type ScopesAPI struct {
	c     *Client
	scope namespaceScope
}

// callScopesList builds the scopes.list call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *ScopesAPI) callScopesList(resourceID uuid.UUID) managementCall {
	return managementCall{
		operation:    "scopes.list",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/resources/{resource_id}/scopes",
		path:         fmt.Sprintf("/api/v1/resources/%s/scopes", resourceID.String()),
	}
}

// List issues GET /api/v1/resources/{resource_id}/scopes.
func (a *ScopesAPI) List(ctx context.Context, resourceID uuid.UUID) ([]Scope, error) {
	call := a.callScopesList(resourceID)
	return sendManagement[[]Scope](ctx, a.c, call)
}

// callScopesCreate builds the scopes.create call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *ScopesAPI) callScopesCreate(resourceID uuid.UUID, body CreateScopeRequest) managementCall {
	return managementCall{
		operation:    "scopes.create",
		method:       http.MethodPost,
		pathTemplate: "/api/v1/resources/{resource_id}/scopes",
		path:         fmt.Sprintf("/api/v1/resources/%s/scopes", resourceID.String()),
		body:         body,
	}
}

// Create issues POST /api/v1/resources/{resource_id}/scopes.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *ScopesAPI) Create(ctx context.Context, resourceID uuid.UUID, body CreateScopeRequest) (Scope, error) {
	call := a.callScopesCreate(resourceID, body)
	return sendManagement[Scope](ctx, a.c, call)
}

// callScopesGet builds the scopes.get call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *ScopesAPI) callScopesGet(resourceID uuid.UUID, scopeID uuid.UUID) managementCall {
	return managementCall{
		operation:    "scopes.get",
		method:       http.MethodGet,
		pathTemplate: "/api/v1/resources/{resource_id}/scopes/{scope_id}",
		path:         fmt.Sprintf("/api/v1/resources/%s/scopes/%s", resourceID.String(), scopeID.String()),
	}
}

// Get issues GET /api/v1/resources/{resource_id}/scopes/{scope_id}.
func (a *ScopesAPI) Get(ctx context.Context, resourceID uuid.UUID, scopeID uuid.UUID) (Scope, error) {
	call := a.callScopesGet(resourceID, scopeID)
	return sendManagement[Scope](ctx, a.c, call)
}

// callScopesUpdate builds the scopes.update call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *ScopesAPI) callScopesUpdate(resourceID uuid.UUID, scopeID uuid.UUID, body UpdateScopeRequest) managementCall {
	return managementCall{
		operation:    "scopes.update",
		method:       http.MethodPut,
		pathTemplate: "/api/v1/resources/{resource_id}/scopes/{scope_id}",
		path:         fmt.Sprintf("/api/v1/resources/%s/scopes/%s", resourceID.String(), scopeID.String()),
		body:         body,
	}
}

// Update issues PUT /api/v1/resources/{resource_id}/scopes/{scope_id}.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *ScopesAPI) Update(ctx context.Context, resourceID uuid.UUID, scopeID uuid.UUID, body UpdateScopeRequest) (Scope, error) {
	call := a.callScopesUpdate(resourceID, scopeID, body)
	return sendManagement[Scope](ctx, a.c, call)
}

// callScopesDelete builds the scopes.delete call. Shared by the operation and its
// auto-paging form, so the path, query and body are decided in one place.
func (a *ScopesAPI) callScopesDelete(resourceID uuid.UUID, scopeID uuid.UUID) managementCall {
	return managementCall{
		operation:    "scopes.delete",
		method:       http.MethodDelete,
		pathTemplate: "/api/v1/resources/{resource_id}/scopes/{scope_id}",
		path:         fmt.Sprintf("/api/v1/resources/%s/scopes/%s", resourceID.String(), scopeID.String()),
	}
}

// Delete issues DELETE /api/v1/resources/{resource_id}/scopes/{scope_id}.
//
// Not retried on failure (§27.4 rule 8): every write on this surface is
// issued exactly once, including the ones that look idempotent.
func (a *ScopesAPI) Delete(ctx context.Context, resourceID uuid.UUID, scopeID uuid.UUID) error {
	call := a.callScopesDelete(resourceID, scopeID)
	return sendManagementNoContent(ctx, a.c, call)
}
