// Hand-written (not generated by internal/cmd/genmanagement): a client-side
// wire-shape guard for SubjectAltName, a §27.13 externally-tagged union
// management_models.go's generated struct cannot itself enforce.

package axiam

import (
	"encoding/json"
	"errors"
)

// MarshalJSON refuses to serialize a SubjectAltName that names neither or
// both branches (CONTRACT.md 1.52 N3, C-12 question 3 / §27.13's
// externally-tagged unions): the wire shape is EXACTLY one of {"dns": …} or
// {"ip": …}, never {} and never both keys in one element.
//
// SubjectAltName's two New<Type><Tag> constructors (management_models.go)
// already only ever build a value naming exactly one branch, so a value
// built through them was always correct. What this closes is the struct
// LITERAL: Go has no sum type, so SubjectAltName{} (neither) and
// SubjectAltName{DNS: &d, IP: &i} (both) both compile, and before this
// method existed, both marshaled silently — encoding/json's default
// struct-tag behaviour simply omits or includes each *string field
// independently, with no way to reject the combination. The caller-facing
// effect: sendManagementOnce's json.Marshal(call.body) call
// (management_request.go) already runs BEFORE any request is built, so an
// error here reaches the caller as this SDK's ordinary client-side-refusal
// shape — a *NetworkError wrapping "could not encode the request body",
// §27.4 rule 2's pattern — with the request never reaching the wire, rather
// than a malformed body reaching the server to be refused there instead.
func (s SubjectAltName) MarshalJSON() ([]byte, error) {
	switch {
	case s.DNS != nil && s.IP != nil:
		return nil, errors.New(
			"SubjectAltName names BOTH dns and ip; exactly one is required (CONTRACT.md §27.13) — " +
				"build it with NewSubjectAltNameDNS or NewSubjectAltNameIP, not a struct literal setting both fields")
	case s.DNS == nil && s.IP == nil:
		return nil, errors.New(
			"SubjectAltName names NEITHER dns nor ip; exactly one is required (CONTRACT.md §27.13) — " +
				"build it with NewSubjectAltNameDNS or NewSubjectAltNameIP, not an empty struct literal")
	case s.DNS != nil:
		return json.Marshal(struct {
			DNS string `json:"dns"`
		}{DNS: *s.DNS})
	default:
		return json.Marshal(struct {
			IP string `json:"ip"`
		}{IP: *s.IP})
	}
}
