package amqp

import (
	"encoding/hex"
	"encoding/json"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

// reactorVectorsPath is the vendored copy of the §22.13 reactor vectors,
// GENERATED by the server's own reactor sign path
// (axiam-amqp::reactor::protocol) and committed beside the §8 vectors in
// crates/axiam-amqp/tests/fixtures/. Same master key, same tenant, same
// derived subkey — which is why one loader idiom serves both files.
const reactorVectorsPath = "testdata/reactor_v2_reference_vectors.json"

// reactorVector is one signed message from the fixture.
type reactorVector struct {
	// CanonicalSignedJSON is the exact byte sequence HMAC ran over: the
	// message in declared field order with hmac_signature set to JSON
	// **null** — not omitted, which is the one canonicalization difference
	// from §8's own two message types.
	CanonicalSignedJSON string `json:"canonical_signed_json"`
	// HMACSignatureHex is HMAC-SHA256(derived_subkey, CanonicalSignedJSON).
	HMACSignatureHex string `json:"hmac_signature_hex"`
	// RoutingKey, on the two server→reactor vectors.
	RoutingKey string `json:"routing_key"`
	// ExpectedRejection, on the rejected-reply vectors.
	ExpectedRejection string `json:"expected_rejection"`
	// VerifyAgainstCorrelationID, on the correlation_replay vector: the
	// correlation this otherwise-valid reply is presented against.
	VerifyAgainstCorrelationID string `json:"verify_against_correlation_id"`
}

type reactorVectors struct {
	TenantID              string `json:"tenant_id"`
	ReactorID             string `json:"reactor_id"`
	ExpectedCorrelationID string `json:"expected_correlation_id"`
	KeyVersion            uint8  `json:"key_version"`
	FreshnessSkewSecs     int    `json:"freshness_skew_secs"`
	VerifiedAt            string `json:"verified_at"`
	HKDF                  struct {
		// The Go SDK never performs HKDF: §8.1 hands it the already-derived
		// per-tenant subkey from the management API and it never sees the
		// master key. The test consumes the same field the §8 test does.
		DerivedSubkeyHex string `json:"derived_subkey_hex"`
	} `json:"hkdf"`
	Topology struct {
		Exchange                string `json:"exchange"`
		ExchangeType            string `json:"exchange_type"`
		Queue                   string `json:"queue"`
		RoutingKeyLoginPostAuth string `json:"routing_key_login_post_auth"`
		RoutingKeyTokenPreIssue string `json:"routing_key_token_pre_issue"`
	} `json:"topology"`
	FieldOrder struct {
		ReactorEvent []string `json:"reactor_event"`
		ReactorReply []string `json:"reactor_reply"`
	} `json:"field_order"`
	ServerToReactor map[string]reactorVector `json:"server_to_reactor"`
	ReactorToServer map[string]reactorVector `json:"reactor_to_server"`
	RejectedReplies map[string]reactorVector `json:"rejected_replies"`
	NonceBinding    struct {
		NonceA   string `json:"nonce_a"`
		NonceB   string `json:"nonce_b"`
		HMACAHex string `json:"hmac_a_hex"`
		HMACBHex string `json:"hmac_b_hex"`
	} `json:"nonce_binding"`
}

func loadReactorVectors(t *testing.T) (reactorVectors, []byte) {
	t.Helper()
	raw, err := os.ReadFile(filepath.FromSlash(reactorVectorsPath))
	if err != nil {
		t.Fatalf("failed to read reactor vectors at %s: %v", reactorVectorsPath, err)
	}
	var v reactorVectors
	if err := json.Unmarshal(raw, &v); err != nil {
		t.Fatalf("failed to parse reactor vectors at %s: %v", reactorVectorsPath, err)
	}
	subkey, err := hex.DecodeString(v.HKDF.DerivedSubkeyHex)
	if err != nil || len(subkey) == 0 {
		t.Fatalf("fixture derived_subkey_hex is missing or not hex: %v", err)
	}
	return v, subkey
}

// vectorsNow is the instant the fixture was signed at. Every freshness check
// in this file runs against it rather than the wall clock, so the tests do
// not rot the moment the vectors are 300 seconds old.
func vectorsNow(t *testing.T, v reactorVectors) time.Time {
	t.Helper()
	ts, err := time.Parse(time.RFC3339, v.VerifiedAt)
	if err != nil {
		t.Fatalf("fixture verified_at is not RFC3339: %v", err)
	}
	return ts
}

// wireBody renders the on-the-wire form of a vector: its canonical bytes
// with the `null` placeholder replaced by the committed signature.
//
// The fixture's own `message` object is pretty-printed with alphabetically
// ordered keys, which is fine for a struct-based decoder but NOT usable
// here: `payload` is echoed byte-for-byte into the bytes this SDK re-signs,
// so re-indenting it would change the MAC. The canonical form IS the wire
// form modulo that one substitution.
func wireBody(t *testing.T, vec reactorVector) []byte {
	t.Helper()
	if vec.CanonicalSignedJSON == "" || vec.HMACSignatureHex == "" {
		t.Fatal("fixture vector is missing canonical_signed_json or hmac_signature_hex")
	}
	body, ok := strings.CutSuffix(vec.CanonicalSignedJSON, `"hmac_signature":null}`)
	if !ok {
		t.Fatalf("fixture canonical JSON does not end in the null hmac_signature placeholder: %s", vec.CanonicalSignedJSON)
	}
	return []byte(body + `"hmac_signature":"` + vec.HMACSignatureHex + `"}`)
}

// TestReactorVectors_FixtureShape pins the fixture's own declarations so a
// regenerated file that moved a field cannot pass silently.
func TestReactorVectors_FixtureShape(t *testing.T) {
	v, _ := loadReactorVectors(t)

	if v.KeyVersion != reactorKeyVersion {
		t.Fatalf("fixture key_version = %d, SDK signs %d", v.KeyVersion, reactorKeyVersion)
	}
	if got := time.Duration(v.FreshnessSkewSecs) * time.Second; got != defaultSkew {
		t.Fatalf("fixture freshness_skew_secs = %s, SDK default = %s", got, defaultSkew)
	}
	if v.Topology.Exchange != ReactorExchange || v.Topology.ExchangeType != "topic" {
		t.Fatalf("fixture topology %+v does not match ReactorExchange %q (topic)", v.Topology, ReactorExchange)
	}
	// §22.1: assert against the fixture's rendered names rather than
	// reimplementing the server's format string.
	if got := ReactorQueueName(v.TenantID, v.ReactorID); got != v.Topology.Queue {
		t.Fatalf("ReactorQueueName = %q, fixture = %q", got, v.Topology.Queue)
	}
	if got := ReactorRoutingKey(v.TenantID, ReactorEventTokenPreIssue); got != v.Topology.RoutingKeyTokenPreIssue {
		t.Fatalf("ReactorRoutingKey = %q, fixture = %q", got, v.Topology.RoutingKeyTokenPreIssue)
	}
	if got := ReactorRoutingKey(v.TenantID, ReactorEventLoginPostAuth); got != v.Topology.RoutingKeyLoginPostAuth {
		t.Fatalf("ReactorRoutingKey = %q, fixture = %q", got, v.Topology.RoutingKeyLoginPostAuth)
	}

	// The field order this SDK's canonical structs are declared in must be
	// the order the fixture names. The fixture annotates two entries, hence
	// the prefix comparison.
	assertFieldOrder := func(name string, declared []string, fixture []string) {
		t.Helper()
		if len(declared) != len(fixture) {
			t.Fatalf("%s: SDK declares %d fields, fixture names %d", name, len(declared), len(fixture))
		}
		for i := range declared {
			if !strings.HasPrefix(fixture[i], declared[i]) {
				t.Fatalf("%s field %d: SDK %q, fixture %q", name, i, declared[i], fixture[i])
			}
		}
	}
	assertFieldOrder("reactor_event",
		[]string{"tenant_id", "event", "correlation_id", "payload", "timeout_ms", "key_version", "nonce", "issued_at", "hmac_signature"},
		v.FieldOrder.ReactorEvent)
	assertFieldOrder("reactor_reply",
		[]string{"correlation_id", "tenant_id", "event", "decision", "reason", "patch", "require_mfa", "key_version", "nonce", "issued_at", "hmac_signature"},
		v.FieldOrder.ReactorReply)
}

// TestReactorVectors_VerifyDirection is §22.13's verify half: every
// committed event vector verifies under the derived subkey, and fails under
// any other key.
func TestReactorVectors_VerifyDirection(t *testing.T) {
	v, subkey := loadReactorVectors(t)
	now := vectorsNow(t, v)

	if len(v.ServerToReactor) == 0 {
		t.Fatal("fixture carries no server_to_reactor vectors")
	}
	for name, vec := range v.ServerToReactor {
		t.Run(name, func(t *testing.T) {
			body := wireBody(t, vec)

			event, err := decodeReactorEvent(subkey, body, v.TenantID, now, defaultSkew, nil)
			if err != nil {
				t.Fatalf("the server-signed %s vector must verify: %v", name, err)
			}
			if event.TenantID != v.TenantID {
				t.Fatalf("tenant_id = %q, want %q", event.TenantID, v.TenantID)
			}
			if event.CorrelationID != v.ExpectedCorrelationID {
				t.Fatalf("correlation_id = %q, want %q", event.CorrelationID, v.ExpectedCorrelationID)
			}
			if got := ReactorRoutingKey(event.TenantID, event.Event); got != vec.RoutingKey {
				t.Fatalf("routing key = %q, fixture = %q", got, vec.RoutingKey)
			}
			if event.Timeout <= 0 {
				t.Fatal("timeout_ms must survive decoding as a positive duration")
			}

			// Any other key must fail — the per-tenant subkey is what stops
			// a reactor in one tenant reading another's events.
			otherKey := append([]byte(nil), subkey...)
			otherKey[0] ^= 0xFF
			if _, err := decodeReactorEvent(otherKey, body, v.TenantID, now, defaultSkew, nil); err == nil {
				t.Fatal("an event must NOT verify under a different key")
			}
		})
	}
}

// TestReactorVectors_TamperingInvalidates covers §22.13's four named
// tamper targets. Each edit is applied to the wire bytes AFTER signing.
func TestReactorVectors_TamperingInvalidates(t *testing.T) {
	v, subkey := loadReactorVectors(t)
	now := vectorsNow(t, v)
	vec := v.ServerToReactor["token_pre_issue"]
	body := string(wireBody(t, vec))

	for _, tc := range []struct{ name, from, to string }{
		{"payload", `"sub":"alice"`, `"sub":"root"`},
		{"timeout_ms", `"timeout_ms":500`, `"timeout_ms":5000`},
		{"tenant_id", v.TenantID, "99999999-9999-9999-9999-999999999999"},
		{"nonce", `"nonce":"aaaaaaaa`, `"nonce":"abaaaaaa`},
	} {
		t.Run(tc.name, func(t *testing.T) {
			tampered := strings.Replace(body, tc.from, tc.to, 1)
			if tampered == body {
				t.Fatalf("test bug: %q not found in the vector body", tc.from)
			}
			// tenant_id appears in the routing key check too; the decode is
			// told the tampered tenant so the failure can only come from the
			// MAC, not from the identity check.
			tenant := v.TenantID
			if tc.name == "tenant_id" {
				tenant = ""
			}
			if _, err := decodeReactorEvent(subkey, []byte(tampered), tenant, now, defaultSkew, nil); err == nil {
				t.Fatalf("tampering with %s after signing must invalidate the event", tc.name)
			}
		})
	}
}

// TestReactorVectors_KeyVersionRefusedBeforeSignature asserts §22.2's
// ordering: a body carrying less than key_version 2 is refused before
// anything else about it is considered — including its signature, which in
// the fixture's downgraded vector no longer matches at all.
func TestReactorVectors_KeyVersionRefusedBeforeSignature(t *testing.T) {
	v, subkey := loadReactorVectors(t)
	now := vectorsNow(t, v)

	vec := v.ServerToReactor["token_pre_issue"]
	body := strings.Replace(string(wireBody(t, vec)), `"key_version":2`, `"key_version":1`, 1)

	_, err := decodeReactorEvent(subkey, []byte(body), v.TenantID, now, defaultSkew, nil)
	if err == nil {
		t.Fatal("key_version 1 must be refused")
	}
	if !errors.Is(err, ErrReactorKeyVersionTooOld) {
		t.Fatalf("refusal must name the key_version gate, not the signature: %v", err)
	}
}

// TestReactorVectors_FreshnessBothDirections covers §22.13's "in BOTH
// directions": a timestamp ahead of the verifier's clock is not extra fresh,
// it is the shape of a captured message held for later.
func TestReactorVectors_FreshnessBothDirections(t *testing.T) {
	v, subkey := loadReactorVectors(t)
	issued := vectorsNow(t, v)
	body := wireBody(t, v.ServerToReactor["token_pre_issue"])
	window := time.Duration(v.FreshnessSkewSecs) * time.Second

	for _, tc := range []struct {
		name  string
		now   time.Time
		valid bool
	}{
		{"at the edge, stale side", issued.Add(window), true},
		{"one second past the edge, stale side", issued.Add(window + time.Second), false},
		{"at the edge, future side", issued.Add(-window), true},
		{"one second past the edge, future side", issued.Add(-window - time.Second), false},
	} {
		t.Run(tc.name, func(t *testing.T) {
			_, err := decodeReactorEvent(subkey, body, v.TenantID, tc.now, window, nil)
			if tc.valid && err != nil {
				t.Fatalf("expected acceptance, got %v", err)
			}
			if !tc.valid {
				if err == nil {
					t.Fatal("expected refusal")
				}
				if !errors.Is(err, ErrReactorStale) {
					t.Fatalf("expected a staleness refusal, got %v", err)
				}
			}
		})
	}
}

// TestReactorVectors_NonceReplayRefused asserts the seen-set: the same event
// delivered twice inside the window is refused the second time.
func TestReactorVectors_NonceReplayRefused(t *testing.T) {
	v, subkey := loadReactorVectors(t)
	now := vectorsNow(t, v)
	body := wireBody(t, v.ServerToReactor["token_pre_issue"])
	guard := newReplayGuard(defaultSkew)

	if _, err := decodeReactorEvent(subkey, body, v.TenantID, now, defaultSkew, guard); err != nil {
		t.Fatalf("first delivery must verify: %v", err)
	}
	_, err := decodeReactorEvent(subkey, body, v.TenantID, now, defaultSkew, guard)
	if !errors.Is(err, ErrReactorReplay) {
		t.Fatalf("a redelivered nonce must be refused as a replay, got %v", err)
	}
}

// TestReactorVectors_TenantMismatchRefused asserts a reactor never acts on
// another tenant's event even when the signature is perfectly valid for
// that other tenant.
func TestReactorVectors_TenantMismatchRefused(t *testing.T) {
	v, subkey := loadReactorVectors(t)
	now := vectorsNow(t, v)
	body := wireBody(t, v.ServerToReactor["token_pre_issue"])

	_, err := decodeReactorEvent(subkey, body, "99999999-9999-9999-9999-999999999999", now, defaultSkew, nil)
	if !errors.Is(err, ErrReactorTenantMismatch) {
		t.Fatalf("an event for another tenant must be refused, got %v", err)
	}
}

// TestReactorVectors_SignDirection is §22.13's sign half. For each committed
// reply vector, building the reply from its fields must reproduce
// `canonical_signed_json` byte-for-byte AND recompute `hmac_signature_hex`.
//
// One assertion covers both: the published body is the canonical bytes with
// the null placeholder replaced by the signature this SDK computed, so
// equality against that string proves the canonicalization and the MAC
// together.
func TestReactorVectors_SignDirection(t *testing.T) {
	v, subkey := loadReactorVectors(t)
	signedAt := vectorsNow(t, v)

	// The nonce every committed reply vector carries.
	const replyNonce = "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"

	cases := []struct {
		name   string
		event  string
		answer ReactorAnswer
	}{
		{"allow", ReactorEventLoginPostAuth, ReactorAllow()},
		{"deny", ReactorEventLoginPostAuth, ReactorDeny("embargoed region")},
		{"mutate", ReactorEventTokenPreIssue, ReactorMutate(map[string]string{
			"ext.cost_center": "42",
			"ext.department":  "eng",
		})},
		{"require_mfa", ReactorEventLoginPostAuth, ReactorAllowWithStepUp()},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			vec, ok := v.ReactorToServer[tc.name]
			if !ok {
				t.Fatalf("fixture carries no reactor_to_server.%s vector", tc.name)
			}
			ev := ReactorEvent{
				TenantID:      v.TenantID,
				Event:         tc.event,
				CorrelationID: v.ExpectedCorrelationID,
			}
			body, err := buildReactorReply(subkey, ev, tc.answer, replyNonce, signedAt)
			if err != nil {
				t.Fatalf("building the %s reply failed: %v", tc.name, err)
			}
			want := strings.Replace(vec.CanonicalSignedJSON, `"hmac_signature":null`, `"hmac_signature":"`+vec.HMACSignatureHex+`"`, 1)
			if string(body) != want {
				t.Fatalf("reply bytes do not match the fixture.\n got: %s\nwant: %s", body, want)
			}
		})
	}
}

// TestReactorReply_OmissionRules asserts §22.2's three conditional omissions
// DIRECTLY, not just as a side effect of the vectors matching. A reply that
// serializes `"require_mfa": false` rather than omitting it produces
// different canonical bytes and therefore a different MAC.
func TestReactorReply_OmissionRules(t *testing.T) {
	v, subkey := loadReactorVectors(t)
	signedAt := vectorsNow(t, v)
	ev := ReactorEvent{TenantID: v.TenantID, Event: ReactorEventLoginPostAuth, CorrelationID: v.ExpectedCorrelationID}

	body, err := buildReactorReply(subkey, ev, ReactorAllow(), "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb", signedAt)
	if err != nil {
		t.Fatalf("building an allow reply failed: %v", err)
	}
	for _, absent := range []string{"require_mfa", "reason", "patch"} {
		if strings.Contains(string(body), absent) {
			t.Fatalf("an allow reply MUST omit %q entirely; got %s", absent, body)
		}
	}

	// And the placeholder itself: hmac_signature is present-and-null while
	// signing, never omitted. Its presence in the final body is trivially
	// true; what matters is that removing it from the signed bytes would
	// break verification — which the vector test above already proves,
	// because the fixture's canonical form carries the null.
	if !strings.Contains(string(body), `"hmac_signature":"`) {
		t.Fatalf("a published reply must carry its signature: %s", body)
	}

	// A deny with no reason still denies. The server substitutes its own
	// string, so the SDK omits the field rather than sending an empty one.
	denyBody, err := buildReactorReply(subkey, ev, ReactorDeny(""), "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb", signedAt)
	if err != nil {
		t.Fatalf("building a reasonless deny failed: %v", err)
	}
	if strings.Contains(string(denyBody), "reason") {
		t.Fatalf("a deny with no reason MUST omit the field: %s", denyBody)
	}
}

// TestReactorReply_NonceBinding is §22.13's nonce_binding pair: two replies
// differing in nothing but the nonce carry different MACs, because the nonce
// is inside the signed bytes.
//
// The server keeps no durable nonce-dedup store for replies, so this is the
// property that keeps two replies from being byte-identical — which is what
// makes a captured reply distinguishable from a fresh one.
func TestReactorReply_NonceBinding(t *testing.T) {
	v, subkey := loadReactorVectors(t)
	signedAt := vectorsNow(t, v)
	ev := ReactorEvent{TenantID: v.TenantID, Event: ReactorEventLoginPostAuth, CorrelationID: v.ExpectedCorrelationID}

	a, err := buildReactorReply(subkey, ev, ReactorAllow(), v.NonceBinding.NonceA, signedAt)
	if err != nil {
		t.Fatalf("building reply A failed: %v", err)
	}
	b, err := buildReactorReply(subkey, ev, ReactorAllow(), v.NonceBinding.NonceB, signedAt)
	if err != nil {
		t.Fatalf("building reply B failed: %v", err)
	}
	if !strings.Contains(string(a), v.NonceBinding.HMACAHex) {
		t.Fatalf("reply A's MAC does not match the fixture's hmac_a_hex\n got: %s\nwant: %s", a, v.NonceBinding.HMACAHex)
	}
	if !strings.Contains(string(b), v.NonceBinding.HMACBHex) {
		t.Fatalf("reply B's MAC does not match the fixture's hmac_b_hex\n got: %s\nwant: %s", b, v.NonceBinding.HMACBHex)
	}
	if v.NonceBinding.HMACAHex == v.NonceBinding.HMACBHex {
		t.Fatal("fixture bug: the nonce_binding pair must carry different MACs")
	}
}

// TestReactorReply_FreshNoncePerReply asserts the runtime does not reuse a
// nonce. A constant nonce is not a small deviation: it removes the only
// uniqueness a reply body carries beyond its timestamp.
func TestReactorReply_FreshNoncePerReply(t *testing.T) {
	seen := map[string]bool{}
	nonce := defaultReactorNonce()
	for range 64 {
		n := nonce()
		if n == "" {
			t.Fatal("nonce generator returned an empty string")
		}
		if seen[n] {
			t.Fatalf("nonce %q was reused", n)
		}
		seen[n] = true
	}
}

// TestReactorReply_CorrelationIsCopiedFromTheEvent covers §22.13's replay
// vector from the side an SDK actually owns.
//
// The server refuses the `correlation_replay` vector as wrong_correlation:
// identical bytes, valid signature, inside the freshness window, presented
// against a different in-flight event. What an SDK must guarantee for that
// check to mean anything is that it copies correlation_id from the EVENT
// BODY into the REPLY BODY — copying it only into the AMQP property produces
// a reply the server discards.
func TestReactorReply_CorrelationIsCopiedFromTheEvent(t *testing.T) {
	v, subkey := loadReactorVectors(t)
	signedAt := vectorsNow(t, v)

	vec := v.RejectedReplies["correlation_replay"]
	if vec.VerifyAgainstCorrelationID == "" {
		t.Fatal("fixture carries no correlation_replay.verify_against_correlation_id")
	}
	if vec.VerifyAgainstCorrelationID == v.ExpectedCorrelationID {
		t.Fatal("fixture bug: the replayed reply must be presented against a DIFFERENT correlation")
	}

	// Build a reply for the other in-flight event; it must carry that
	// event's correlation, not the replayed one — which is exactly why the
	// captured reply cannot be re-aimed.
	other := ReactorEvent{TenantID: v.TenantID, Event: ReactorEventLoginPostAuth, CorrelationID: vec.VerifyAgainstCorrelationID}
	body, err := buildReactorReply(subkey, other, ReactorAllow(), "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb", signedAt)
	if err != nil {
		t.Fatalf("building the reply failed: %v", err)
	}
	if !strings.Contains(string(body), `"correlation_id":"`+vec.VerifyAgainstCorrelationID+`"`) {
		t.Fatalf("the reply must carry the event's own correlation_id: %s", body)
	}
	if strings.Contains(string(body), v.ExpectedCorrelationID) {
		t.Fatalf("the reply must NOT carry another event's correlation_id: %s", body)
	}
	// And the captured reply's own bytes are unchanged, so a server holding
	// the other correlation refuses it on rule 1 before reading anything
	// else.
	if strings.Contains(vec.CanonicalSignedJSON, vec.VerifyAgainstCorrelationID) {
		t.Fatal("fixture bug: the replayed reply must not already name the correlation it is presented against")
	}
}
