// Command genmanagement generates the CONTRACT §27 management surface.
//
// It reads management-registry.json (the 146 operations across 24 namespaces,
// maintained in ilpanich/axiam and vendored here) plus openapi.json for the
// schemas those operations carry, and writes:
//
//   - management_models.go        — every request and response type
//   - management_<namespace>.go   — one namespace handle per namespace
//   - management_api.go           — the accessors on *Client
//   - management_surface_generated_test.go — one conformance case per operation
//
// Run with -check to verify the committed output is current; that is what CI
// runs, so a registry change that is not regenerated fails the build rather
// than shipping a surface that disagrees with the contract.
//
// Layout is decided by go/format rather than by this program's line breaking,
// the same way gofmt decides it for hand-written code.
//
//	go run ./internal/cmd/genmanagement
//	go run ./internal/cmd/genmanagement -check
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// implicitTenantNamespaces are the namespaces where {tenant_id} names the
// calling CONTEXT and so defaults from the client (§27.4 rule 3). Everywhere
// else — Tenants, and the signing CAs under CaCertificates — it names the
// object being acted on and stays an ordinary argument.
var implicitTenantNamespaces = map[string]bool{
	"email_config":    true,
	"settings":        true,
	"webauthn_policy": true,
}

// renamedSchemas are schema names that would collide with a type this package
// already exports. The generated surface shares one package with the rest of
// the SDK, so a duplicate name is a compile error rather than a shadowing.
var renamedSchemas = map[string]string{
	// §23's OpaqueEnrollment (opaque.go) is the enrolment *result* a caller
	// receives; this is the registration payload a caller *sends* when
	// creating a user. Different shapes, same server-side vocabulary.
	"OpaqueEnrollment": "OpaqueEnrollmentPayload",
	// Sensitive, Page and PageRequest are this package's own §7/§27 types.
	"Page":        "PageSchema",
	"PageRequest": "PageRequestSchema",
	"Sensitive":   "SensitiveSchema",
	// §1's AccessCheck/AccessResult in authz.go.
	"AccessCheck":  "AccessCheckSchema",
	"AccessResult": "AccessResultSchema",
	// §2's error types.
	"FieldError": "FieldErrorSchema",
}

const banner = `// Code generated by internal/cmd/genmanagement. DO NOT EDIT.
//
// Generated from management-registry.json and openapi.json. Regenerate with
// ` + "`go run ./internal/cmd/genmanagement`" + `; CI verifies the committed output
// is current.

`

const exampleUUID = "11111111-1111-4111-8111-111111111111"
const exampleTime = "2026-08-26T00:00:00Z"

// ---------------------------------------------------------------------------
// Registry and spec
// ---------------------------------------------------------------------------

type param struct {
	Name     string `json:"name"`
	Format   string `json:"format"`
	Required bool   `json:"required"`
	// Type is `any` because the registry writes a nullable query parameter's
	// type as the array ["string","null"] rather than a bare string. It is not
	// read — every query parameter on this surface travels as a string — but
	// decoding must not fail on the shape.
	Type any `json:"type"`
}

type response struct {
	Status int    `json:"status"`
	Kind   string `json:"kind"`
	Schema string `json:"schema"`
}

type operation struct {
	Method                  string   `json:"method"`
	Path                    string   `json:"path"`
	PathParams              []param  `json:"path_params"`
	QueryParams             []param  `json:"query_params"`
	Paginated               bool     `json:"paginated"`
	RequestBody             string   `json:"request_body"`
	RequestSchema           string   `json:"request_schema"`
	Response                response `json:"response"`
	SensitiveResponseFields []string `json:"sensitive_response_fields"`
	SensitiveRequestFields  []string `json:"sensitive_request_fields"`
	UpdateStyle             string   `json:"update_style"`
	Summary                 string   `json:"summary"`
}

type namespace struct {
	Doc        string               `json:"doc"`
	Operations map[string]operation `json:"operations"`
	order      []string
}

type registry struct {
	SpecVersion    string               `json:"spec_version"`
	OperationCount int                  `json:"operation_count"`
	NamespaceCount int                  `json:"namespace_count"`
	Namespaces     map[string]namespace `json:"namespaces"`
	order          []string
}

var reg registry
var schemas map[string]json.RawMessage
var root string

// orderedKeys reads the key order of a JSON object as it appears in the file,
// so generated output follows the registry's own order rather than Go's
// randomised map iteration — which would make every regeneration a diff.
func orderedKeys(raw []byte) []string {
	dec := json.NewDecoder(bytes.NewReader(raw))
	if _, err := dec.Token(); err != nil { // opening brace
		return nil
	}
	var keys []string
	depth := 0
	for dec.More() {
		tok, err := dec.Token()
		if err != nil {
			return keys
		}
		if depth == 0 {
			keys = append(keys, tok.(string))
			var skip json.RawMessage
			if err := dec.Decode(&skip); err != nil {
				return keys
			}
		}
	}
	return keys
}

func load() error {
	regRaw, err := os.ReadFile(filepath.Join(root, "management-registry.json"))
	if err != nil {
		return err
	}
	if err := json.Unmarshal(regRaw, &reg); err != nil {
		return err
	}

	var regObj struct {
		Namespaces json.RawMessage `json:"namespaces"`
	}
	if err := json.Unmarshal(regRaw, &regObj); err != nil {
		return err
	}
	reg.order = orderedKeys(regObj.Namespaces)

	var nsRaw map[string]json.RawMessage
	if err := json.Unmarshal(regObj.Namespaces, &nsRaw); err != nil {
		return err
	}
	for name, raw := range nsRaw {
		var holder struct {
			Operations json.RawMessage `json:"operations"`
		}
		if err := json.Unmarshal(raw, &holder); err != nil {
			return err
		}
		ns := reg.Namespaces[name]
		ns.order = orderedKeys(holder.Operations)
		reg.Namespaces[name] = ns
	}

	specRaw, err := os.ReadFile(filepath.Join(root, "openapi.json"))
	if err != nil {
		return err
	}
	var spec struct {
		Components struct {
			Schemas map[string]json.RawMessage `json:"schemas"`
		} `json:"components"`
	}
	if err := json.Unmarshal(specRaw, &spec); err != nil {
		return err
	}
	schemas = spec.Components.Schemas
	return nil
}

// ---------------------------------------------------------------------------
// Naming
// ---------------------------------------------------------------------------

// initialisms Go style guide requires be fully capitalised in identifiers.
var initialisms = map[string]string{
	"id": "ID", "ids": "IDs", "url": "URL", "uri": "URI", "api": "API",
	"ca": "CA", "csr": "CSR", "pem": "PEM", "json": "JSON", "http": "HTTP",
	"https": "HTTPS", "tls": "TLS", "mtls": "MTLS", "sso": "SSO", "mfa": "MFA",
	"totp": "TOTP", "oauth2": "OAuth2", "oidc": "OIDC", "saml": "SAML",
	"scim": "SCIM", "pgp": "PGP", "jwt": "JWT", "jwks": "JWKS", "uuid": "UUID",
	"smtp": "SMTP", "acl": "ACL", "rbac": "RBAC", "mds": "MDS", "aaguid": "AAGUID",
	"ttl": "TTL", "crl": "CRL", "ocsp": "OCSP", "ip": "IP", "cn": "CN",
}

// splitWords breaks an identifier into words on separators AND on case
// boundaries, so a schema name the spec writes in CamelCase gets the same
// initialism treatment as a snake_case operation name.
//
// Without the case split the surface is inconsistent with itself: the namespace
// scim_tokens becomes SCIMTokens (it has an underscore to split on) while the
// schema CreateScimTokenRequest stays Scim (it does not), and the SDK ends up
// with SCIMTokens().Create(CreateScimTokenRequest{}) — two spellings of one
// initialism in a single call.
func splitWords(s string) []string {
	var words []string
	var current strings.Builder
	flush := func() {
		if current.Len() > 0 {
			words = append(words, current.String())
			current.Reset()
		}
	}
	runes := []rune(s)
	for i, r := range runes {
		switch {
		case r == '_' || r == '-' || r == ' ' || r == '.':
			flush()
		case r >= 'A' && r <= 'Z':
			// A new word starts at an uppercase run's first letter, and at the
			// last letter of an uppercase run followed by a lowercase one
			// (so "HTTPServer" splits as HTTP + Server).
			if i > 0 {
				prev := runes[i-1]
				next := rune(0)
				if i+1 < len(runes) {
					next = runes[i+1]
				}
				prevUpper := prev >= 'A' && prev <= 'Z'
				nextLower := next >= 'a' && next <= 'z'
				if !prevUpper || (prevUpper && nextLower) {
					flush()
				}
			}
			current.WriteRune(r)
		default:
			current.WriteRune(r)
		}
	}
	flush()
	return words
}

func pascal(s string) string {
	parts := splitWords(s)
	var b strings.Builder
	for _, p := range parts {
		if up, ok := initialisms[strings.ToLower(p)]; ok {
			b.WriteString(up)
			continue
		}
		if p == "" {
			continue
		}
		b.WriteString(strings.ToUpper(p[:1]))
		b.WriteString(p[1:])
	}
	out := b.String()
	if renamed, ok := renamedSchemas[out]; ok {
		return renamed
	}
	return out
}

func camel(s string) string {
	p := pascal(s)
	if p == "" {
		return p
	}
	// Leading initialism stays lowercase in full: orgID -> orgID, not oRGID.
	for i, r := range p {
		if i > 0 && r >= 'a' && r <= 'z' {
			if i == 1 {
				return strings.ToLower(p[:1]) + p[1:]
			}
			return strings.ToLower(p[:i-1]) + p[i-1:]
		}
	}
	return strings.ToLower(p)
}

// goDoc renders text as a Go doc comment at the given indent.
func goDoc(indent, name, text string) string {
	text = strings.TrimSpace(text)
	if text == "" {
		return ""
	}
	var b strings.Builder
	first := true
	for _, para := range strings.Split(text, "\n\n") {
		if !first {
			b.WriteString(indent + "//\n")
		}
		for _, line := range wrap(strings.Join(strings.Fields(para), " "), 72-len(indent)) {
			prefix := ""
			if first && name != "" {
				prefix = name + " "
				name = ""
			}
			b.WriteString(indent + "// " + prefix + line + "\n")
			first = false
		}
		first = false
	}
	return b.String()
}

func wrap(text string, width int) []string {
	words := strings.Fields(text)
	if len(words) == 0 {
		return nil
	}
	var out []string
	line := ""
	for _, w := range words {
		if line != "" && len(line)+1+len(w) > width {
			out = append(out, line)
			line = w
		} else if line == "" {
			line = w
		} else {
			line += " " + w
		}
	}
	if line != "" {
		out = append(out, line)
	}
	return out
}

func sortedNames[V any](m map[string]V) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

// ---------------------------------------------------------------------------
// Schema analysis
// ---------------------------------------------------------------------------

// schemaNode is the subset of JSON Schema this surface actually uses.
type schemaNode struct {
	Ref         string                 `json:"$ref"`
	Type        any                    `json:"type"`
	Format      string                 `json:"format"`
	Enum        []any                  `json:"enum"`
	Items       *schemaNode            `json:"items"`
	Properties  map[string]*schemaNode `json:"properties"`
	Required    []string               `json:"required"`
	AllOf       []*schemaNode          `json:"allOf"`
	OneOf       []*schemaNode          `json:"oneOf"`
	AnyOf       []*schemaNode          `json:"anyOf"`
	Description string                 `json:"description"`

	propOrder []string
}

func parseSchema(raw json.RawMessage) *schemaNode {
	if len(raw) == 0 {
		return nil
	}
	var n schemaNode
	if err := json.Unmarshal(raw, &n); err != nil {
		return nil
	}
	var holder struct {
		Properties json.RawMessage `json:"properties"`
	}
	if err := json.Unmarshal(raw, &holder); err == nil && len(holder.Properties) > 0 {
		n.propOrder = orderedKeys(holder.Properties)
	}
	return &n
}

// propNames lists a node's property names.
//
// parseSchema records declaration order only for a schema read from the top
// level of components.schemas; a node reached as a nested allOf/oneOf member is
// decoded straight into schemaNode and has none. Falling back to the map's
// sorted keys is what stops those members' fields being silently DROPPED — the
// bug this helper exists to prevent lost provisioning_token from
// CreateScimTokenResponse, whose only field is declared in an inline allOf
// member, and a dropped field on a one-time secret is unrecoverable.
func propNames(n *schemaNode) []string {
	if n == nil {
		return nil
	}
	if len(n.propOrder) > 0 {
		return n.propOrder
	}
	return sortedNames(n.Properties)
}

func schemaByName(name string) *schemaNode {
	raw, ok := schemas[name]
	if !ok {
		return nil
	}
	return parseSchema(raw)
}

func refName(ref string) string {
	i := strings.LastIndex(ref, "/")
	return ref[i+1:]
}

func (n *schemaNode) typeName() string {
	switch t := n.Type.(type) {
	case string:
		return t
	case []any:
		for _, v := range t {
			if s, ok := v.(string); ok && s != "null" {
				return s
			}
		}
	}
	return ""
}

func (n *schemaNode) isNullable() bool {
	if t, ok := n.Type.([]any); ok {
		for _, v := range t {
			if s, ok := v.(string); ok && s == "null" {
				return true
			}
		}
	}
	return false
}

// nullableRef detects {oneOf: [{type: null}, {$ref: X}]} — utoipa's
// optional-enum shape.
func (n *schemaNode) nullableRef() string {
	if len(n.OneOf) != 2 {
		return ""
	}
	nulls, ref := 0, ""
	for _, v := range n.OneOf {
		if v.typeName() == "null" && v.Ref == "" {
			nulls++
		}
		if v.Ref != "" {
			ref = refName(v.Ref)
		}
	}
	if nulls == 1 && ref != "" {
		return ref
	}
	return ""
}

// goType is the Go type for a schema, without optionality applied.
func goType(n *schemaNode) string {
	if n == nil {
		return "any"
	}
	if n.Ref != "" {
		return pascal(refName(n.Ref))
	}
	if inner := n.nullableRef(); inner != "" {
		return "*" + pascal(inner)
	}
	if len(n.OneOf) > 0 || len(n.AnyOf) > 0 {
		return "any"
	}
	switch n.typeName() {
	case "string":
		if n.Format == "uuid" {
			return "uuid.UUID"
		}
		if len(n.Enum) > 0 {
			return "string"
		}
		return "string"
	case "integer":
		if n.Format == "int64" {
			return "int64"
		}
		return "int"
	case "number":
		return "float64"
	case "boolean":
		return "bool"
	case "array":
		return "[]" + goType(n.Items)
	case "object":
		return "map[string]any"
	}
	return "any"
}

// flatten resolves allOf into one property set, preserving declaration order.
func flatten(name string) (props map[string]*schemaNode, order []string, required map[string]bool, desc string) {
	props = map[string]*schemaNode{}
	required = map[string]bool{}
	seen := map[string]bool{}

	var absorb func(n *schemaNode)
	absorb = func(n *schemaNode) {
		if n == nil {
			return
		}
		if n.Ref != "" {
			absorb(schemaByName(refName(n.Ref)))
			return
		}
		for _, p := range propNames(n) {
			if !seen[p] {
				seen[p] = true
				order = append(order, p)
			}
			props[p] = n.Properties[p]
		}
		for _, r := range n.Required {
			required[r] = true
		}
		for _, sub := range n.AllOf {
			absorb(sub)
		}
	}

	top := schemaByName(name)
	if top != nil {
		desc = top.Description
	}
	absorb(top)
	sort.Strings(order)
	return props, order, required, desc
}

// unionArm is one variant of an internally-tagged union.
type unionArm struct {
	Value string
	Props map[string]*schemaNode
	Order []string
	Req   map[string]bool
}

// discriminated detects an internally-tagged union and returns its tag and arms.
func discriminated(n *schemaNode) (string, []unionArm, bool) {
	if n == nil || len(n.OneOf) < 2 {
		return "", nil, false
	}
	tag := ""
	var arms []unionArm
	for _, variant := range n.OneOf {
		parts := variant.AllOf
		if len(parts) == 0 {
			parts = []*schemaNode{variant}
		}
		arm := unionArm{Props: map[string]*schemaNode{}, Req: map[string]bool{}}
		value := ""
		for _, part := range parts {
			if part.Ref != "" {
				p, order, req, _ := flatten(refName(part.Ref))
				for k, v := range p {
					arm.Props[k] = v
				}
				arm.Order = append(arm.Order, order...)
				for k := range req {
					arm.Req[k] = true
				}
				continue
			}
			for _, name := range propNames(part) {
				prop := part.Properties[name]
				if prop.typeName() == "string" && len(prop.Enum) == 1 {
					if s, ok := prop.Enum[0].(string); ok {
						if tag != "" && tag != name {
							return "", nil, false
						}
						tag, value = name, s
						continue
					}
				}
				arm.Props[name] = prop
				arm.Order = append(arm.Order, name)
				for _, r := range part.Required {
					if r == name {
						arm.Req[name] = true
					}
				}
			}
		}
		if value == "" {
			return "", nil, false
		}
		arm.Value = value
		arms = append(arms, arm)
	}
	return tag, arms, true
}

// sensitiveFields maps a schema name to the fields the registry marks secret.
func sensitiveFields() map[string]map[string]bool {
	out := map[string]map[string]bool{}
	add := func(schema string, fields []string) {
		if schema == "" || len(fields) == 0 {
			return
		}
		key := strings.TrimPrefix(schema, "[]")
		if out[key] == nil {
			out[key] = map[string]bool{}
		}
		for _, f := range fields {
			out[key][f] = true
		}
	}
	for _, ns := range reg.Namespaces {
		for _, op := range ns.Operations {
			add(op.RequestSchema, op.SensitiveRequestFields)
			add(op.Response.Schema, op.SensitiveResponseFields)
		}
	}
	return out
}

// replacementSchemas are the request bodies whose PUT replaces rather than
// patches (§27.4 rule 5). Read from the registry's update_style rather than
// inferred from "every field is required", which is also true of most response
// types and would scatter constructors across the whole model file.
func replacementSchemas() map[string]bool {
	out := map[string]bool{}
	for _, ns := range reg.Namespaces {
		for _, op := range ns.Operations {
			if op.UpdateStyle == "replace" && op.RequestSchema != "" {
				out[strings.TrimPrefix(op.RequestSchema, "[]")] = true
			}
		}
	}
	return out
}

// requestSchemas are the schemas that travel outbound, and so need a wire twin
// when they carry a secret.
func requestSchemas() map[string]bool {
	out := map[string]bool{}
	for _, ns := range reg.Namespaces {
		for _, op := range ns.Operations {
			if op.RequestSchema != "" {
				out[strings.TrimPrefix(op.RequestSchema, "[]")] = true
			}
		}
	}
	return out
}

// schemaClosure is every schema reachable from an operation, transitively.
func schemaClosure() []string {
	seeds := map[string]bool{}
	for _, ns := range reg.Namespaces {
		for _, op := range ns.Operations {
			if op.RequestSchema != "" {
				seeds[strings.TrimPrefix(op.RequestSchema, "[]")] = true
			}
			if op.Response.Schema != "" {
				seeds[strings.TrimPrefix(op.Response.Schema, "[]")] = true
			}
		}
	}

	var refsIn func(raw json.RawMessage, found map[string]bool)
	refsIn = func(raw json.RawMessage, found map[string]bool) {
		var node any
		if err := json.Unmarshal(raw, &node); err != nil {
			return
		}
		var walk func(v any)
		walk = func(v any) {
			switch t := v.(type) {
			case map[string]any:
				for k, val := range t {
					if k == "$ref" {
						if s, ok := val.(string); ok {
							found[refName(s)] = true
						}
						continue
					}
					walk(val)
				}
			case []any:
				for _, item := range t {
					walk(item)
				}
			}
		}
		walk(node)
	}

	seen := map[string]bool{}
	frontier := sortedNames(seeds)
	for len(frontier) > 0 {
		name := frontier[len(frontier)-1]
		frontier = frontier[:len(frontier)-1]
		if seen[name] {
			continue
		}
		raw, ok := schemas[name]
		if !ok {
			continue
		}
		seen[name] = true
		found := map[string]bool{}
		refsIn(raw, found)
		for _, f := range sortedNames(found) {
			if !seen[f] {
				frontier = append(frontier, f)
			}
		}
	}
	return sortedNames(seen)
}

// ---------------------------------------------------------------------------
// Models
// ---------------------------------------------------------------------------

const modelsHeader = `// Request and response types for the CONTRACT §27 management surface.
//
// Three shapes recur and are worth knowing before reading:
//
//   - Sparse update bodies. Every field is a pointer with omitempty, so a field
//     you leave nil is ABSENT from the wire body rather than sent as null — a
//     body carrying one field changes one field (§27.4 rule 5).
//   - Replacement bodies. SetOrgSettings, the organization email config,
//     WebauthnAttestationPolicy and SetMtlsTrustAnchor have required fields,
//     because a PUT on those routes replaces rather than patches. Each has a
//     New… constructor taking every required field, so "I forgot one" is a
//     compile error at the call site rather than a silent zero value.
//   - Types carrying a secret. These hold a Sensitive, whose MarshalJSON emits
//     "[SENSITIVE]" — so a request type carrying one also has an unexported
//     wire twin and a toWire method. That is the single place a §27 secret is
//     unwrapped for the socket (§7 rule 4).

`

func emitModels() string {
	secrets := sensitiveFields()
	outbound := requestSchemas()
	replacements := replacementSchemas()
	var b strings.Builder
	b.WriteString(banner)
	b.WriteString(modelsHeader)
	b.WriteString("package axiam\n\nimport (\n\t\"github.com/google/uuid\"\n)\n\n")

	for _, name := range schemaClosure() {
		node := schemaByName(name)
		if node == nil {
			continue
		}
		typeName := pascal(name)

		if len(node.Enum) > 0 && node.typeName() == "string" {
			emitEnum(&b, typeName, node)
			continue
		}
		if tag, arms, ok := discriminated(node); ok {
			emitUnion(&b, typeName, node, tag, arms)
			continue
		}
		emitStruct(&b, typeName, name, secrets[name], outbound[name], replacements[name])
	}
	return b.String()
}

func emitEnum(b *strings.Builder, typeName string, node *schemaNode) {
	desc := node.Description
	if desc == "" {
		desc = fmt.Sprintf("is a %s value from the server's schema.", typeName)
	} else {
		desc = lowerFirstSentence(desc)
	}
	b.WriteString(goDoc("", typeName, desc))
	b.WriteString(fmt.Sprintf("type %s string\n\n", typeName))
	b.WriteString(fmt.Sprintf("// The %s values the server defines.\nconst (\n", typeName))
	for _, v := range node.Enum {
		s, ok := v.(string)
		if !ok {
			continue
		}
		b.WriteString(fmt.Sprintf("\t%s%s %s = %q\n", typeName, pascal(s), typeName, s))
	}
	b.WriteString(")\n\n")
}

// emitUnion renders an internally-tagged union as one struct.
//
// Go has no sum type, so the honest rendering is the tag plus every arm's
// fields as pointers, documented with which are present for which tag value. An
// interface would force a type switch on a shape the server describes with one
// string, and would not round-trip through encoding/json without a hand-written
// UnmarshalJSON per union.
func emitUnion(b *strings.Builder, typeName string, node *schemaNode, tag string, arms []unionArm) {
	desc := node.Description
	if desc == "" {
		desc = fmt.Sprintf("is a union discriminated by %s.", tag)
	} else {
		desc = lowerFirstSentence(desc)
	}
	var which []string
	merged := map[string]*schemaNode{}
	var order []string
	seen := map[string]bool{}
	for _, arm := range arms {
		var present []string
		for _, f := range arm.Order {
			if !seen[f] {
				seen[f] = true
				order = append(order, f)
			}
			merged[f] = arm.Props[f]
			present = append(present, f)
		}
		sort.Strings(present)
		if len(present) == 0 {
			which = append(which, fmt.Sprintf("%s=%q carries no further fields.", tag, arm.Value))
		} else {
			which = append(which, fmt.Sprintf("%s=%q carries %s.", tag, arm.Value, strings.Join(present, ", ")))
		}
	}
	sort.Strings(order)

	desc += "\n\nGo has no sum type, so every arm's fields live on this one struct as " +
		"pointers and " + tag + " says which are set: " + strings.Join(which, " ") +
		" A field belonging to another arm is nil."
	b.WriteString(goDoc("", typeName, desc))
	b.WriteString(fmt.Sprintf("type %s struct {\n", typeName))
	b.WriteString(goDoc("\t", pascal(tag), "is the discriminator: it says which of the fields below are set."))
	b.WriteString(fmt.Sprintf("\t%s string `json:%q`\n", pascal(tag), tag))
	for _, f := range order {
		emitField(b, f, merged[f], false, false)
	}
	b.WriteString("}\n\n")
}

func lowerFirstSentence(s string) string {
	s = strings.TrimSpace(strings.ReplaceAll(s, "\n", " "))
	if s == "" {
		return s
	}
	return s
}

func emitField(b *strings.Builder, name string, node *schemaNode, required, secret bool) {
	goName := pascal(name)
	typ := goType(node)
	if secret {
		typ = "Sensitive"
	}
	tag := name
	if !required {
		if !strings.HasPrefix(typ, "*") && !strings.HasPrefix(typ, "[]") && !strings.HasPrefix(typ, "map[") {
			typ = "*" + typ
		}
		tag += ",omitempty"
	}
	desc := ""
	if node != nil {
		desc = node.Description
	}
	if desc == "" {
		desc = fmt.Sprintf("carries the server's %s field.", name)
	} else {
		desc = lowerFirstSentence(desc)
	}
	if secret {
		desc += "\n\nSecret. Redacted from every fmt verb, log line and JSON rendering; " +
			"the raw value never leaves this package except on the wire."
	}
	b.WriteString(goDoc("\t", goName, desc))
	b.WriteString(fmt.Sprintf("\t%s %s `json:%q`\n", goName, typ, tag))
}

func emitStruct(b *strings.Builder, typeName, schemaName string, secrets map[string]bool, outbound, replacement bool) {
	props, order, required, desc := flatten(schemaName)
	if desc == "" {
		desc = fmt.Sprintf("is the %s schema from the server's OpenAPI document.", typeName)
	} else {
		desc = lowerFirstSentence(desc)
	}
	allOptional := len(order) > 0 && len(required) == 0
	if allOptional {
		desc += "\n\nEvery field is optional, so this is a SPARSE body: what you leave nil " +
			"is left unchanged, and is omitted from the wire request entirely rather than " +
			"sent as null (§27.4 rule 5)."
	}

	b.WriteString(goDoc("", typeName, desc))
	b.WriteString(fmt.Sprintf("type %s struct {\n", typeName))
	if len(order) == 0 {
		b.WriteString("\t// The server documents no fields on this schema.\n")
	}
	for _, f := range order {
		emitField(b, f, props[f], required[f], secrets[f])
	}
	b.WriteString("}\n\n")

	// A replacement body gets a constructor naming every required field.
	//
	// §27.9 asks that a replacement type "does not compile with a field
	// omitted". Go cannot express that on a struct — a keyed literal may always
	// leave fields at their zero value — so the strongest available guarantee is
	// a constructor that takes every one of them: forgetting a field is then a
	// compile error at the call site, and the documented way to build the body
	// is the way that cannot be half-filled.
	if replacement && len(order) > 0 {
		emitConstructor(b, typeName, props, order, required, secrets)
	}

	if len(secrets) > 0 && outbound {
		emitWireTwin(b, typeName, props, order, required, secrets)
	}
}

func emitConstructor(b *strings.Builder, typeName string, props map[string]*schemaNode, order []string, required map[string]bool, secrets map[string]bool) {
	var args, assigns []string
	var optional []string
	for _, f := range order {
		if !required[f] {
			optional = append(optional, pascal(f))
			continue
		}
		typ := goType(props[f])
		if secrets[f] {
			typ = "Sensitive"
		}
		args = append(args, fmt.Sprintf("%s %s", camel(f), typ))
		assigns = append(assigns, fmt.Sprintf("%s: %s", pascal(f), camel(f)))
	}
	if len(args) == 0 {
		return
	}
	doc := fmt.Sprintf(
		"builds a %s with every field the server requires.\n\nThis body REPLACES rather "+
			"than patches (§27.4 rule 5), so what you do not carry over from a prior read is "+
			"not preserved — it is overwritten. Taking every required field as an argument is "+
			"what makes forgetting one a compile error rather than a silent zero value on the "+
			"wire.", typeName)
	if len(optional) > 0 {
		doc += fmt.Sprintf("\n\nThe optional fields (%s) stay settable on the returned value, "+
			"and are equally overwritten when omitted — read the current state first and carry "+
			"them across.", strings.Join(optional, ", "))
	}
	b.WriteString(goDoc("", "New"+typeName, doc))
	b.WriteString(fmt.Sprintf("func New%s(%s) %s {\n\treturn %s{%s}\n}\n\n",
		typeName, strings.Join(args, ", "), typeName, typeName, strings.Join(assigns, ", ")))
}

func emitWireTwin(b *strings.Builder, typeName string, props map[string]*schemaNode, order []string, required map[string]bool, secrets map[string]bool) {
	wire := camel(typeName) + "Wire"
	b.WriteString(fmt.Sprintf(
		"// %s is the outbound twin of %s: plain strings where the public type\n"+
			"// holds a Sensitive.\n//\n"+
			"// It exists because Sensitive.MarshalJSON emits \"[SENSITIVE]\" — marshalling\n"+
			"// the public type directly would send the placeholder to the server.\n",
		wire, typeName))
	b.WriteString(fmt.Sprintf("type %s struct {\n", wire))
	for _, f := range order {
		typ := goType(props[f])
		if secrets[f] {
			typ = "string"
		}
		tag := f
		if !required[f] {
			if !strings.HasPrefix(typ, "*") && !strings.HasPrefix(typ, "[]") && !strings.HasPrefix(typ, "map[") {
				typ = "*" + typ
			}
			tag += ",omitempty"
		}
		b.WriteString(fmt.Sprintf("\t%s %s `json:%q`\n", pascal(f), typ, tag))
	}
	b.WriteString("}\n\n")

	b.WriteString(fmt.Sprintf(
		"// toWire unwraps the secret fields of a %s for the socket.\n//\n"+
			"// One of the few places a §27 secret is unwrapped, so \"put a secret on the\n"+
			"// wire\" stays a greppable call rather than fourteen (§7 rule 4).\n",
		typeName))
	b.WriteString(fmt.Sprintf("func (v %s) toWire() %s {\n\treturn %s{\n", typeName, wire, wire))
	for _, f := range order {
		if secrets[f] {
			if required[f] {
				b.WriteString(fmt.Sprintf("\t\t%s: v.%s.expose(),\n", pascal(f), pascal(f)))
			} else {
				b.WriteString(fmt.Sprintf("\t\t%s: exposeOptional(v.%s),\n", pascal(f), pascal(f)))
			}
			continue
		}
		b.WriteString(fmt.Sprintf("\t\t%s: v.%s,\n", pascal(f), pascal(f)))
	}
	b.WriteString("\t}\n}\n\n")
}

// ---------------------------------------------------------------------------
// Namespace handles
// ---------------------------------------------------------------------------

// implicitParams reports which of an operation's path params default from the
// client (§27.4 rule 3).
func implicitParams(ns string, op operation) map[string]bool {
	out := map[string]bool{}
	for _, p := range op.PathParams {
		if p.Name == "org_id" {
			out["org_id"] = true
		}
		if p.Name == "tenant_id" && implicitTenantNamespaces[ns] {
			out["tenant_id"] = true
		}
	}
	return out
}

func splitQuery(op operation) (req, opt []param) {
	for _, q := range op.QueryParams {
		if q.Name == "offset" || q.Name == "limit" {
			continue
		}
		if q.Required {
			req = append(req, q)
		} else {
			opt = append(opt, q)
		}
	}
	return req, opt
}

func filterTypeName(ns, opName string, opt []param) string {
	if len(opt) <= 2 {
		return ""
	}
	return pascal(ns) + pascal(opName) + "Filter"
}

// arg is one caller-facing parameter of a generated method.
type arg struct {
	name string
	typ  string
}

func operationArgs(ns, opName string, op operation) []arg {
	implicit := implicitParams(ns, op)
	var args []arg
	for _, p := range op.PathParams {
		if implicit[p.Name] {
			continue
		}
		typ := "string"
		if p.Format == "uuid" {
			typ = "uuid.UUID"
		}
		args = append(args, arg{camel(p.Name), typ})
	}
	reqQ, optQ := splitQuery(op)
	for _, q := range reqQ {
		args = append(args, arg{camel(q.Name), "string"})
	}
	if op.RequestBody == "schema" {
		args = append(args, arg{"body", pascal(op.RequestSchema)})
	} else if op.RequestBody == "untyped" {
		args = append(args, arg{"body", "any"})
	}
	if f := filterTypeName(ns, opName, optQ); f != "" {
		args = append(args, arg{"filter", f})
	} else {
		for _, q := range optQ {
			args = append(args, arg{camel(q.Name), "string"})
		}
	}
	if op.Paginated {
		args = append(args, arg{"page", "PageRequest"})
	}
	return args
}

func responseType(op operation) string {
	switch op.Response.Kind {
	case "none":
		return ""
	case "array":
		return "[]" + pascal(op.Response.Schema)
	case "page":
		return "Page[" + pascal(op.Response.Schema) + "]"
	}
	return pascal(op.Response.Schema)
}

func operationDoc(method, canonical string, op operation) string {
	text := fmt.Sprintf("issues %s %s.", op.Method, op.Path)
	if op.UpdateStyle == "replace" {
		text += "\n\nThis is a REPLACEMENT, not a patch (§27.4 rule 5). Every field of the " +
			"body is required, and what you do not carry over from a prior read is not " +
			"preserved — it is overwritten. Read first, change the field you mean, send the " +
			"whole thing back."
	}
	if len(op.SensitiveResponseFields) > 0 {
		text += fmt.Sprintf("\n\nReturns secret material, once. %s is returned by this call "+
			"and by no other; no later Get will return it again, and the Get projection has "+
			"no field where it was. Discarding the result destroys the credential "+
			"(§27.5 rule 3).", strings.Join(op.SensitiveResponseFields, ", "))
	}
	if op.Method != "GET" {
		text += "\n\nNot retried on failure (§27.4 rule 8): every write on this surface is " +
			"issued exactly once, including the ones that look idempotent."
	}
	return text
}

func emitNamespace(ns string, def namespace) string {
	handle := pascal(ns) + "API"
	var b strings.Builder
	b.WriteString(banner)
	b.WriteString(goDoc("", "", fmt.Sprintf("The %s management namespace (CONTRACT §27.1).\n\n%s", ns, def.Doc)))
	b.WriteString("\npackage axiam\n\n")

	var body strings.Builder

	// Filter structs for operations with more than two optional filters.
	for _, opName := range def.order {
		op := def.Operations[opName]
		_, optQ := splitQuery(op)
		name := filterTypeName(ns, opName, optQ)
		if name == "" {
			continue
		}
		body.WriteString(goDoc("", name, fmt.Sprintf(
			"holds the optional filters for %s.%s.\n\nSix loose optional string arguments "+
				"is a call site a reader cannot check and a refactor silently reorders, so "+
				"they travel as one struct. A zero field is not sent.", ns, opName)))
		body.WriteString(fmt.Sprintf("type %s struct {\n", name))
		for _, q := range optQ {
			body.WriteString(goDoc("\t", pascal(q.Name), fmt.Sprintf("filters on %s. Empty means unset.", q.Name)))
			body.WriteString(fmt.Sprintf("\t%s string\n", pascal(q.Name)))
		}
		body.WriteString("}\n\n")
	}

	hasOrg, hasTenant := false, false
	for _, opName := range def.order {
		implicit := implicitParams(ns, def.Operations[opName])
		hasOrg = hasOrg || implicit["org_id"]
		hasTenant = hasTenant || implicit["tenant_id"]
	}

	body.WriteString(goDoc("", handle, fmt.Sprintf(
		"is the %s namespace handle.\n\n%s\n\nAcquiring one performs no I/O and allocates "+
			"nothing meaningful (§27.2 rule 1); it holds the client and cannot be "+
			"constructed without one.", ns, def.Doc)))
	body.WriteString(fmt.Sprintf("type %s struct {\n\tc *Client\n\tscope namespaceScope\n}\n\n", handle))

	if hasOrg {
		body.WriteString(goDoc("", "InOrg", fmt.Sprintf(
			"addresses a different organization than the client's own.\n\n§27.4 rule 3: the "+
				"client's organization is the default, and a platform-admin token legitimately "+
				"overrides it. Returns a new handle; the original is unchanged.")))
		body.WriteString(fmt.Sprintf(
			"func (a *%s) InOrg(orgID uuid.UUID) *%s {\n\treturn &%s{c: a.c, scope: a.scope.withOrg(orgID)}\n}\n\n",
			handle, handle, handle))
	}
	if hasTenant {
		body.WriteString(goDoc("", "ForTenant",
			"addresses a different tenant than the client's own (§27.4 rule 3).\n\nReturns a new handle; the original is unchanged."))
		body.WriteString(fmt.Sprintf(
			"func (a *%s) ForTenant(tenantID uuid.UUID) *%s {\n\treturn &%s{c: a.c, scope: a.scope.withTenant(tenantID)}\n}\n\n",
			handle, handle, handle))
	}

	for _, opName := range def.order {
		emitOperation(&body, ns, opName, def.Operations[opName], handle)
	}

	rendered := body.String()
	// Imports are derived from what was actually rendered rather than assumed,
	// so a namespace with no paths to format does not import fmt and trip the
	// unused-import compile error.
	var std []string
	std = append(std, "\"context\"")
	if strings.Contains(rendered, "fmt.Sprintf") {
		std = append(std, "\"fmt\"")
	}
	if strings.Contains(rendered, "http.Method") {
		std = append(std, "\"net/http\"")
	}
	if strings.Contains(rendered, "url.Values") || strings.Contains(rendered, "url.PathEscape") {
		std = append(std, "\"net/url\"")
	}
	sort.Strings(std)
	imports := std
	if strings.Contains(rendered, "uuid.UUID") {
		imports = append(imports, "", "\"github.com/google/uuid\"")
	}
	b.WriteString("import (\n")
	for _, imp := range imports {
		if imp == "" {
			b.WriteString("\n")
			continue
		}
		b.WriteString("\t" + imp + "\n")
	}
	b.WriteString(")\n\n")
	b.WriteString(rendered)
	return b.String()
}

func emitOperation(b *strings.Builder, ns, opName string, op operation, handle string) {
	canonical := ns + "." + opName
	method := pascal(opName)
	implicit := implicitParams(ns, op)
	args := operationArgs(ns, opName, op)

	var sig []string
	sig = append(sig, "ctx context.Context")
	for _, a := range args {
		sig = append(sig, a.name+" "+a.typ)
	}

	ret := responseType(op)
	retSig := "error"
	if ret != "" {
		retSig = "(" + ret + ", error)"
	}

	// The call builder, shared by the operation and (where paginated) its
	// ListAll walker, so the path, query and body are decided in one place.
	builder := fmt.Sprintf("call%s%s", pascal(ns), method)
	// A builder can only fail where it has to resolve an implicit {org_id} or
	// {tenant_id} from the client. Everywhere else it is total, and giving it an
	// error return anyway would put an unreachable branch in every one of the
	// 146 operations — dead code that no test can honestly cover.
	fallible := len(implicit) > 0
	var pre strings.Builder
	route := op.Path
	fmtArgs := []string{}
	for _, p := range op.PathParams {
		if implicit[p.Name] {
			fn := "resolveOrg"
			if p.Name == "tenant_id" {
				fn = "resolveTenant"
			}
			pre.WriteString(fmt.Sprintf("\t%s, err := a.c.%s(a.scope, %q)\n\tif err != nil {\n\t\treturn managementCall{}, err\n\t}\n",
				camel(p.Name), fn, canonical))
			route = strings.ReplaceAll(route, "{"+p.Name+"}", "%s")
			fmtArgs = append(fmtArgs, camel(p.Name)+".String()")
			continue
		}
		route = strings.ReplaceAll(route, "{"+p.Name+"}", "%s")
		if p.Format == "uuid" {
			fmtArgs = append(fmtArgs, camel(p.Name)+".String()")
		} else {
			fmtArgs = append(fmtArgs, "url.PathEscape("+camel(p.Name)+")")
		}
	}

	reqQ, optQ := splitQuery(op)
	filter := filterTypeName(ns, opName, optQ)
	var q strings.Builder
	if op.Paginated || len(reqQ) > 0 || len(optQ) > 0 {
		q.WriteString("\tquery := url.Values{}\n")
		for _, p := range reqQ {
			q.WriteString(fmt.Sprintf("\tquery.Set(%q, %s)\n", p.Name, camel(p.Name)))
		}
		for _, p := range optQ {
			src := camel(p.Name)
			if filter != "" {
				src = "filter." + pascal(p.Name)
			}
			q.WriteString(fmt.Sprintf("\tif %s != \"\" {\n\t\tquery.Set(%q, %s)\n\t}\n", src, p.Name, src))
		}
		if op.Paginated {
			q.WriteString("\tquery = pageQuery(page, query)\n")
		}
	}

	bodyExpr := "nil"
	if op.RequestBody == "schema" {
		if hasSecretRequest(op.RequestSchema) {
			bodyExpr = "body.toWire()"
		} else {
			bodyExpr = "body"
		}
	} else if op.RequestBody == "untyped" {
		bodyExpr = "body"
	}

	// Builder signature mirrors the operation's, minus ctx.
	var bsig []string
	for _, a := range args {
		bsig = append(bsig, a.name+" "+a.typ)
	}
	b.WriteString(fmt.Sprintf("// %s builds the %s call. Shared by the operation and its\n// auto-paging form, so the path, query and body are decided in one place.\n",
		builder, canonical))
	builderRet := "managementCall"
	if fallible {
		builderRet = "(managementCall, error)"
	}
	b.WriteString(fmt.Sprintf("func (a *%s) %s(%s) %s {\n", handle, builder, strings.Join(bsig, ", "), builderRet))
	b.WriteString(pre.String())
	b.WriteString(q.String())
	pathExpr := fmt.Sprintf("%q", route)
	if len(fmtArgs) > 0 {
		pathExpr = fmt.Sprintf("fmt.Sprintf(%q, %s)", route, strings.Join(fmtArgs, ", "))
	}
	b.WriteString("\treturn managementCall{\n")
	b.WriteString(fmt.Sprintf("\t\toperation:    %q,\n", canonical))
	b.WriteString(fmt.Sprintf("\t\tmethod:       %s,\n", httpMethodConst(op.Method)))
	b.WriteString(fmt.Sprintf("\t\tpathTemplate: %q,\n", op.Path))
	b.WriteString(fmt.Sprintf("\t\tpath:         %s,\n", pathExpr))
	if q.Len() > 0 {
		b.WriteString("\t\tquery:        query,\n")
	}
	if bodyExpr != "nil" {
		b.WriteString(fmt.Sprintf("\t\tbody:         %s,\n", bodyExpr))
	}
	if fallible {
		b.WriteString("\t}, nil\n}\n\n")
	} else {
		b.WriteString("\t}\n}\n\n")
	}

	// The operation itself.
	b.WriteString(goDoc("", method, operationDoc(method, canonical, op)))
	b.WriteString(fmt.Sprintf("func (a *%s) %s(%s) %s {\n", handle, method, strings.Join(sig, ", "), retSig))
	var fwd []string
	for _, a := range args {
		fwd = append(fwd, a.name)
	}
	if fallible {
		failure := "return err"
		if ret != "" {
			failure = fmt.Sprintf("var zero %s\n\t\treturn zero, err", ret)
		}
		b.WriteString(fmt.Sprintf("\tcall, err := a.%s(%s)\n\tif err != nil {\n\t\t%s\n\t}\n",
			builder, strings.Join(fwd, ", "), failure))
	} else {
		b.WriteString(fmt.Sprintf("\tcall := a.%s(%s)\n", builder, strings.Join(fwd, ", ")))
	}
	if ret == "" {
		b.WriteString("\treturn sendManagementNoContent(ctx, a.c, call)\n}\n\n")
	} else {
		b.WriteString(fmt.Sprintf("\treturn sendManagement[%s](ctx, a.c, call)\n}\n\n", ret))
	}

	if op.Paginated {
		inner := strings.TrimSuffix(strings.TrimPrefix(ret, "Page["), "]")
		var lead []arg
		for _, a := range args {
			if a.name != "page" {
				lead = append(lead, a)
			}
		}
		var leadSig []string
		var leadFwd []string
		leadSig = append(leadSig, "ctx context.Context")
		for _, a := range lead {
			leadSig = append(leadSig, a.name+" "+a.typ)
			leadFwd = append(leadFwd, a.name)
		}
		leadSig = append(leadSig, "start PageRequest")
		b.WriteString(goDoc("", method+"All", fmt.Sprintf(
			"walks %s to exhaustion, concatenating every page.\n\nThe auto-paging form §27.4 "+
				"rule 4 requires. It stops on an empty page even if Total disagrees, so a "+
				"misreporting server costs one wasted request rather than an unbounded loop.",
			canonical)))
		b.WriteString(fmt.Sprintf("func (a *%s) %sAll(%s) ([]%s, error) {\n", handle, method, strings.Join(leadSig, ", "), inner))
		callFwd := append(append([]string{"ctx"}, leadFwd...), "p")
		b.WriteString(fmt.Sprintf(
			"\treturn collectPages(ctx, start, func(ctx context.Context, p PageRequest) (Page[%s], error) {\n\t\treturn a.%s(%s)\n\t})\n}\n\n",
			inner, method, strings.Join(callFwd, ", ")))
	}
}

func httpMethodConst(m string) string {
	switch m {
	case "GET":
		return "http.MethodGet"
	case "POST":
		return "http.MethodPost"
	case "PUT":
		return "http.MethodPut"
	case "DELETE":
		return "http.MethodDelete"
	}
	return fmt.Sprintf("%q", m)
}

func hasSecretRequest(schema string) bool {
	if schema == "" {
		return false
	}
	return len(sensitiveFields()[strings.TrimPrefix(schema, "[]")]) > 0
}

// ---------------------------------------------------------------------------
// The accessors on *Client
// ---------------------------------------------------------------------------

func emitAPI() string {
	var b strings.Builder
	b.WriteString(banner)
	b.WriteString(goDoc("", "", "One accessor per §27 namespace.\n\n"+
		"§27.2 makes this namespacing normative rather than stylistic: twenty namespaces "+
		"have a List and fourteen a Get, so flattening 146 operations onto the Client "+
		"would need a disambiguating prefix invented once per operation — and would bury "+
		"the eight §1 methods most callers actually want under five times as many they "+
		"do not.\n\nEach accessor builds its handle on access and performs no I/O "+
		"(§27.2 rule 1), so holding one costs nothing and none of them runs at "+
		"construction."))
	b.WriteString("\npackage axiam\n\n")
	for _, ns := range reg.order {
		def := reg.Namespaces[ns]
		handle := pascal(ns) + "API"
		b.WriteString(goDoc("", pascal(ns), fmt.Sprintf(
			"returns the %s management namespace handle.\n\n%s", ns, def.Doc)))
		b.WriteString(fmt.Sprintf("func (c *Client) %s() *%s {\n\treturn &%s{c: c}\n}\n\n",
			pascal(ns), handle, handle))
	}
	return b.String()
}

// ---------------------------------------------------------------------------
// The generated conformance test
// ---------------------------------------------------------------------------

func exampleJSON(n *schemaNode, depth int) any {
	if depth > 6 || n == nil {
		return nil
	}
	if n.Ref != "" {
		return exampleJSON(schemaByName(refName(n.Ref)), depth+1)
	}
	if inner := n.nullableRef(); inner != "" {
		return exampleJSON(schemaByName(inner), depth+1)
	}
	if len(n.Enum) > 0 {
		return n.Enum[0]
	}
	variants := n.OneOf
	if len(variants) == 0 {
		variants = n.AnyOf
	}
	if len(variants) > 0 {
		for _, v := range variants {
			if v.typeName() != "null" {
				return exampleJSON(v, depth+1)
			}
		}
		return nil
	}
	if len(n.AllOf) > 0 {
		merged := map[string]any{}
		for _, part := range n.AllOf {
			if got, ok := exampleJSON(part, depth+1).(map[string]any); ok {
				for k, v := range got {
					merged[k] = v
				}
			}
		}
		for _, p := range propNames(n) {
			for _, r := range n.Required {
				if r == p {
					merged[p] = exampleJSON(n.Properties[p], depth+1)
				}
			}
		}
		return merged
	}
	switch n.typeName() {
	case "object":
		out := map[string]any{}
		for _, p := range propNames(n) {
			for _, r := range n.Required {
				if r == p {
					out[p] = exampleJSON(n.Properties[p], depth+1)
				}
			}
		}
		return out
	case "array":
		return []any{}
	case "integer", "number":
		return 1
	case "boolean":
		return true
	case "string":
		switch n.Format {
		case "uuid":
			return exampleUUID
		case "date-time":
			return exampleTime
		}
		return "example"
	}
	if len(n.Properties) > 0 {
		out := map[string]any{}
		for _, p := range propNames(n) {
			for _, r := range n.Required {
				if r == p {
					out[p] = exampleJSON(n.Properties[p], depth+1)
				}
			}
		}
		return out
	}
	return map[string]any{}
}

func exampleResponse(op operation) string {
	if op.Response.Kind == "none" {
		return `""`
	}
	one := exampleJSON(schemaByName(op.Response.Schema), 0)
	var payload any = one
	switch op.Response.Kind {
	case "array":
		payload = []any{one}
	case "page":
		payload = map[string]any{"items": []any{one}, "total": 1, "offset": 0, "limit": 50}
	}
	encoded, err := json.Marshal(payload)
	if err != nil {
		return `""`
	}
	return "`" + string(encoded) + "`"
}

// goLiteral builds a Go expression for a minimal valid value of a schema.
func goLiteral(n *schemaNode, secrets map[string]bool, field string, depth int) string {
	if depth > 6 || n == nil {
		return "nil"
	}
	if secrets[field] {
		return `Sensitive("example")`
	}
	if n.Ref != "" {
		return literalFor(refName(n.Ref), nil, depth+1)
	}
	if n.nullableRef() != "" || len(n.OneOf) > 0 || len(n.AnyOf) > 0 {
		return "nil"
	}
	if len(n.Enum) > 0 {
		if s, ok := n.Enum[0].(string); ok {
			return fmt.Sprintf("%q", s)
		}
	}
	switch n.typeName() {
	case "array":
		return goType(n) + "{}"
	case "integer":
		return "1"
	case "number":
		return "1"
	case "boolean":
		return "true"
	case "string":
		switch n.Format {
		case "uuid":
			return "exampleID"
		case "date-time":
			return fmt.Sprintf("%q", exampleTime)
		}
		return `"example"`
	case "object":
		return "map[string]any{}"
	}
	return "nil"
}

func literalFor(name string, secrets map[string]bool, depth int) string {
	node := schemaByName(name)
	if node == nil {
		return "nil"
	}
	if len(node.Enum) > 0 && node.typeName() == "string" {
		if s, ok := node.Enum[0].(string); ok {
			return fmt.Sprintf("%s%s", pascal(name), pascal(s))
		}
	}
	if tag, arms, ok := discriminated(node); ok && len(arms) > 0 {
		arm := arms[0]
		parts := []string{fmt.Sprintf("%s: %q", pascal(tag), arm.Value)}
		for _, f := range arm.Order {
			if arm.Req[f] {
				parts = append(parts, fmt.Sprintf("%s: ptr(%s)", pascal(f), goLiteral(arm.Props[f], nil, f, depth+1)))
			}
		}
		return fmt.Sprintf("%s{%s}", pascal(name), strings.Join(parts, ", "))
	}
	props, order, required, _ := flatten(name)
	var parts []string
	for _, f := range order {
		if !required[f] {
			continue
		}
		parts = append(parts, fmt.Sprintf("%s: %s", pascal(f), goLiteral(props[f], secrets, f, depth+1)))
	}
	return fmt.Sprintf("%s{%s}", pascal(name), strings.Join(parts, ", "))
}

func callArguments(ns, opName string, op operation, secrets map[string]map[string]bool) ([]string, string) {
	implicit := implicitParams(ns, op)
	var args []string
	route := op.Path
	for _, p := range op.PathParams {
		if implicit[p.Name] {
			placeholder := "\" + orgID.String() + \""
			if p.Name == "tenant_id" {
				placeholder = "\" + tenantID.String() + \""
			}
			route = strings.ReplaceAll(route, "{"+p.Name+"}", placeholder)
			continue
		}
		if p.Format == "uuid" {
			args = append(args, "exampleID")
			route = strings.ReplaceAll(route, "{"+p.Name+"}", "\" + exampleID.String() + \"")
		} else {
			args = append(args, `"example"`)
			route = strings.ReplaceAll(route, "{"+p.Name+"}", "example")
		}
	}
	reqQ, optQ := splitQuery(op)
	for range reqQ {
		args = append(args, `"example"`)
	}
	if op.RequestBody == "schema" {
		args = append(args, literalFor(op.RequestSchema, secrets[op.RequestSchema], 0))
	} else if op.RequestBody == "untyped" {
		args = append(args, "map[string]any{}")
	}
	if f := filterTypeName(ns, opName, optQ); f != "" {
		args = append(args, f+"{}")
	} else {
		for range optQ {
			args = append(args, `""`)
		}
	}
	if op.Paginated {
		args = append(args, "Limited(50)")
	}
	return args, route
}

func emitTest() string {
	secrets := sensitiveFields()
	var b strings.Builder
	var all []string
	b.WriteString(banner)
	b.WriteString(goDoc("", "", "Generated §27 surface conformance: every operation is reached once.\n\n"+
		"Per operation: the SDK issues the registry's method against the registry's path, "+
		"and decodes the response shape openapi.json declares. Semantics that are not "+
		"per-operation — sparse-update key sets, secret redaction, error mapping, "+
		"pagination walks, the manifest — are tested by hand in management_semantics_test.go "+
		"and its neighbours."))
	b.WriteString("\npackage axiam\n\n@@IMPORTS@@")

	for _, ns := range reg.order {
		def := reg.Namespaces[ns]
		for _, opName := range def.order {
			op := def.Operations[opName]
			canonical := ns + "." + opName
			all = append(all, canonical)
			args, route := callArguments(ns, opName, op, secrets)
			testName := "TestManagementSurface_" + pascal(ns) + pascal(opName)

			b.WriteString(fmt.Sprintf("// %s exercises %s.\nfunc %s(t *testing.T) {\n",
				testName, canonical, testName))
			b.WriteString("\tsrv, c := managementServer(t)\n")
			b.WriteString(fmt.Sprintf("\tsrv.mount(%s, \"%s\", %d, %s)\n",
				httpMethodConst(op.Method), route, op.Response.Status, exampleResponse(op)))
			call := fmt.Sprintf("c.%s().%s(context.Background()", pascal(ns), pascal(opName))
			for _, a := range args {
				call += ", " + a
			}
			call += ")"
			if op.Response.Kind == "none" {
				b.WriteString(fmt.Sprintf("\tif err := %s; err != nil {\n\t\tt.Fatalf(\"%s: %%v\", err)\n\t}\n", call, canonical))
			} else {
				b.WriteString(fmt.Sprintf("\tif _, err := %s; err != nil {\n\t\tt.Fatalf(\"%s: %%v\", err)\n\t}\n", call, canonical))
			}
			if op.Paginated {
				var lead []string
				for _, a := range args {
					if a != "Limited(50)" {
						lead = append(lead, a)
					}
				}
				allCall := fmt.Sprintf("c.%s().%sAll(context.Background()", pascal(ns), pascal(opName))
				for _, a := range lead {
					allCall += ", " + a
				}
				allCall += ", Limited(50))"
				b.WriteString(fmt.Sprintf("\tif _, err := %s; err != nil {\n\t\tt.Fatalf(\"%s (all): %%v\", err)\n\t}\n", allCall, canonical))
			}
			b.WriteString("}\n\n")
		}
	}

	// §27.9: "a slug-only client calling a {tenant_id} route fails client-side
	// with zero wire calls". Asserted for EVERY route that resolves an implicit
	// {org_id} or {tenant_id} rather than for one example, because the refusal
	// is generated per operation and one hand-written case would leave the other
	// twenty-nine unproven.
	b.WriteString(goDoc("", "TestGeneratedImplicitContextRefusalsMakeNoWireCall",
		"is §27.9: every route with an implicit {org_id} or {tenant_id} refuses "+
			"client-side when the client has resolved neither, without reaching the network."))
	b.WriteString("func TestGeneratedImplicitContextRefusalsMakeNoWireCall(t *testing.T) {\n")
	b.WriteString("\tsrv, anonymous := anonymousManagementServer(t)\n")
	b.WriteString("\tbefore := srv.totalCalls()\n")
	b.WriteString("\tctx := context.Background()\n")
	for _, ns := range reg.order {
		def := reg.Namespaces[ns]
		for _, opName := range def.order {
			op := def.Operations[opName]
			if len(implicitParams(ns, op)) == 0 {
				continue
			}
			canonical := ns + "." + opName
			args, _ := callArguments(ns, opName, op, secrets)
			call := fmt.Sprintf("anonymous.%s().%s(ctx", pascal(ns), pascal(opName))
			for _, a := range args {
				call += ", " + a
			}
			call += ")"
			assign := "_, err :="
			if op.Response.Kind == "none" {
				assign = "err :="
			}
			b.WriteString(fmt.Sprintf("\tif %s %s; err == nil {\n\t\tt.Errorf(%q)\n\t}\n",
				assign, call, canonical+": expected a client-side refusal with no resolved context"))
		}
	}
	b.WriteString("\tif got := srv.totalCalls(); got != before {\n")
	b.WriteString("\t\tt.Fatalf(\"expected zero wire calls, %d were made\", got-before)\n\t}\n")
	b.WriteString("}\n\n")

	sort.Strings(all)
	b.WriteString(goDoc("", "generatedSurface", "is every operation the cases above reach."))
	b.WriteString("var generatedSurface = []string{\n")
	for _, name := range all {
		b.WriteString(fmt.Sprintf("\t%q,\n", name))
	}
	b.WriteString("}\n\n")
	// §27.5 conformance, generated from the registry's own sensitive-field
	// lists. This exists because a generator that silently drops a field is a
	// class of bug the path-and-status conformance cases above cannot see: the
	// call still reaches the right route, and the secret simply is not there.
	type secretCase struct{ schema, field string }
	var secretCases []secretCase
	seenSecret := map[string]bool{}
	for _, ns := range reg.order {
		def := reg.Namespaces[ns]
		for _, opName := range def.order {
			op := def.Operations[opName]
			for _, pair := range []struct {
				schema string
				fields []string
			}{
				{op.Response.Schema, op.SensitiveResponseFields},
				{op.RequestSchema, op.SensitiveRequestFields},
			} {
				if pair.schema == "" {
					continue
				}
				for _, f := range pair.fields {
					key := pair.schema + "." + f
					if seenSecret[key] {
						continue
					}
					seenSecret[key] = true
					secretCases = append(secretCases, secretCase{strings.TrimPrefix(pair.schema, "[]"), f})
				}
			}
		}
	}
	sort.Slice(secretCases, func(i, j int) bool {
		if secretCases[i].schema != secretCases[j].schema {
			return secretCases[i].schema < secretCases[j].schema
		}
		return secretCases[i].field < secretCases[j].field
	})

	b.WriteString(goDoc("", "TestGeneratedSecretFieldsAreSensitive",
		"is §27.5: every field the registry marks secret exists on its model and is a "+
			"Sensitive.\n\nA generated model that silently dropped one would still pass every "+
			"path-and-status case above — the call reaches the right route and the secret is "+
			"simply absent — which is exactly how a one-time credential goes missing."))
	b.WriteString("func TestGeneratedSecretFieldsAreSensitive(t *testing.T) {\n")
	b.WriteString("\tsensitiveType := reflect.TypeOf(Sensitive(\"\"))\n")
	b.WriteString("\tfor _, tc := range []struct {\n\t\tmodel any\n\t\tschema, field string\n\t}{\n")
	for _, sc := range secretCases {
		b.WriteString(fmt.Sprintf("\t\t{%s{}, %q, %q},\n", pascal(sc.schema), sc.schema, sc.field))
	}
	b.WriteString("\t} {\n")
	b.WriteString(`		typ := reflect.TypeOf(tc.model)
		var found *reflect.StructField
		for i := 0; i < typ.NumField(); i++ {
			f := typ.Field(i)
			tag := f.Tag.Get("json")
			if name, _, _ := strings.Cut(tag, ","); name == tc.field {
				found = &f
				break
			}
		}
		if found == nil {
			t.Errorf("%s: the registry marks %q secret, but the generated model has no such field",
				tc.schema, tc.field)
			continue
		}
		got := found.Type
		if got.Kind() == reflect.Pointer {
			got = got.Elem()
		}
		if got != sensitiveType {
			t.Errorf("%s.%s is %s, not Sensitive: it would be logged in the clear",
				tc.schema, tc.field, found.Type)
		}
	}
}

`)

	b.WriteString(goDoc("", "TestGeneratedSurfaceCoversTheRegistry",
		"is §27.9: a partial regeneration must fail here, not ship 140 of 146.\n\n"+
			"Asserting the whole set rather than the count catches a regeneration that "+
			"dropped one operation and gained another."))
	b.WriteString(fmt.Sprintf(`func TestGeneratedSurfaceCoversTheRegistry(t *testing.T) {
	expected := expectedSurface(t)
	if len(generatedSurface) != %d {
		t.Fatalf("generated surface has %%d operations, registry declares %d", len(generatedSurface))
	}
	if len(generatedSurface) != len(expected) {
		t.Fatalf("generated %%d operations, registry declares %%d", len(generatedSurface), len(expected))
	}
	for i := range expected {
		if generatedSurface[i] != expected[i] {
			t.Fatalf("operation %%d: generated %%q, registry declares %%q", i, generatedSurface[i], expected[i])
		}
	}
}

`, reg.OperationCount, reg.OperationCount))

	// Imports derived from what was rendered, so a surface that happens not to
	// carry a uuid-typed body does not import uuid and fail to compile.
	rendered := b.String()
	imports := "import (\n\t\"context\"\n\t\"net/http\"\n\t\"reflect\"\n\t\"strings\"\n\t\"testing\"\n"
	if strings.Contains(rendered, "uuid.UUID") || strings.Contains(rendered, "uuid.MustParse") {
		imports += "\n\t\"github.com/google/uuid\"\n"
	}
	imports += ")\n\n"
	return strings.Replace(rendered, "@@IMPORTS@@", imports, 1)
}

// ---------------------------------------------------------------------------
// main
// ---------------------------------------------------------------------------

func build() (map[string]string, error) {
	files := map[string]string{
		"management_models.go":                 emitModels(),
		"management_api.go":                    emitAPI(),
		"management_surface_generated_test.go": emitTest(),
	}
	for _, ns := range reg.order {
		files["management_"+ns+".go"] = emitNamespace(ns, reg.Namespaces[ns])
	}

	formatted := make(map[string]string, len(files))
	for name, src := range files {
		out, err := format.Source([]byte(src))
		if err != nil {
			return nil, fmt.Errorf("gofmt rejected generated %s: %w", name, err)
		}
		formatted[name] = string(out)
	}
	return formatted, nil
}

func main() {
	check := flag.Bool("check", false, "verify the committed output is current instead of writing it")
	flag.Parse()

	wd, err := os.Getwd()
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	root = wd

	if err := load(); err != nil {
		fmt.Fprintf(os.Stderr, "could not read the registry or spec: %v\n", err)
		os.Exit(1)
	}

	files, err := build()
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	if *check {
		var stale []string
		for _, name := range sortedNames(files) {
			existing, err := os.ReadFile(filepath.Join(root, name))
			if err != nil || string(existing) != files[name] {
				stale = append(stale, name)
			}
		}
		if len(stale) > 0 {
			for _, name := range stale {
				fmt.Fprintf(os.Stderr, "FAIL: %s is stale\n", name)
			}
			fmt.Fprintln(os.Stderr, "run `go run ./internal/cmd/genmanagement`")
			os.Exit(1)
		}
		fmt.Printf("OK: %d generated files are current (%d operations)\n", len(files), reg.OperationCount)
		return
	}

	for _, name := range sortedNames(files) {
		if err := os.WriteFile(filepath.Join(root, name), []byte(files[name]), 0o644); err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}
	}
	fmt.Printf("wrote %d files: %d operations across %d namespaces\n",
		len(files), reg.OperationCount, reg.NamespaceCount)
}
